/**
 * COMPREHENSIVE SOLAR INVERTER FAULT DATABASE - PART 2
 * Covers: GoodWe, Sungrow, SolarEdge, Enphase, Sofar, Solis
 * 200+ Additional Fault Codes
 */

import { InverterFault } from './inverter-faults-part1';

// ═══════════════════════════════════════════════════════════════════════════════
// GOODWE INVERTER FAULT CODES (50+ Codes)
// Models: DNS, GW, ES, EM, ET, BT, SBP Series
// ═══════════════════════════════════════════════════════════════════════════════

export const GOODWE_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'E001', name: 'Grid Over Voltage', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'AC voltage exceeds maximum limit (typically >270V).', causes: ['Utility voltage high', 'Grid impedance', 'Transformer tap'], symptoms: ['No export', 'E001 displayed'], solution: 'Check grid voltage and report to utility if high.', steps: ['Measure voltage', 'Compare to settings', 'Report if needed'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'E002', name: 'Grid Under Voltage', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'AC voltage below minimum limit.', causes: ['Utility low', 'Cable undersized', 'Heavy loads'], symptoms: ['No export', 'E002'], solution: 'Improve grid voltage.', steps: ['Measure voltage', 'Check cables', 'Report to utility'], prevention: ['Proper cable sizing'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'E003', name: 'Grid Over Frequency', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'Grid frequency above 52Hz.', causes: ['Grid instability', 'Generator issue'], symptoms: ['Disconnection', 'E003'], solution: 'Wait for grid stability.', steps: ['Monitor frequency'], prevention: ['Grid monitoring'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'E004', name: 'Grid Under Frequency', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'Grid frequency below 47.5Hz.', causes: ['Grid overload', 'Utility issue'], symptoms: ['Disconnection', 'E004'], solution: 'Wait for recovery.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'E005', name: 'Grid Impedance High', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'Medium', category: 'Grid', description: 'Grid impedance exceeds acceptable level.', causes: ['Weak grid', 'Long cables', 'Small transformer'], symptoms: ['Voltage rise', 'E005'], solution: 'Improve grid connection.', steps: ['Check cable sizing', 'Verify transformer'], prevention: ['Proper design'], tools: ['Impedance meter'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-100,000' },
  { code: 'E006', name: 'No Utility', brand: 'GoodWe', model: 'All Models', severity: 'Low', category: 'Grid', description: 'No grid voltage detected.', causes: ['Power outage', 'Breaker off'], symptoms: ['No operation', 'E006'], solution: 'Restore grid.', steps: ['Check utility', 'Check breakers'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'E007', name: 'Island Detected', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'Critical', category: 'Grid', description: 'Possible islanding condition detected.', causes: ['Grid disconnection', 'Generator interference'], symptoms: ['Immediate stop', 'E007'], solution: 'Verify grid connection.', steps: ['Check grid', 'Verify bonding'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'E008', name: 'Grid Relay Fault', brand: 'GoodWe', model: 'All Grid-Tie', severity: 'Critical', category: 'Hardware', description: 'Internal relay test failed.', causes: ['Relay wear', 'Control fault'], symptoms: ['Cannot connect', 'E008'], solution: 'Service required.', steps: ['Document', 'Contact service'], prevention: ['Regular maintenance'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },

  // PV Faults
  { code: 'E010', name: 'PV1 Over Voltage', brand: 'GoodWe', model: 'All Models', severity: 'Critical', category: 'PV', description: 'String 1 voltage exceeds maximum.', causes: ['Too many panels', 'Cold weather'], symptoms: ['Won\'t start', 'E010'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E011', name: 'PV2 Over Voltage', brand: 'GoodWe', model: 'Dual MPPT', severity: 'Critical', category: 'PV', description: 'String 2 voltage exceeds maximum.', causes: ['Same as E010'], symptoms: ['Won\'t start', 'E011'], solution: 'Reduce string voltage.', steps: ['Measure String 2 Voc'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E012', name: 'PV Insulation Low', brand: 'GoodWe', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault - insulation resistance too low.', causes: ['Cable damage', 'Water ingress', 'Panel fault'], symptoms: ['Won\'t operate', 'E012'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Find fault', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E013', name: 'PV1 Connection Fault', brand: 'GoodWe', model: 'All Models', severity: 'Medium', category: 'PV', description: 'String 1 connection problem.', causes: ['Loose MC4', 'Cable damage'], symptoms: ['String not producing', 'E013'], solution: 'Check connections.', steps: ['Inspect connectors', 'Check continuity'], prevention: ['Quality connectors'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'E014', name: 'PV2 Connection Fault', brand: 'GoodWe', model: 'Dual MPPT', severity: 'Medium', category: 'PV', description: 'String 2 connection problem.', causes: ['Same as E013'], symptoms: ['String 2 not producing', 'E014'], solution: 'Check String 2 connections.', steps: ['Inspect connectors'], prevention: ['Quality installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'E015', name: 'PV Over Current', brand: 'GoodWe', model: 'All Models', severity: 'High', category: 'PV', description: 'DC input current exceeds maximum.', causes: ['Too many parallel strings'], symptoms: ['Shutdown', 'E015'], solution: 'Reduce parallel strings.', steps: ['Measure current', 'Reconfigure'], prevention: ['Proper design'], tools: ['Clamp meter'], estimatedTime: '2-6 hours', estimatedCost: 'KES 5,000-30,000' },
  { code: 'E016', name: 'PV Reverse Polarity', brand: 'GoodWe', model: 'All Models', severity: 'High', category: 'PV', description: 'DC polarity is reversed.', causes: ['Installation error'], symptoms: ['No start', 'E016'], solution: 'Correct polarity.', steps: ['Check polarity', 'Correct'], prevention: ['Careful installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },

  // Inverter Faults
  { code: 'E020', name: 'Inverter Over Temperature', brand: 'GoodWe', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal temperature too high.', causes: ['Poor ventilation', 'High ambient'], symptoms: ['Derating', 'E020'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Add shading'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'E021', name: 'Module Temperature High', brand: 'GoodWe', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Power module overheating.', causes: ['Overload', 'Cooling failure'], symptoms: ['Shutdown', 'E021'], solution: 'Reduce load, improve cooling.', steps: ['Check loading', 'Check cooling'], prevention: ['Proper sizing'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-75,000' },
  { code: 'E022', name: 'Ambient Temperature High', brand: 'GoodWe', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Surrounding temperature too high.', causes: ['Hot location'], symptoms: ['Derating', 'E022'], solution: 'Improve location.', steps: ['Measure ambient', 'Improve ventilation'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '2-8 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'E023', name: 'Fan Fault', brand: 'GoodWe', model: 'Models with fan', severity: 'Medium', category: 'Hardware', description: 'Cooling fan malfunction.', causes: ['Motor failure', 'Obstruction'], symptoms: ['Overheating', 'E023'], solution: 'Replace fan.', steps: ['Check fan', 'Clear/replace'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: 'E024', name: 'DC Bus Over Voltage', brand: 'GoodWe', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal DC bus voltage too high.', causes: ['Grid loss during export', 'Surge'], symptoms: ['Shutdown', 'E024'], solution: 'Check and restart.', steps: ['Check PV voltage', 'Power cycle'], prevention: ['Surge protection'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'E025', name: 'Hardware Fault', brand: 'GoodWe', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal hardware failure.', causes: ['Component failure', 'Surge'], symptoms: ['No operation', 'E025'], solution: 'Service required.', steps: ['Document', 'Contact service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-200,000' },
  { code: 'E026', name: 'EEPROM Fault', brand: 'GoodWe', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal memory error.', causes: ['Component fault'], symptoms: ['Settings lost', 'E026'], solution: 'Firmware reload or service.', steps: ['Update firmware', 'Contact service'], prevention: ['Proper shutdown'], tools: ['USB'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-50,000' },

  // Battery Faults (ES/EM/ET/BT Series)
  { code: 'E030', name: 'Battery Over Voltage', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'High', category: 'Battery', description: 'Battery voltage exceeds maximum.', causes: ['Wrong charge settings', 'BMS fault'], symptoms: ['Charging stops', 'E030'], solution: 'Correct settings.', steps: ['Check voltage', 'Adjust settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'E031', name: 'Battery Under Voltage', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'High', category: 'Battery', description: 'Battery voltage too low.', causes: ['Overdischarge', 'Battery fault'], symptoms: ['System offline', 'E031'], solution: 'Recharge battery.', steps: ['Charge', 'Adjust DOD'], prevention: ['Proper DOD settings'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'E032', name: 'Battery Over Temperature', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'High', category: 'Battery', description: 'Battery too hot.', causes: ['Poor ventilation', 'High current'], symptoms: ['Current limited', 'E032'], solution: 'Improve cooling.', steps: ['Check temperature', 'Improve ventilation'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'E033', name: 'Battery Low Temperature', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'Medium', category: 'Battery', description: 'Battery too cold for charging.', causes: ['Cold environment'], symptoms: ['Charging suspended', 'E033'], solution: 'Allow warming.', steps: ['Wait', 'Add insulation'], prevention: ['Insulated location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'E034', name: 'BMS Communication Error', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'Medium', category: 'Battery', description: 'Cannot communicate with BMS.', causes: ['Cable fault', 'BMS offline'], symptoms: ['Battery offline', 'E034'], solution: 'Restore communication.', steps: ['Check cables', 'Restart BMS'], prevention: ['Secure connections'], tools: ['Communication cable'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'E035', name: 'Battery Not Detected', brand: 'GoodWe', model: 'ES/EM/ET/BT', severity: 'Medium', category: 'Battery', description: 'No battery detected.', causes: ['Disconnected', 'Fuse blown'], symptoms: ['No battery function', 'E035'], solution: 'Check battery connection.', steps: ['Verify connection', 'Check fuses'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-10,000' },

  // Protection Faults
  { code: 'E040', name: 'Ground Fault', brand: 'GoodWe', model: 'All Models', severity: 'Critical', category: 'Protection', description: 'Excessive ground current detected.', causes: ['Insulation fault', 'Equipment fault'], symptoms: ['Shutdown', 'E040'], solution: 'Find and clear fault.', steps: ['Test insulation', 'Find fault'], prevention: ['Regular testing'], tools: ['Megger'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-60,000' },
  { code: 'E041', name: 'Leakage Current High', brand: 'GoodWe', model: 'All Models', severity: 'High', category: 'Protection', description: 'DC leakage current exceeds limit.', causes: ['Insulation degradation', 'Moisture'], symptoms: ['Limited operation', 'E041'], solution: 'Find leakage source.', steps: ['Test insulation', 'Check for moisture'], prevention: ['Quality installation'], tools: ['Leakage clamp'], estimatedTime: '2-6 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E042', name: 'Arc Fault', brand: 'GoodWe', model: 'AFCI Models', severity: 'Critical', category: 'Protection', description: 'DC arc detected.', causes: ['Loose connection', 'Cable damage'], symptoms: ['Immediate stop', 'E042'], solution: 'Inspect all DC connections.', steps: ['Do not restart', 'Inspect all connections'], prevention: ['Quality connections'], tools: ['Thermal camera'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-65,000' },
  { code: 'E043', name: 'SPD Fault', brand: 'GoodWe', model: 'All Models', severity: 'Medium', category: 'Protection', description: 'Surge protection device activated.', causes: ['Lightning', 'Surge'], symptoms: ['Shutdown', 'E043'], solution: 'Check SPD, replace if needed.', steps: ['Check SPD indicator', 'Replace if tripped'], prevention: ['Quality SPDs'], tools: ['Visual'], estimatedTime: '1-2 hours', estimatedCost: 'KES 5,000-20,000' },

  // Communication
  { code: 'E050', name: 'WiFi Error', brand: 'GoodWe', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi module offline.', causes: ['Signal weak', 'Module fault'], symptoms: ['No monitoring', 'E050'], solution: 'Check WiFi.', steps: ['Check signal', 'Reconnect'], prevention: ['Good WiFi'], tools: ['Phone'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-5,000' },
  { code: 'E051', name: 'SEMS Connection Lost', brand: 'GoodWe', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Cannot connect to SEMS portal.', causes: ['Internet down', 'Server issue'], symptoms: ['No cloud data', 'E051'], solution: 'Check internet.', steps: ['Verify connection'], prevention: ['Reliable internet'], tools: ['Network tools'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'E052', name: 'Meter Communication Lost', brand: 'GoodWe', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Smart meter offline.', causes: ['CT disconnected', 'Meter fault'], symptoms: ['No power flow data', 'E052'], solution: 'Check meter.', steps: ['Check CT', 'Check wiring'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SUNGROW INVERTER FAULT CODES (45+ Codes)
// Models: SG, SH, SC Series
// ═══════════════════════════════════════════════════════════════════════════════

export const SUNGROW_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'F001', name: 'Grid Over Voltage', brand: 'Sungrow', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage too high.', causes: ['Utility high', 'Grid impedance'], symptoms: ['No export', 'F001'], solution: 'Check grid.', steps: ['Measure voltage', 'Report to utility'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'F002', name: 'Grid Under Voltage', brand: 'Sungrow', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage too low.', causes: ['Utility low', 'Cable issues'], symptoms: ['No export', 'F002'], solution: 'Improve voltage.', steps: ['Check cables', 'Report to utility'], prevention: ['Proper cables'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F003', name: 'Grid Frequency Fault', brand: 'Sungrow', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency outside limits.', causes: ['Grid instability'], symptoms: ['Disconnection', 'F003'], solution: 'Wait for stability.', steps: ['Monitor'], prevention: ['Grid monitoring'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'F004', name: 'No Grid', brand: 'Sungrow', model: 'All Models', severity: 'Low', category: 'Grid', description: 'No grid detected.', causes: ['Outage', 'Breaker off'], symptoms: ['Standby', 'F004'], solution: 'Restore grid.', steps: ['Check utility', 'Check breakers'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'F005', name: 'Grid Relay Fault', brand: 'Sungrow', model: 'All Grid-Tie', severity: 'Critical', category: 'Hardware', description: 'Relay test failed.', causes: ['Relay wear'], symptoms: ['Cannot connect', 'F005'], solution: 'Service needed.', steps: ['Contact service'], prevention: ['Regular service'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },

  // PV Faults
  { code: 'F010', name: 'PV Over Voltage', brand: 'Sungrow', model: 'All Models', severity: 'Critical', category: 'PV', description: 'DC voltage too high.', causes: ['String too long', 'Cold weather'], symptoms: ['Won\'t start', 'F010'], solution: 'Reduce string.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F011', name: 'PV Insulation Fault', brand: 'Sungrow', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault detected.', causes: ['Cable damage', 'Moisture'], symptoms: ['Won\'t operate', 'F011'], solution: 'Find and repair.', steps: ['Test insulation', 'Locate fault'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F012', name: 'PV Connection Fault', brand: 'Sungrow', model: 'All Models', severity: 'Medium', category: 'PV', description: 'String connection problem.', causes: ['Loose connector'], symptoms: ['String offline', 'F012'], solution: 'Check connections.', steps: ['Inspect MC4s'], prevention: ['Quality connectors'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'F013', name: 'PV Reverse Connection', brand: 'Sungrow', model: 'All Models', severity: 'High', category: 'PV', description: 'Polarity reversed.', causes: ['Installation error'], symptoms: ['No start', 'F013'], solution: 'Correct polarity.', steps: ['Check polarity', 'Correct'], prevention: ['Careful installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F014', name: 'String Current Abnormal', brand: 'Sungrow', model: 'Multi-String', severity: 'Medium', category: 'PV', description: 'Current imbalance between strings.', causes: ['Shading', 'Panel fault'], symptoms: ['Reduced output', 'F014'], solution: 'Check strings.', steps: ['Measure currents', 'Check for shading'], prevention: ['Matched strings'], tools: ['Clamp meter'], estimatedTime: '2-4 hours', estimatedCost: 'KES 5,000-30,000' },

  // Inverter Faults
  { code: 'F020', name: 'Over Temperature', brand: 'Sungrow', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal temperature high.', causes: ['Poor ventilation'], symptoms: ['Derating', 'F020'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Add shading'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'F021', name: 'Fan Fault', brand: 'Sungrow', model: 'Models with fan', severity: 'Medium', category: 'Hardware', description: 'Fan malfunction.', causes: ['Motor failure'], symptoms: ['Overheating', 'F021'], solution: 'Replace fan.', steps: ['Check fan', 'Replace'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: 'F022', name: 'DC Bus Fault', brand: 'Sungrow', model: 'All Models', severity: 'High', category: 'Hardware', description: 'DC bus voltage abnormal.', causes: ['Surge', 'Component fault'], symptoms: ['Shutdown', 'F022'], solution: 'Check and restart.', steps: ['Power cycle', 'If persists, service'], prevention: ['Surge protection'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-100,000' },
  { code: 'F023', name: 'Hardware Error', brand: 'Sungrow', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal hardware failure.', causes: ['Component failure'], symptoms: ['No operation', 'F023'], solution: 'Service required.', steps: ['Contact service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-200,000' },

  // Battery Faults (SH Series)
  { code: 'F030', name: 'Battery Over Voltage', brand: 'Sungrow', model: 'SH Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage too high.', causes: ['Wrong settings'], symptoms: ['Charging stops', 'F030'], solution: 'Correct settings.', steps: ['Check settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F031', name: 'Battery Under Voltage', brand: 'Sungrow', model: 'SH Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage too low.', causes: ['Overdischarge'], symptoms: ['System offline', 'F031'], solution: 'Recharge.', steps: ['Charge battery'], prevention: ['Proper DOD'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'F032', name: 'Battery Temperature Fault', brand: 'Sungrow', model: 'SH Hybrid', severity: 'High', category: 'Battery', description: 'Battery temperature abnormal.', causes: ['Hot or cold environment'], symptoms: ['Current limited', 'F032'], solution: 'Adjust environment.', steps: ['Check temperature'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'F033', name: 'BMS Communication Fault', brand: 'Sungrow', model: 'SH Hybrid', severity: 'Medium', category: 'Battery', description: 'Lost BMS communication.', causes: ['Cable fault'], symptoms: ['Battery offline', 'F033'], solution: 'Check cables.', steps: ['Check connections'], prevention: ['Secure installation'], tools: ['Communication cable'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },

  // Protection Faults
  { code: 'F040', name: 'Ground Fault', brand: 'Sungrow', model: 'All Models', severity: 'Critical', category: 'Protection', description: 'Ground fault detected.', causes: ['Insulation fault'], symptoms: ['Shutdown', 'F040'], solution: 'Find and repair.', steps: ['Test insulation'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-60,000' },
  { code: 'F041', name: 'AFCI Fault', brand: 'Sungrow', model: 'AFCI Models', severity: 'Critical', category: 'Protection', description: 'Arc fault detected.', causes: ['Loose connection'], symptoms: ['Immediate stop', 'F041'], solution: 'Inspect connections.', steps: ['Inspect all DC connections'], prevention: ['Quality installation'], tools: ['Thermal camera'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-65,000' },

  // Communication
  { code: 'F050', name: 'Communication Fault', brand: 'Sungrow', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Communication error.', causes: ['Cable fault', 'Network issue'], symptoms: ['No monitoring', 'F050'], solution: 'Check connections.', steps: ['Verify cables'], prevention: ['Secure installation'], tools: ['Network tools'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'F051', name: 'Meter Fault', brand: 'Sungrow', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Smart meter offline.', causes: ['CT disconnected'], symptoms: ['No power flow', 'F051'], solution: 'Check meter.', steps: ['Check CT'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SOLAREDGE INVERTER FAULT CODES (40+ Codes)
// Models: SE Series Single/Three Phase, StorEdge
// ═══════════════════════════════════════════════════════════════════════════════

export const SOLAREDGE_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'Grid Frequency High', name: 'Grid Frequency High', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency above limit.', causes: ['Grid instability'], symptoms: ['Disconnection'], solution: 'Wait for stability.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'Grid Frequency Low', name: 'Grid Frequency Low', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency below limit.', causes: ['Grid overload'], symptoms: ['Disconnection'], solution: 'Wait for recovery.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'Grid Voltage High', name: 'Grid Voltage High', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Grid', description: 'AC voltage above limit.', causes: ['Utility high'], symptoms: ['No export'], solution: 'Check grid.', steps: ['Measure voltage'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Grid Voltage Low', name: 'Grid Voltage Low', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Grid', description: 'AC voltage below limit.', causes: ['Utility low'], symptoms: ['No export'], solution: 'Improve voltage.', steps: ['Check cables'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Grid Shutdown', name: 'Grid Shutdown', brand: 'SolarEdge', model: 'All Models', severity: 'Low', category: 'Grid', description: 'Grid disconnected.', causes: ['Outage', 'Breaker'], symptoms: ['Standby'], solution: 'Restore grid.', steps: ['Check utility'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'AC Freq Trip', name: 'AC Frequency Trip', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency protection tripped.', causes: ['Frequency excursion'], symptoms: ['Disconnection'], solution: 'Verify grid.', steps: ['Monitor frequency'], prevention: ['Grid monitoring'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },

  // DC/Optimizer Faults
  { code: 'P(max) Exceeded', name: 'Power Optimizer Pmax Exceeded', brand: 'SolarEdge', model: 'All Models', severity: 'Medium', category: 'PV', description: 'Optimizer output exceeds maximum.', causes: ['Configuration error'], symptoms: ['Optimizer limited'], solution: 'Check pairing.', steps: ['Verify panel-optimizer match'], prevention: ['Correct pairing'], tools: ['SetApp'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Optimizer Comm', name: 'Optimizer Communication Error', brand: 'SolarEdge', model: 'All Models', severity: 'Medium', category: 'PV', description: 'Cannot communicate with optimizer(s).', causes: ['Optimizer fault', 'Wiring issue'], symptoms: ['Some panels not reporting'], solution: 'Check string wiring.', steps: ['Check connections', 'Replace faulty optimizers'], prevention: ['Quality installation'], tools: ['SetApp'], estimatedTime: '2-6 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'V(in) High', name: 'DC Input Voltage High', brand: 'SolarEdge', model: 'All Models', severity: 'Critical', category: 'PV', description: 'String voltage too high.', causes: ['Too many optimizers'], symptoms: ['Won\'t operate'], solution: 'Reduce string length.', steps: ['Count optimizers', 'Reconfigure'], prevention: ['Proper design'], tools: ['SetApp'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'V(in) Low', name: 'DC Input Voltage Low', brand: 'SolarEdge', model: 'All Models', severity: 'Low', category: 'PV', description: 'String voltage below start threshold.', causes: ['Low irradiance', 'Short string'], symptoms: ['Not starting'], solution: 'Wait or add panels.', steps: ['Check irradiance'], prevention: ['Proper sizing'], tools: ['SetApp'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Insulation Fault', name: 'Insulation Fault', brand: 'SolarEdge', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault detected.', causes: ['Cable damage', 'Moisture'], symptoms: ['Won\'t operate'], solution: 'Find and repair.', steps: ['Test insulation'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Module Performance', name: 'Module Performance Low', brand: 'SolarEdge', model: 'All Models', severity: 'Medium', category: 'PV', description: 'Panel underperforming.', causes: ['Shading', 'Soiling', 'Degradation'], symptoms: ['Panel flagged in monitoring'], solution: 'Inspect panel.', steps: ['Check for shading', 'Clean panel', 'Test'], prevention: ['Regular maintenance'], tools: ['Thermal camera'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },

  // Inverter Faults
  { code: 'Over Temp', name: 'Inverter Over Temperature', brand: 'SolarEdge', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal temperature high.', causes: ['Poor ventilation'], symptoms: ['Derating'], solution: 'Improve cooling.', steps: ['Check location', 'Add ventilation'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'HW Fault', name: 'Hardware Fault', brand: 'SolarEdge', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal hardware failure.', causes: ['Component failure'], symptoms: ['No operation'], solution: 'Service required.', steps: ['Contact SolarEdge'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 75,000-200,000' },
  { code: 'Firmware Fault', name: 'Firmware Fault', brand: 'SolarEdge', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Firmware error.', causes: ['Corruption'], symptoms: ['Erratic behavior'], solution: 'Update firmware.', steps: ['Download update', 'Apply via SetApp'], prevention: ['Keep updated'], tools: ['SetApp'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0' },
  { code: 'DC Injection', name: 'DC Injection High', brand: 'SolarEdge', model: 'All Grid-Tie', severity: 'High', category: 'Hardware', description: 'Excessive DC in AC output.', causes: ['Internal fault'], symptoms: ['Shutdown'], solution: 'Service required.', steps: ['Contact service'], prevention: ['None'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },
  { code: 'Arc Fault', name: 'Arc Fault Detected', brand: 'SolarEdge', model: 'HD Wave', severity: 'Critical', category: 'Protection', description: 'DC arc detected.', causes: ['Loose connection'], symptoms: ['Immediate shutdown'], solution: 'Inspect all connections.', steps: ['DO NOT restart', 'Check all connections'], prevention: ['Quality installation'], tools: ['Visual inspection'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-65,000' },

  // StorEdge Battery Faults
  { code: 'Battery Comm', name: 'Battery Communication Error', brand: 'SolarEdge', model: 'StorEdge', severity: 'Medium', category: 'Battery', description: 'Lost battery communication.', causes: ['Cable fault'], symptoms: ['Battery offline'], solution: 'Check cables.', steps: ['Verify connections'], prevention: ['Secure installation'], tools: ['None'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Battery SOC Low', name: 'Battery State of Charge Low', brand: 'SolarEdge', model: 'StorEdge', severity: 'High', category: 'Battery', description: 'Battery deeply discharged.', causes: ['Overdischarge'], symptoms: ['System offline'], solution: 'Recharge.', steps: ['Allow charging'], prevention: ['Proper DOD'], tools: ['Monitoring'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0' },
  { code: 'Battery Temp', name: 'Battery Temperature Fault', brand: 'SolarEdge', model: 'StorEdge', severity: 'High', category: 'Battery', description: 'Battery temperature abnormal.', causes: ['Hot/cold environment'], symptoms: ['Operation limited'], solution: 'Adjust environment.', steps: ['Check temperature'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },

  // Communication
  { code: 'SetApp Conn', name: 'SetApp Connection Error', brand: 'SolarEdge', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Cannot connect via SetApp.', causes: ['WiFi issue', 'App issue'], symptoms: ['No local access'], solution: 'Check connection.', steps: ['Verify WiFi', 'Restart app'], prevention: ['Good signal'], tools: ['Phone'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'Cloud Conn', name: 'Cloud Connection Lost', brand: 'SolarEdge', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Lost connection to monitoring portal.', causes: ['Internet down'], symptoms: ['No portal data'], solution: 'Check internet.', steps: ['Verify connection'], prevention: ['Reliable internet'], tools: ['Network tools'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ENPHASE MICROINVERTER FAULT CODES (35+ Codes)
// Models: IQ7, IQ7+, IQ7X, IQ8 Series
// ═══════════════════════════════════════════════════════════════════════════════

export const ENPHASE_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'Grid Profile', name: 'Grid Profile Error', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'Grid', description: 'Grid profile not set or incorrect.', causes: ['Not configured', 'Wrong profile'], symptoms: ['Not producing'], solution: 'Set correct profile.', steps: ['Use Enphase app', 'Select correct profile'], prevention: ['Proper commissioning'], tools: ['Envoy', 'Installer Toolkit'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0' },
  { code: 'Grid Voltage High', name: 'Grid Voltage High', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'Grid', description: 'AC voltage above limit.', causes: ['Utility high'], symptoms: ['Units offline'], solution: 'Check grid.', steps: ['Measure voltage'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Grid Voltage Low', name: 'Grid Voltage Low', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'Grid', description: 'AC voltage below limit.', causes: ['Utility low'], symptoms: ['Units offline'], solution: 'Improve voltage.', steps: ['Check cables'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Grid Freq Error', name: 'Grid Frequency Error', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'Grid', description: 'Frequency outside limits.', causes: ['Grid instability'], symptoms: ['Disconnection'], solution: 'Wait for stability.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'No Grid', name: 'No Grid Detected', brand: 'Enphase', model: 'All IQ', severity: 'Low', category: 'Grid', description: 'No AC present.', causes: ['Outage', 'Breaker'], symptoms: ['All units offline'], solution: 'Restore grid.', steps: ['Check utility'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },

  // DC/Panel Faults
  { code: 'DC Low', name: 'DC Voltage Low', brand: 'Enphase', model: 'All IQ', severity: 'Low', category: 'PV', description: 'Panel voltage below start threshold.', causes: ['Low irradiance', 'Panel issue'], symptoms: ['Unit not starting'], solution: 'Wait for sun or check panel.', steps: ['Check irradiance', 'Check panel connections'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'DC High', name: 'DC Voltage High', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'PV', description: 'Panel voltage exceeds maximum.', causes: ['Panel mismatch', 'Wiring error'], symptoms: ['Unit not operating'], solution: 'Verify panel compatibility.', steps: ['Check panel specs', 'Verify wiring'], prevention: ['Compatible panels'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'GFDI', name: 'Ground Fault', brand: 'Enphase', model: 'All IQ', severity: 'Critical', category: 'PV', description: 'Ground fault detected.', causes: ['Insulation fault'], symptoms: ['System offline'], solution: 'Find and repair.', steps: ['Check branch circuits', 'Find fault'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },

  // Microinverter Hardware Faults
  { code: 'Comm Fault', name: 'Communication Fault', brand: 'Enphase', model: 'All IQ', severity: 'Medium', category: 'Communication', description: 'Unit not communicating with Envoy.', causes: ['Signal issue', 'Unit fault'], symptoms: ['Unit grey in app'], solution: 'Check power line communication.', steps: ['Verify branch circuit', 'Check distance to Envoy'], prevention: ['Proper installation'], tools: ['Installer Toolkit'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-30,000' },
  { code: 'Not Reporting', name: 'Unit Not Reporting', brand: 'Enphase', model: 'All IQ', severity: 'Medium', category: 'Communication', description: 'No data from unit.', causes: ['PLC issue', 'Unit offline'], symptoms: ['No production data'], solution: 'Check unit status.', steps: ['Power cycle', 'Check connections'], prevention: ['Good PLC signal'], tools: ['Installer Toolkit'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Over Temp', name: 'Microinverter Over Temperature', brand: 'Enphase', model: 'All IQ', severity: 'Medium', category: 'Thermal', description: 'Unit overheating.', causes: ['Hot roof', 'No airflow'], symptoms: ['Derating'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Consider relocation'], prevention: ['Adequate clearance'], tools: ['Temperature meter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'Hardware Fault', name: 'Microinverter Hardware Fault', brand: 'Enphase', model: 'All IQ', severity: 'Critical', category: 'Hardware', description: 'Internal failure.', causes: ['Component failure'], symptoms: ['Unit offline'], solution: 'Replace unit.', steps: ['Identify unit', 'Replace'], prevention: ['Quality installation'], tools: ['Replacement unit'], estimatedTime: '2-4 hours', estimatedCost: 'KES 15,000-35,000' },
  { code: 'Unit Offline', name: 'Unit Completely Offline', brand: 'Enphase', model: 'All IQ', severity: 'High', category: 'Hardware', description: 'Unit not responding at all.', causes: ['Unit failure', 'No DC input'], symptoms: ['Red in app'], solution: 'Diagnose and replace if needed.', steps: ['Check DC input', 'Check connections', 'Replace if faulty'], prevention: ['Quality installation'], tools: ['Multimeter', 'Replacement unit'], estimatedTime: '2-4 hours', estimatedCost: 'KES 15,000-35,000' },

  // Envoy Faults
  { code: 'Envoy Offline', name: 'Envoy Not Reporting', brand: 'Enphase', model: 'Envoy', severity: 'Medium', category: 'Communication', description: 'Envoy not sending data to cloud.', causes: ['Internet down', 'Envoy fault'], symptoms: ['No cloud data'], solution: 'Check Envoy status.', steps: ['Check internet', 'Check Envoy LEDs', 'Restart'], prevention: ['Reliable internet'], tools: ['Network tools'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'CT Error', name: 'Production CT Error', brand: 'Enphase', model: 'Envoy', severity: 'Low', category: 'Communication', description: 'Current transformer reading error.', causes: ['CT not installed', 'CT reversed'], symptoms: ['Wrong power reading'], solution: 'Check CT installation.', steps: ['Verify CT placement', 'Check direction'], prevention: ['Proper installation'], tools: ['Clamp meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'Meter Comm', name: 'Consumption Meter Error', brand: 'Enphase', model: 'Envoy', severity: 'Low', category: 'Communication', description: 'Consumption monitoring error.', causes: ['CT fault', 'Setup error'], symptoms: ['No consumption data'], solution: 'Check CTs.', steps: ['Verify CT setup'], prevention: ['Proper installation'], tools: ['Installer Toolkit'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },

  // IQ Battery Faults
  { code: 'Battery Comm', name: 'IQ Battery Communication Error', brand: 'Enphase', model: 'IQ Battery', severity: 'Medium', category: 'Battery', description: 'Lost communication with battery.', causes: ['Cable fault'], symptoms: ['Battery offline'], solution: 'Check connections.', steps: ['Verify cables'], prevention: ['Secure installation'], tools: ['None'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Battery SOC', name: 'Battery SOC Low', brand: 'Enphase', model: 'IQ Battery', severity: 'High', category: 'Battery', description: 'Battery discharged deeply.', causes: ['Overdischarge'], symptoms: ['No backup'], solution: 'Allow charging.', steps: ['Wait for charge'], prevention: ['Proper settings'], tools: ['App'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0' },
  { code: 'Battery Temp', name: 'Battery Temperature Fault', brand: 'Enphase', model: 'IQ Battery', severity: 'High', category: 'Battery', description: 'Battery temperature abnormal.', causes: ['Environment'], symptoms: ['Limited operation'], solution: 'Adjust environment.', steps: ['Check temperature'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SOFAR INVERTER FAULT CODES (35+ Codes)
// Models: ME, HYD, SOFAR Series
// ═══════════════════════════════════════════════════════════════════════════════

export const SOFAR_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'E01', name: 'Grid Over Voltage', brand: 'Sofar', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage too high.', causes: ['Utility high'], symptoms: ['No export', 'E01'], solution: 'Check grid.', steps: ['Measure voltage'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'E02', name: 'Grid Under Voltage', brand: 'Sofar', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage too low.', causes: ['Utility low'], symptoms: ['No export', 'E02'], solution: 'Improve voltage.', steps: ['Check cables'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'E03', name: 'Grid Frequency Fault', brand: 'Sofar', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency abnormal.', causes: ['Grid instability'], symptoms: ['Disconnection', 'E03'], solution: 'Wait for stability.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'E04', name: 'No Grid', brand: 'Sofar', model: 'All Models', severity: 'Low', category: 'Grid', description: 'Grid not detected.', causes: ['Outage'], symptoms: ['Standby', 'E04'], solution: 'Restore grid.', steps: ['Check utility'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'E05', name: 'Grid Relay Fault', brand: 'Sofar', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Relay test failed.', causes: ['Relay wear'], symptoms: ['Cannot connect', 'E05'], solution: 'Service needed.', steps: ['Contact service'], prevention: ['Regular service'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },

  // PV Faults
  { code: 'E10', name: 'PV Over Voltage', brand: 'Sofar', model: 'All Models', severity: 'Critical', category: 'PV', description: 'DC voltage too high.', causes: ['String too long'], symptoms: ['Won\'t start', 'E10'], solution: 'Reduce string.', steps: ['Measure Voc'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E11', name: 'PV Insulation Fault', brand: 'Sofar', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault.', causes: ['Cable damage'], symptoms: ['Won\'t operate', 'E11'], solution: 'Find and repair.', steps: ['Test insulation'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E12', name: 'PV Connection Fault', brand: 'Sofar', model: 'All Models', severity: 'Medium', category: 'PV', description: 'String connection issue.', causes: ['Loose connector'], symptoms: ['String offline', 'E12'], solution: 'Check connections.', steps: ['Inspect MC4s'], prevention: ['Quality connectors'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },

  // Inverter Faults
  { code: 'E20', name: 'Over Temperature', brand: 'Sofar', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Temperature high.', causes: ['Poor ventilation'], symptoms: ['Derating', 'E20'], solution: 'Improve cooling.', steps: ['Check ventilation'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'E21', name: 'Fan Fault', brand: 'Sofar', model: 'With fan', severity: 'Medium', category: 'Hardware', description: 'Fan malfunction.', causes: ['Motor failure'], symptoms: ['Overheating', 'E21'], solution: 'Replace fan.', steps: ['Check fan'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: 'E22', name: 'Hardware Fault', brand: 'Sofar', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal failure.', causes: ['Component failure'], symptoms: ['No operation', 'E22'], solution: 'Service required.', steps: ['Contact service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-200,000' },

  // Battery Faults (HYD Series)
  { code: 'E30', name: 'Battery Over Voltage', brand: 'Sofar', model: 'HYD Series', severity: 'High', category: 'Battery', description: 'Battery voltage high.', causes: ['Wrong settings'], symptoms: ['Charging stops', 'E30'], solution: 'Correct settings.', steps: ['Check settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'E31', name: 'Battery Under Voltage', brand: 'Sofar', model: 'HYD Series', severity: 'High', category: 'Battery', description: 'Battery voltage low.', causes: ['Overdischarge'], symptoms: ['System offline', 'E31'], solution: 'Recharge.', steps: ['Charge battery'], prevention: ['Proper DOD'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'E32', name: 'BMS Communication Error', brand: 'Sofar', model: 'HYD Series', severity: 'Medium', category: 'Battery', description: 'Lost BMS communication.', causes: ['Cable fault'], symptoms: ['Battery offline', 'E32'], solution: 'Check cables.', steps: ['Check connections'], prevention: ['Secure installation'], tools: ['Communication cable'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },

  // Communication
  { code: 'E40', name: 'WiFi Error', brand: 'Sofar', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi module offline.', causes: ['Signal weak'], symptoms: ['No monitoring', 'E40'], solution: 'Check WiFi.', steps: ['Check signal'], prevention: ['Good WiFi'], tools: ['Phone'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-5,000' },
  { code: 'E41', name: 'Meter Error', brand: 'Sofar', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Smart meter offline.', causes: ['CT disconnected'], symptoms: ['No power flow', 'E41'], solution: 'Check meter.', steps: ['Check CT'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SOLIS INVERTER FAULT CODES (35+ Codes)
// Models: SOLIS, S5, S6 Series
// ═══════════════════════════════════════════════════════════════════════════════

export const SOLIS_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'F01', name: 'Grid Over Voltage', brand: 'Solis', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage high.', causes: ['Utility high'], symptoms: ['No export'], solution: 'Check grid.', steps: ['Measure voltage'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'F02', name: 'Grid Under Voltage', brand: 'Solis', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage low.', causes: ['Utility low'], symptoms: ['No export'], solution: 'Improve voltage.', steps: ['Check cables'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F03', name: 'Grid Frequency High', brand: 'Solis', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency high.', causes: ['Grid instability'], symptoms: ['Disconnection'], solution: 'Wait.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'F04', name: 'Grid Frequency Low', brand: 'Solis', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency low.', causes: ['Grid overload'], symptoms: ['Disconnection'], solution: 'Wait.', steps: ['Monitor'], prevention: ['None'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: 'F05', name: 'No Grid', brand: 'Solis', model: 'All Models', severity: 'Low', category: 'Grid', description: 'No grid detected.', causes: ['Outage'], symptoms: ['Standby'], solution: 'Restore grid.', steps: ['Check utility'], prevention: ['Normal'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: 'F06', name: 'Island Detected', brand: 'Solis', model: 'All Models', severity: 'Critical', category: 'Grid', description: 'Islanding detected.', causes: ['Grid disconnection'], symptoms: ['Immediate stop'], solution: 'Verify grid.', steps: ['Check grid'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'F07', name: 'Grid Relay Fault', brand: 'Solis', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Relay test failed.', causes: ['Relay wear'], symptoms: ['Cannot connect'], solution: 'Service needed.', steps: ['Contact service'], prevention: ['Regular service'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },

  // PV Faults
  { code: 'F10', name: 'PV Over Voltage', brand: 'Solis', model: 'All Models', severity: 'Critical', category: 'PV', description: 'DC voltage high.', causes: ['String too long'], symptoms: ['Won\'t start'], solution: 'Reduce string.', steps: ['Measure Voc'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F11', name: 'PV Insulation Low', brand: 'Solis', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault.', causes: ['Cable damage'], symptoms: ['Won\'t operate'], solution: 'Find and repair.', steps: ['Test insulation'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F12', name: 'PV Connection Fault', brand: 'Solis', model: 'All Models', severity: 'Medium', category: 'PV', description: 'Connection issue.', causes: ['Loose connector'], symptoms: ['String offline'], solution: 'Check connections.', steps: ['Inspect MC4s'], prevention: ['Quality connectors'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },

  // Inverter Faults
  { code: 'F20', name: 'Over Temperature', brand: 'Solis', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Temperature high.', causes: ['Poor ventilation'], symptoms: ['Derating'], solution: 'Improve cooling.', steps: ['Check ventilation'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'F21', name: 'Fan Fault', brand: 'Solis', model: 'With fan', severity: 'Medium', category: 'Hardware', description: 'Fan malfunction.', causes: ['Motor failure'], symptoms: ['Overheating'], solution: 'Replace fan.', steps: ['Check fan'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: 'F22', name: 'Hardware Fault', brand: 'Solis', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal failure.', causes: ['Component failure'], symptoms: ['No operation'], solution: 'Service required.', steps: ['Contact service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-200,000' },

  // Battery Faults (Hybrid Models)
  { code: 'F30', name: 'Battery Over Voltage', brand: 'Solis', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage high.', causes: ['Wrong settings'], symptoms: ['Charging stops'], solution: 'Correct settings.', steps: ['Check settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F31', name: 'Battery Under Voltage', brand: 'Solis', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage low.', causes: ['Overdischarge'], symptoms: ['System offline'], solution: 'Recharge.', steps: ['Charge battery'], prevention: ['Proper DOD'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'F32', name: 'BMS Communication Error', brand: 'Solis', model: 'Hybrid', severity: 'Medium', category: 'Battery', description: 'Lost BMS communication.', causes: ['Cable fault'], symptoms: ['Battery offline'], solution: 'Check cables.', steps: ['Check connections'], prevention: ['Secure installation'], tools: ['Communication cable'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },

  // Communication
  { code: 'F40', name: 'WiFi Error', brand: 'Solis', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi module offline.', causes: ['Signal weak'], symptoms: ['No monitoring'], solution: 'Check WiFi.', steps: ['Check signal'], prevention: ['Good WiFi'], tools: ['Phone'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-5,000' },
  { code: 'F41', name: 'Meter Error', brand: 'Solis', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Smart meter offline.', causes: ['CT disconnected'], symptoms: ['No power flow'], solution: 'Check meter.', steps: ['Check CT'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// Export combined array
export const INVERTER_FAULTS_PART2: InverterFault[] = [
  ...GOODWE_FAULTS,
  ...SUNGROW_FAULTS,
  ...SOLAREDGE_FAULTS,
  ...ENPHASE_FAULTS,
  ...SOFAR_FAULTS,
  ...SOLIS_FAULTS,
];

export const BRANDS_PART2 = ['GoodWe', 'Sungrow', 'SolarEdge', 'Enphase', 'Sofar', 'Solis'];

export const FAULT_COUNT_PART2 = INVERTER_FAULTS_PART2.length;
