/**
 * WORLD'S MOST COMPREHENSIVE SOLAR INVERTER FAULT DATABASE - PART 1
 * Covers: Growatt, Deye, Victron, Huawei, SMA, Fronius
 * 200+ Fault codes with detailed diagnostics
 */

export interface InverterFault {
  code: string;
  name: string;
  brand: string;
  model?: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low' | 'Warning';
  category: string;
  description: string;
  causes: string[];
  symptoms: string[];
  solution: string;
  steps: string[];
  prevention: string[];
  tools: string[];
  estimatedTime: string;
  estimatedCost: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// GROWATT INVERTER FAULT CODES - Complete Database (50+ Codes)
// Models: MIN, MIC, MOD, MAC, SPF, SPH, SPA, MAX, MID Series
// ═══════════════════════════════════════════════════════════════════════════════

export const GROWATT_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'Error 100', name: 'Grid Over Voltage (Phase A)', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Grid', description: 'Phase A grid voltage exceeded maximum limit (typically >270V). Inverter disconnects to protect equipment.', causes: ['Utility voltage high', 'Transformer tap wrong', 'Light loading on grid', 'Voltage sensing fault'], symptoms: ['No export', 'Error 100 displayed', 'Phase A voltage reading high'], solution: 'Check actual grid voltage, report to utility if high, or adjust inverter settings.', steps: ['Measure Phase A voltage', 'Compare to inverter reading', 'If utility high, report', 'If settings issue, adjust limits'], prevention: ['Monitor grid voltage', 'Proper site assessment'], tools: ['Multimeter', 'Voltage recorder'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Error 101', name: 'Grid Over Voltage (Phase B)', brand: 'Growatt', model: 'Three Phase', severity: 'High', category: 'Grid', description: 'Phase B grid voltage exceeded maximum limit.', causes: ['Utility voltage high', 'Phase imbalance', 'Connection issue'], symptoms: ['No export', 'Error 101 displayed'], solution: 'Check Phase B voltage and connections.', steps: ['Measure Phase B voltage', 'Check connections', 'Report to utility if needed'], prevention: ['Regular monitoring'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Error 102', name: 'Grid Over Voltage (Phase C)', brand: 'Growatt', model: 'Three Phase', severity: 'High', category: 'Grid', description: 'Phase C grid voltage exceeded maximum limit.', causes: ['Utility voltage high', 'Phase imbalance'], symptoms: ['No export', 'Error 102 displayed'], solution: 'Check Phase C voltage.', steps: ['Measure Phase C voltage', 'Verify connections'], prevention: ['Monitor all phases'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Error 103', name: 'Grid Under Voltage (Phase A)', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Grid', description: 'Phase A voltage dropped below minimum (typically <180V).', causes: ['Utility voltage low', 'Heavy loads', 'Cable voltage drop', 'Loose connection'], symptoms: ['No export', 'Dim lights', 'Error 103'], solution: 'Improve voltage or adjust settings.', steps: ['Measure voltage at inverter and main panel', 'Check for voltage drop', 'Tighten connections', 'Report to utility'], prevention: ['Proper cable sizing', 'Connection maintenance'], tools: ['Multimeter', 'Clamp meter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Error 104', name: 'Grid Under Voltage (Phase B)', brand: 'Growatt', model: 'Three Phase', severity: 'High', category: 'Grid', description: 'Phase B voltage below minimum.', causes: ['Utility low', 'Phase loss partial'], symptoms: ['Error 104', 'Reduced output'], solution: 'Check Phase B supply.', steps: ['Measure all phase voltages', 'Check for phase issues'], prevention: ['Phase monitoring'], tools: ['Three-phase meter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-20,000' },
  { code: 'Error 105', name: 'Grid Under Voltage (Phase C)', brand: 'Growatt', model: 'Three Phase', severity: 'High', category: 'Grid', description: 'Phase C voltage below minimum.', causes: ['Utility low', 'Connection issue'], symptoms: ['Error 105'], solution: 'Check Phase C.', steps: ['Verify Phase C voltage and connections'], prevention: ['Regular checks'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-20,000' },
  { code: 'Error 106', name: 'Grid Over Frequency', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency exceeded 52Hz (50Hz system) or 62Hz (60Hz system).', causes: ['Grid instability', 'Generator with poor regulation', 'Island condition'], symptoms: ['Inverter stops', 'Error 106'], solution: 'Check grid source and frequency.', steps: ['Measure frequency', 'Verify grid connection', 'Check for generator'], prevention: ['Proper grid connection'], tools: ['Frequency meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'Error 107', name: 'Grid Under Frequency', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency dropped below 47.5Hz (50Hz) or 57.5Hz (60Hz).', causes: ['Grid overloaded', 'Generator struggling', 'Utility issue'], symptoms: ['Inverter stops', 'Error 107'], solution: 'Check grid frequency source.', steps: ['Measure frequency', 'Report to utility if persistent'], prevention: ['Monitor frequency'], tools: ['Frequency meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'Error 108', name: 'Grid Impedance Too High', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Grid', description: 'Grid impedance exceeds limit, indicating weak grid connection.', causes: ['Long cable run', 'Undersized cable', 'Transformer too small', 'Multiple inverters on circuit'], symptoms: ['Error 108', 'Voltage rise when exporting'], solution: 'Improve grid connection or reduce export.', steps: ['Check cable sizing', 'Verify transformer capacity', 'Consider export limiting'], prevention: ['Proper design', 'Cable sizing'], tools: ['Impedance meter'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-100,000' },
  { code: 'Error 109', name: 'No Utility Connection', brand: 'Growatt', model: 'All Models', severity: 'Low', category: 'Grid', description: 'No grid voltage detected at AC input.', causes: ['Power outage', 'Breaker off', 'Cable disconnected'], symptoms: ['No grid indicator', 'Error 109'], solution: 'Restore grid connection.', steps: ['Check utility status', 'Verify breakers', 'Check connections'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-5,000' },
  { code: 'Error 110', name: 'Grid Relay Failure', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal grid connection relay has failed or is stuck.', causes: ['Relay wear', 'Surge damage', 'Control board fault'], symptoms: ['Cannot connect to grid', 'Error 110'], solution: 'Inverter requires service or replacement.', steps: ['Power cycle inverter', 'If persists, contact service'], prevention: ['Surge protection'], tools: ['None - requires service'], estimatedTime: 'Service required', estimatedCost: 'KES 25,000-150,000' },

  // PV/DC Faults
  { code: 'Error 200', name: 'PV1 Over Voltage', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'PV', description: 'String 1 DC voltage exceeds inverter maximum input voltage. Fire and damage risk.', causes: ['Too many panels in series', 'Cold temperature increasing Voc', 'Wrong panel specs'], symptoms: ['Inverter won\'t start', 'Error 200', 'High DC voltage reading'], solution: 'Reconfigure string to reduce voltage.', steps: ['Measure string Voc', 'Calculate cold temperature Voc', 'Reduce panels per string'], prevention: ['Proper string sizing', 'Temperature calculations'], tools: ['DC multimeter 600V+', 'MC4 tools'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Error 201', name: 'PV2 Over Voltage', brand: 'Growatt', model: 'Dual MPPT', severity: 'Critical', category: 'PV', description: 'String 2 DC voltage exceeds maximum.', causes: ['Same as Error 200'], symptoms: ['Error 201', 'String 2 not operating'], solution: 'Reduce String 2 voltage.', steps: ['Measure String 2 Voc', 'Reconfigure if needed'], prevention: ['Correct sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Error 202', name: 'PV Over Voltage (Combined)', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Total PV voltage too high for inverter.', causes: ['String configuration error'], symptoms: ['No operation', 'Error 202'], solution: 'Check all string voltages.', steps: ['Measure all strings', 'Reconfigure as needed'], prevention: ['Design review'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Error 203', name: 'PV Insulation Resistance Low', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault detected - insulation resistance below safe level.', causes: ['Damaged cable', 'Water in junction box', 'Panel frame fault', 'Connector failure'], symptoms: ['Won\'t operate', 'ISO fault', 'Error 203'], solution: 'Locate and repair insulation fault.', steps: ['Test each string with megger', 'Isolate faulty section', 'Inspect and repair'], prevention: ['Quality installation', 'Cable protection'], tools: ['Insulation tester', 'MC4 tools'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Error 204', name: 'PV1 Connection Fault', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'PV', description: 'String 1 has poor or no connection detected.', causes: ['Loose MC4', 'Cable damage', 'Fuse blown', 'Connector corrosion'], symptoms: ['String 1 not producing', 'Error 204'], solution: 'Check String 1 connections.', steps: ['Inspect MC4 connectors', 'Check fuses', 'Measure continuity'], prevention: ['Quality connections', 'Regular inspection'], tools: ['Multimeter', 'MC4 tools'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'Error 205', name: 'PV2 Connection Fault', brand: 'Growatt', model: 'Dual MPPT', severity: 'Medium', category: 'PV', description: 'String 2 connection issue.', causes: ['Same as Error 204'], symptoms: ['String 2 not producing'], solution: 'Check String 2 connections.', steps: ['Inspect connections', 'Test continuity'], prevention: ['Quality installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'Error 206', name: 'PV Reverse Polarity', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'PV', description: 'DC input polarity is reversed - positive and negative swapped.', causes: ['Installation error', 'Connector mistake'], symptoms: ['No operation', 'Error 206', 'Possible damage'], solution: 'Correct polarity immediately.', steps: ['Identify reversed connection', 'Correct polarity', 'Check for damage'], prevention: ['Careful installation', 'Polarity verification'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Error 207', name: 'String Current Imbalance', brand: 'Growatt', model: 'Dual/Multi MPPT', severity: 'Medium', category: 'PV', description: 'Significant current difference between strings on same MPPT.', causes: ['Shading on one string', 'Panel mismatch', 'Connection issue', 'Panel degradation'], symptoms: ['Reduced output', 'Error 207'], solution: 'Balance strings or identify issue.', steps: ['Measure each string current', 'Check for shading', 'Verify panel specs match'], prevention: ['Matched strings', 'Shading analysis'], tools: ['Clamp meter', 'Solar analyzer'], estimatedTime: '2-4 hours', estimatedCost: 'KES 5,000-30,000' },

  // Inverter/Hardware Faults
  { code: 'Error 300', name: 'Inverter Over Temperature', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal temperature exceeds safe limit. Output will be reduced or stopped.', causes: ['Poor ventilation', 'Direct sunlight', 'High ambient', 'Blocked vents', 'Fan failure'], symptoms: ['Output derating', 'Error 300', 'Hot enclosure'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Clear vents', 'Verify fan operation', 'Add shading'], prevention: ['Proper installation location', 'Regular cleaning'], tools: ['Temperature meter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'Error 301', name: 'Ambient Temperature High', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Surrounding air temperature too high for rated operation.', causes: ['Hot location', 'Enclosed space', 'No air circulation'], symptoms: ['Derating', 'Error 301'], solution: 'Improve location cooling.', steps: ['Measure ambient temperature', 'Improve ventilation', 'Consider relocation'], prevention: ['Proper location selection'], tools: ['Thermometer'], estimatedTime: '2-8 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'Error 302', name: 'Module Temperature High', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal power module temperature excessive.', causes: ['Overload', 'Cooling failure', 'Internal fault'], symptoms: ['Shutdown', 'Error 302'], solution: 'Reduce load, improve cooling, or service.', steps: ['Check loading', 'Verify cooling system', 'Contact service if persists'], prevention: ['Proper sizing', 'Adequate cooling'], tools: ['None initial'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-75,000' },
  { code: 'Error 303', name: 'Fan Failure', brand: 'Growatt', model: 'Models with fans', severity: 'Medium', category: 'Hardware', description: 'Internal cooling fan not operating.', causes: ['Fan motor failure', 'Blocked fan', 'Driver circuit fault'], symptoms: ['Fan not running', 'Overheating', 'Error 303'], solution: 'Replace fan or clear obstruction.', steps: ['Check fan operation', 'Clear debris', 'Replace if faulty'], prevention: ['Regular cleaning', 'Inspection'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: 'Error 304', name: 'DC Bus Over Voltage', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal DC bus voltage exceeded safe limit.', causes: ['PV surge', 'Grid disconnection during export', 'Capacitor issue'], symptoms: ['Shutdown', 'Error 304'], solution: 'Check inputs and restart.', steps: ['Power cycle', 'Check PV voltage', 'If persists, contact service'], prevention: ['Surge protection'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-100,000' },
  { code: 'Error 305', name: 'DC Bus Under Voltage', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Hardware', description: 'Internal DC bus voltage too low.', causes: ['Low PV input', 'Capacitor degradation', 'Control fault'], symptoms: ['Won\'t start', 'Error 305'], solution: 'Check PV input, may need service.', steps: ['Measure PV voltage', 'Verify adequate irradiance', 'Contact service if issue'], prevention: ['Proper string sizing'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-75,000' },
  { code: 'Error 306', name: 'Inverter Hardware Fault', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal hardware failure detected.', causes: ['Component failure', 'Surge damage', 'Manufacturing defect'], symptoms: ['No operation', 'Error 306'], solution: 'Professional service or replacement required.', steps: ['Document error', 'Check warranty', 'Contact service'], prevention: ['Surge protection', 'Proper installation'], tools: ['None - service required'], estimatedTime: 'Days', estimatedCost: 'KES 50,000-250,000' },

  // Battery Faults (SPF/SPH/SPA Hybrid Models)
  { code: 'Error 400', name: 'Battery Over Voltage', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'High', category: 'Battery', description: 'Battery voltage exceeded maximum safe charging limit.', causes: ['Wrong charge settings', 'BMS fault', 'Wrong battery type selected'], symptoms: ['Charging stops', 'Error 400', 'Hot battery'], solution: 'Correct charge settings.', steps: ['Check battery voltage', 'Review charge parameters', 'Verify battery type setting'], prevention: ['Correct configuration', 'BMS communication'], tools: ['Multimeter', 'Inverter interface'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'Error 401', name: 'Battery Under Voltage', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'High', category: 'Battery', description: 'Battery voltage below minimum safe level.', causes: ['Excessive discharge', 'Low DOD setting failure', 'Battery degradation'], symptoms: ['System shutdown', 'Error 401'], solution: 'Recharge and adjust settings.', steps: ['Charge battery', 'Adjust cutoff voltage', 'Check battery health'], prevention: ['Proper DOD settings', 'Load management'], tools: ['Multimeter', 'Battery tester'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'Error 402', name: 'Battery Over Temperature', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'High', category: 'Battery', description: 'Battery temperature exceeds safe limit.', causes: ['Poor ventilation', 'High charge/discharge rate', 'Internal fault'], symptoms: ['Charge limited', 'Error 402', 'Hot battery'], solution: 'Improve cooling or reduce rates.', steps: ['Check battery temperature', 'Improve ventilation', 'Reduce current'], prevention: ['Proper installation', 'Temperature sensor'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'Error 403', name: 'Battery Communication Error', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'Medium', category: 'Battery', description: 'Lost communication with battery BMS.', causes: ['Cable disconnected', 'BMS fault', 'Protocol mismatch'], symptoms: ['Battery offline', 'Error 403', 'Default charging'], solution: 'Restore communication.', steps: ['Check cables', 'Verify protocol', 'Check BMS power'], prevention: ['Secure connections', 'Compatible equipment'], tools: ['Communication cables'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'Error 404', name: 'Battery Reverse Polarity', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'Critical', category: 'Battery', description: 'Battery connected with reversed polarity.', causes: ['Installation error'], symptoms: ['No operation', 'Possible damage', 'Error 404'], solution: 'Correct immediately, check for damage.', steps: ['Disconnect battery', 'Correct polarity', 'Check for damage', 'Test operation'], prevention: ['Careful installation', 'Polarity verification'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-150,000' },
  { code: 'Error 405', name: 'No Battery Detected', brand: 'Growatt', model: 'SPF/SPH/SPA', severity: 'Medium', category: 'Battery', description: 'Battery not detected by inverter.', causes: ['Battery disconnected', 'BMS off', 'Fuse blown', 'Cable fault'], symptoms: ['No battery operation', 'Error 405'], solution: 'Check battery connection.', steps: ['Verify battery is connected and powered', 'Check fuses', 'Check cables'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-10,000' },

  // Protection Faults
  { code: 'Error 500', name: 'Ground Fault Current High', brand: 'Growatt', model: 'All Models', severity: 'Critical', category: 'Protection', description: 'Excessive current flowing to ground detected.', causes: ['Insulation failure', 'Ground fault in wiring', 'Equipment fault'], symptoms: ['Immediate shutdown', 'Error 500'], solution: 'Locate and clear ground fault.', steps: ['Test all circuit insulation', 'Identify fault location', 'Repair'], prevention: ['Quality installation', 'Regular testing'], tools: ['Insulation tester', 'Clamp meter'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-60,000' },
  { code: 'Error 501', name: 'Leakage Current High', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Protection', description: 'DC leakage current to ground exceeds limit.', causes: ['Insulation degradation', 'Moisture', 'Panel PID'], symptoms: ['Error 501', 'Reduced operation'], solution: 'Identify leakage source.', steps: ['Test insulation resistance', 'Check for moisture', 'Inspect panels'], prevention: ['Proper installation', 'Grounding'], tools: ['Megger', 'Leakage clamp'], estimatedTime: '2-6 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'Error 502', name: 'GFCI/RCD Trip', brand: 'Growatt', model: 'All Models', severity: 'High', category: 'Protection', description: 'Ground fault circuit interrupter has tripped.', causes: ['Ground fault present', 'RCD too sensitive', 'Nuisance trip'], symptoms: ['System offline', 'Error 502'], solution: 'Identify cause of trip.', steps: ['Reset RCD', 'If trips again, investigate', 'May need different RCD type'], prevention: ['Proper RCD selection'], tools: ['Multimeter', 'RCD tester'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'Error 503', name: 'Arc Fault Detected', brand: 'Growatt', model: 'AFCI Models', severity: 'Critical', category: 'Protection', description: 'DC arc fault detected - fire hazard.', causes: ['Loose connection', 'Damaged connector', 'Cable damage'], symptoms: ['Immediate shutdown', 'Error 503'], solution: 'Thoroughly inspect all DC connections before restart.', steps: ['DO NOT restart without inspection', 'Check all MC4 connectors', 'Inspect cables', 'Look for burn marks'], prevention: ['Quality installation', 'Regular inspection'], tools: ['Visual inspection', 'Thermal camera'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-65,000' },
  { code: 'Error 504', name: 'Surge Protection Activated', brand: 'Growatt', model: 'All Models', severity: 'Medium', category: 'Protection', description: 'Surge protection device has activated.', causes: ['Lightning nearby', 'Grid surge', 'Switching transient'], symptoms: ['Temporary shutdown', 'Error 504'], solution: 'Check SPD status, may need replacement.', steps: ['Check SPD indicator', 'Replace if tripped', 'Check for damage'], prevention: ['Quality SPDs', 'Proper grounding'], tools: ['Visual inspection'], estimatedTime: '1-2 hours', estimatedCost: 'KES 5,000-20,000' },

  // Communication Faults
  { code: 'Error 600', name: 'WiFi Module Offline', brand: 'Growatt', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi monitoring dongle not communicating.', causes: ['Weak signal', 'Module fault', 'Network change'], symptoms: ['No monitoring data', 'Error 600'], solution: 'Restore WiFi connection.', steps: ['Check WiFi signal', 'Reconnect module', 'Reconfigure if needed'], prevention: ['Strong WiFi signal'], tools: ['Phone/laptop'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'Error 601', name: 'RS485 Communication Error', brand: 'Growatt', model: 'All Models', severity: 'Low', category: 'Communication', description: 'RS485 serial communication fault.', causes: ['Cable issue', 'Address conflict', 'Termination wrong'], symptoms: ['No communication', 'Error 601'], solution: 'Check RS485 wiring and settings.', steps: ['Check cable connections', 'Verify addresses', 'Check termination resistors'], prevention: ['Proper installation'], tools: ['RS485 tester'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'Error 602', name: 'CAN Bus Error', brand: 'Growatt', model: 'SPH/SPA', severity: 'Medium', category: 'Communication', description: 'CAN bus communication fault with battery.', causes: ['Cable fault', 'Protocol mismatch', 'BMS issue'], symptoms: ['Battery not responding', 'Error 602'], solution: 'Check CAN bus wiring and compatibility.', steps: ['Verify cable connections', 'Check CAN H/L wiring', 'Verify BMS compatible'], prevention: ['Compatible equipment'], tools: ['CAN analyzer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'Error 603', name: 'Meter Communication Lost', brand: 'Growatt', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Smart meter communication interrupted.', causes: ['CT disconnected', 'Meter fault', 'Wiring issue'], symptoms: ['No power flow data', 'Error 603'], solution: 'Check meter connection.', steps: ['Verify CT connections', 'Check meter power', 'Check RS485 link'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DEYE INVERTER FAULT CODES - Complete Database (40+ Codes)
// Models: SUN-xK-SG01/03/04LP1, SUN-xK-G03/04, Hybrid Series
// ═══════════════════════════════════════════════════════════════════════════════

export const DEYE_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: 'F01', name: 'Grid Lost', brand: 'Deye', model: 'All Models', severity: 'Low', category: 'Grid', description: 'No grid voltage detected at AC input.', causes: ['Power outage', 'Breaker off', 'Loose connection'], symptoms: ['Grid lost display', 'Battery mode active'], solution: 'Check grid connection.', steps: ['Verify utility power', 'Check breakers', 'Inspect connections'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-5,000' },
  { code: 'F02', name: 'Grid Voltage High', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage above maximum limit.', causes: ['Utility voltage high', 'Connection issue'], symptoms: ['No export', 'F02 displayed'], solution: 'Check grid voltage.', steps: ['Measure grid voltage', 'Report to utility if high'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'F03', name: 'Grid Voltage Low', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage below minimum limit.', causes: ['Utility voltage low', 'Heavy loads', 'Cable undersized'], symptoms: ['No export', 'F03 displayed'], solution: 'Improve grid voltage.', steps: ['Measure voltage', 'Check cable sizing', 'Report to utility'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F04', name: 'Grid Frequency High', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency above limit (>52Hz).', causes: ['Grid instability', 'Generator issue'], symptoms: ['Inverter stops', 'F04 displayed'], solution: 'Check grid frequency.', steps: ['Measure frequency', 'Verify grid source'], prevention: ['Proper grid connection'], tools: ['Frequency meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'F05', name: 'Grid Frequency Low', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid frequency below limit (<47.5Hz).', causes: ['Grid overloaded', 'Utility issue'], symptoms: ['Inverter stops', 'F05 displayed'], solution: 'Check grid frequency.', steps: ['Measure frequency', 'Report to utility'], prevention: ['Monitor grid'], tools: ['Frequency meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'F06', name: 'Island Mode Detected', brand: 'Deye', model: 'All Models', severity: 'Critical', category: 'Grid', description: 'Possible island condition detected - safety shutdown.', causes: ['Grid disconnected', 'Impedance change'], symptoms: ['Immediate shutdown', 'F06'], solution: 'Verify grid connection.', steps: ['Check grid status', 'Verify bonding', 'Check other inverters'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'F07', name: 'Phase Sequence Error', brand: 'Deye', model: 'Three Phase', severity: 'High', category: 'Grid', description: 'Three phase sequence is incorrect (should be L1-L2-L3).', causes: ['Installation error', 'Utility change'], symptoms: ['Won\'t connect', 'F07'], solution: 'Correct phase sequence.', steps: ['Verify phase rotation', 'Swap phases if needed'], prevention: ['Phase rotation check at install'], tools: ['Phase rotation meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 2,000-10,000' },

  // PV Faults
  { code: 'F10', name: 'PV1 Over Voltage', brand: 'Deye', model: 'All Models', severity: 'Critical', category: 'PV', description: 'String 1 voltage exceeds maximum.', causes: ['Too many panels', 'Cold weather'], symptoms: ['Won\'t start', 'F10'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure string'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F11', name: 'PV2 Over Voltage', brand: 'Deye', model: 'Dual MPPT', severity: 'Critical', category: 'PV', description: 'String 2 voltage exceeds maximum.', causes: ['Same as F10'], symptoms: ['F11 displayed'], solution: 'Reduce string voltage.', steps: ['Measure String 2 Voc', 'Reconfigure'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F12', name: 'PV Insulation Low', brand: 'Deye', model: 'All Models', severity: 'Critical', category: 'PV', description: 'DC insulation resistance below safe limit.', causes: ['Ground fault', 'Water ingress', 'Cable damage'], symptoms: ['Won\'t operate', 'F12'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Find fault', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F13', name: 'PV1 Current High', brand: 'Deye', model: 'All Models', severity: 'High', category: 'PV', description: 'String 1 current exceeds rated input current.', causes: ['Too many strings parallel', 'Panel mismatch'], symptoms: ['F13', 'Possible damage'], solution: 'Reduce parallel strings.', steps: ['Measure current', 'Reconfigure'], prevention: ['Proper design'], tools: ['Clamp meter'], estimatedTime: '2-6 hours', estimatedCost: 'KES 5,000-30,000' },
  { code: 'F14', name: 'PV Reverse Current', brand: 'Deye', model: 'All Models', severity: 'High', category: 'PV', description: 'Reverse current flow detected in PV circuit.', causes: ['Shaded panel', 'Bypass diode failure', 'Configuration error'], symptoms: ['F14', 'Reduced output'], solution: 'Check for shading and bypass diodes.', steps: ['Inspect panels', 'Check diodes', 'Verify configuration'], prevention: ['Proper design'], tools: ['Multimeter'], estimatedTime: '2-4 hours', estimatedCost: 'KES 5,000-25,000' },

  // Battery Faults
  { code: 'F20', name: 'Battery Over Voltage', brand: 'Deye', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage exceeds maximum charge limit.', causes: ['Wrong settings', 'BMS fault'], symptoms: ['Charging stops', 'F20'], solution: 'Correct charge settings.', steps: ['Check voltage', 'Adjust settings', 'Check BMS'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F21', name: 'Battery Under Voltage', brand: 'Deye', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery voltage below minimum.', causes: ['Over discharge', 'Battery fault'], symptoms: ['System shutdown', 'F21'], solution: 'Recharge battery.', steps: ['Charge battery', 'Check health', 'Adjust DOD'], prevention: ['Proper settings'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'F22', name: 'Battery Over Temperature', brand: 'Deye', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery temperature too high.', causes: ['Poor ventilation', 'High current'], symptoms: ['Current limited', 'F22'], solution: 'Improve cooling.', steps: ['Check temperature', 'Improve ventilation'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'F23', name: 'Battery Low Temperature', brand: 'Deye', model: 'Hybrid', severity: 'Medium', category: 'Battery', description: 'Battery too cold for charging.', causes: ['Cold environment'], symptoms: ['Charging suspended', 'F23'], solution: 'Allow warming or add heating.', steps: ['Check temperature', 'Wait or add heater'], prevention: ['Insulated location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F24', name: 'BMS Communication Lost', brand: 'Deye', model: 'Hybrid', severity: 'Medium', category: 'Battery', description: 'Lost communication with battery BMS.', causes: ['Cable fault', 'BMS offline'], symptoms: ['Battery offline', 'F24'], solution: 'Restore communication.', steps: ['Check cables', 'Check BMS', 'Restart'], prevention: ['Secure connections'], tools: ['Communication cable'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F25', name: 'Battery Current High', brand: 'Deye', model: 'Hybrid', severity: 'High', category: 'Battery', description: 'Battery current exceeds maximum.', causes: ['Overload', 'Short circuit'], symptoms: ['Shutdown', 'F25'], solution: 'Reduce load.', steps: ['Check load', 'Verify wiring'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },

  // Inverter Faults
  { code: 'F30', name: 'Inverter Over Temperature', brand: 'Deye', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Inverter internal temperature too high.', causes: ['Poor cooling', 'Overload'], symptoms: ['Derating', 'F30'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Clear vents', 'Check fan'], prevention: ['Proper installation'], tools: ['Temperature meter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: 'F31', name: 'Inverter Over Current', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Protection', description: 'Output current exceeds limit.', causes: ['Overload', 'Short circuit'], symptoms: ['Shutdown', 'F31'], solution: 'Reduce load.', steps: ['Measure load', 'Remove excess loads'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: 'F32', name: 'DC Bus Over Voltage', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal DC bus voltage too high.', causes: ['Grid loss during export', 'PV surge'], symptoms: ['Shutdown', 'F32'], solution: 'Check and restart.', steps: ['Check PV voltage', 'Power cycle'], prevention: ['Surge protection'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F33', name: 'Hardware Fault', brand: 'Deye', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Internal hardware failure.', causes: ['Component failure', 'Surge damage'], symptoms: ['Won\'t operate', 'F33'], solution: 'Service required.', steps: ['Document error', 'Contact service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Days', estimatedCost: 'KES 50,000-200,000' },
  { code: 'F34', name: 'EEPROM Fault', brand: 'Deye', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal memory error.', causes: ['Component fault', 'Corruption'], symptoms: ['Settings lost', 'F34'], solution: 'May need firmware reload or service.', steps: ['Try firmware update', 'Contact service'], prevention: ['Proper shutdown'], tools: ['USB/SD card'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-50,000' },

  // Output Faults
  { code: 'F40', name: 'Output Over Voltage', brand: 'Deye', model: 'Hybrid/Off-grid', severity: 'High', category: 'Output', description: 'AC output voltage too high.', causes: ['Regulation fault', 'Light load'], symptoms: ['Output stops', 'F40'], solution: 'Check load and settings.', steps: ['Measure output voltage', 'Check settings'], prevention: ['Proper configuration'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F41', name: 'Output Under Voltage', brand: 'Deye', model: 'Hybrid/Off-grid', severity: 'High', category: 'Output', description: 'AC output voltage too low.', causes: ['Overload', 'Regulation fault'], symptoms: ['Output low', 'F41'], solution: 'Reduce load or check inverter.', steps: ['Measure voltage', 'Check load'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'F42', name: 'Output Short Circuit', brand: 'Deye', model: 'Hybrid/Off-grid', severity: 'Critical', category: 'Output', description: 'Short circuit detected on AC output.', causes: ['Wiring fault', 'Equipment fault'], symptoms: ['Immediate shutdown', 'F42'], solution: 'Find and clear short.', steps: ['Disconnect loads', 'Find short', 'Repair'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'F43', name: 'Output Overload', brand: 'Deye', model: 'Hybrid/Off-grid', severity: 'Medium', category: 'Output', description: 'Connected load exceeds inverter capacity.', causes: ['Too many loads', 'Motor starting'], symptoms: ['Shutdown or derating', 'F43'], solution: 'Reduce load.', steps: ['Measure load', 'Remove excess'], prevention: ['Load management'], tools: ['Clamp meter'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0' },

  // Communication Faults
  { code: 'F50', name: 'WiFi Module Error', brand: 'Deye', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi monitoring module not responding.', causes: ['Module fault', 'No signal'], symptoms: ['No monitoring', 'F50'], solution: 'Check WiFi module.', steps: ['Check signal', 'Reconnect', 'Replace if faulty'], prevention: ['Good WiFi coverage'], tools: ['Phone'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: 'F51', name: 'Meter Communication Lost', brand: 'Deye', model: 'All Models', severity: 'Low', category: 'Communication', description: 'External meter not responding.', causes: ['CT disconnected', 'Meter fault'], symptoms: ['No power flow data', 'F51'], solution: 'Check meter connections.', steps: ['Verify CT installation', 'Check wiring'], prevention: ['Secure installation'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SMA INVERTER FAULT CODES - Complete Database (60+ Codes)
// Models: Sunny Boy, Sunny Tripower, Sunny Island, Sunny Highpower
// ═══════════════════════════════════════════════════════════════════════════════

export const SMA_FAULTS: InverterFault[] = [
  // Grid Faults
  { code: '101', name: 'Grid Off', brand: 'SMA', model: 'All Grid-Tie', severity: 'Low', category: 'Grid', description: 'No grid voltage detected.', causes: ['Utility outage', 'Breaker off'], symptoms: ['No operation', 'Event 101'], solution: 'Restore grid.', steps: ['Check utility', 'Check breakers'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: '102', name: 'Grid Voltage Too High', brand: 'SMA', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'AC voltage exceeds upper limit.', causes: ['Utility high', 'Grid impedance'], symptoms: ['No feed-in', 'Event 102'], solution: 'Check grid voltage.', steps: ['Measure voltage', 'Check connections'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: '103', name: 'Grid Voltage Too Low', brand: 'SMA', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'AC voltage below lower limit.', causes: ['Utility low', 'Cable drop'], symptoms: ['No feed-in', 'Event 103'], solution: 'Improve voltage.', steps: ['Measure voltage', 'Check sizing'], prevention: ['Proper cables'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: '104', name: 'Grid Frequency Too High', brand: 'SMA', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'Grid frequency above limit.', causes: ['Grid instability'], symptoms: ['Disconnection', 'Event 104'], solution: 'Wait for grid stability.', steps: ['Monitor frequency'], prevention: ['Grid connection'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: '105', name: 'Grid Frequency Too Low', brand: 'SMA', model: 'All Grid-Tie', severity: 'High', category: 'Grid', description: 'Grid frequency below limit.', causes: ['Grid overload'], symptoms: ['Disconnection', 'Event 105'], solution: 'Wait for recovery.', steps: ['Monitor'], prevention: ['Grid monitoring'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: '202', name: 'AC Disconnector Open', brand: 'SMA', model: 'All Grid-Tie', severity: 'Low', category: 'Grid', description: 'AC isolation switch is open.', causes: ['Manual operation', 'Safety trip'], symptoms: ['No operation', 'Event 202'], solution: 'Close AC disconnector.', steps: ['Close switch', 'Verify safe'], prevention: ['Normal operation'], tools: ['None'], estimatedTime: '5 min', estimatedCost: 'KES 0' },
  { code: '301', name: 'Unstable Grid Frequency', brand: 'SMA', model: 'All Grid-Tie', severity: 'Medium', category: 'Grid', description: 'Frequency is varying excessively.', causes: ['Weak grid', 'Generation/load imbalance'], symptoms: ['Intermittent operation', 'Event 301'], solution: 'Monitor, report to utility.', steps: ['Log frequency variations', 'Report'], prevention: ['Grid quality'], tools: ['Data logger'], estimatedTime: 'Variable', estimatedCost: 'KES 0' },

  // DC/PV Faults
  { code: '401', name: 'DC Overvoltage', brand: 'SMA', model: 'All Models', severity: 'Critical', category: 'PV', description: 'DC input voltage exceeds maximum.', causes: ['String too long', 'Cold conditions'], symptoms: ['No start', 'Event 401'], solution: 'Reduce string length.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '402', name: 'DC Overcurrent', brand: 'SMA', model: 'All Models', severity: 'High', category: 'PV', description: 'DC input current exceeds maximum.', causes: ['Too many parallel strings'], symptoms: ['Reduced output', 'Event 402'], solution: 'Reduce parallel strings.', steps: ['Measure current', 'Reconfigure'], prevention: ['Proper design'], tools: ['Clamp meter'], estimatedTime: '2-6 hours', estimatedCost: 'KES 5,000-30,000' },
  { code: '501', name: 'Insulation Resistance Low', brand: 'SMA', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault - low insulation resistance.', causes: ['Cable damage', 'Moisture'], symptoms: ['No operation', 'Event 501'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Find fault', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '502', name: 'Residual Current Too High', brand: 'SMA', model: 'All Models', severity: 'High', category: 'PV', description: 'DC leakage current exceeds limit.', causes: ['Insulation degradation', 'PID'], symptoms: ['Operation limited', 'Event 502'], solution: 'Investigate leakage source.', steps: ['Test insulation', 'Check panels'], prevention: ['Proper grounding'], tools: ['Leakage clamp'], estimatedTime: '2-6 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '503', name: 'String x Current High', brand: 'SMA', model: 'Multi-String', severity: 'Medium', category: 'PV', description: 'One string has abnormally high current.', causes: ['String configuration error', 'Panel fault'], symptoms: ['Possible damage', 'Event 503'], solution: 'Verify string configuration.', steps: ['Measure currents', 'Check configuration'], prevention: ['Matched strings'], tools: ['Clamp meter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: '504', name: 'String x Current Low', brand: 'SMA', model: 'Multi-String', severity: 'Medium', category: 'PV', description: 'One string producing less than expected.', causes: ['Shading', 'Panel fault', 'Connection'], symptoms: ['Reduced output', 'Event 504'], solution: 'Investigate string.', steps: ['Check for shading', 'Test panels', 'Check connections'], prevention: ['Regular monitoring'], tools: ['Thermal camera'], estimatedTime: '2-4 hours', estimatedCost: 'KES 5,000-30,000' },

  // Inverter/Hardware Faults
  { code: '601', name: 'Overtemperature', brand: 'SMA', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Internal temperature too high.', causes: ['Poor ventilation', 'High ambient'], symptoms: ['Derating', 'Event 601'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Add shading'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: '701', name: 'Self-Test Failed', brand: 'SMA', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal self-test did not pass.', causes: ['Component degradation', 'Fault condition'], symptoms: ['No operation', 'Event 701'], solution: 'Restart, contact service if persists.', steps: ['Power cycle', 'Monitor', 'Contact service'], prevention: ['Regular maintenance'], tools: ['None initial'], estimatedTime: '1 hour-days', estimatedCost: 'KES 0-100,000' },
  { code: '801', name: 'Grid Relay Test Failed', brand: 'SMA', model: 'All Grid-Tie', severity: 'Critical', category: 'Hardware', description: 'Grid connection relay self-test failed.', causes: ['Relay wear', 'Control fault'], symptoms: ['Cannot connect', 'Event 801'], solution: 'Service required.', steps: ['Document', 'Contact service'], prevention: ['Regular service'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },
  { code: '901', name: 'Fan Defective', brand: 'SMA', model: 'Models with fan', severity: 'Medium', category: 'Hardware', description: 'Cooling fan not operating correctly.', causes: ['Motor failure', 'Obstruction'], symptoms: ['Fan not running', 'Event 901'], solution: 'Replace fan.', steps: ['Check fan', 'Clear obstruction', 'Replace'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },
  { code: '1001', name: 'Arc Fault Detected', brand: 'SMA', model: 'AFCI Models', severity: 'Critical', category: 'Safety', description: 'DC arc fault signature detected.', causes: ['Loose connection', 'Cable damage'], symptoms: ['Immediate stop', 'Event 1001'], solution: 'Inspect all DC connections.', steps: ['Do not restart', 'Inspect thoroughly', 'Repair'], prevention: ['Quality connections'], tools: ['Visual', 'Thermal camera'], estimatedTime: '2-8 hours', estimatedCost: 'KES 10,000-65,000' },

  // Communication
  { code: '1101', name: 'SMA Speedwire Fault', brand: 'SMA', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Ethernet communication fault.', causes: ['Cable fault', 'Network issue'], symptoms: ['No monitoring', 'Event 1101'], solution: 'Check network connection.', steps: ['Verify cable', 'Check network settings'], prevention: ['Secure installation'], tools: ['Network tester'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-5,000' },
  { code: '1102', name: 'Webconnect Fault', brand: 'SMA', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Cannot connect to Sunny Portal.', causes: ['Internet down', 'DNS issue', 'Portal maintenance'], symptoms: ['No cloud monitoring', 'Event 1102'], solution: 'Check internet connection.', steps: ['Verify internet', 'Check portal status'], prevention: ['Reliable internet'], tools: ['Network tools'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0' },

  // Sunny Island Specific
  { code: 'SI-101', name: 'Battery Voltage High', brand: 'SMA', model: 'Sunny Island', severity: 'High', category: 'Battery', description: 'Battery voltage exceeds limit.', causes: ['Wrong charge settings', 'BMS fault'], symptoms: ['Charging stopped', 'SI-101'], solution: 'Adjust charge parameters.', steps: ['Check voltage', 'Adjust settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'SI-102', name: 'Battery Voltage Low', brand: 'SMA', model: 'Sunny Island', severity: 'High', category: 'Battery', description: 'Battery voltage too low.', causes: ['Overdischarge'], symptoms: ['System off', 'SI-102'], solution: 'Recharge battery.', steps: ['Charge', 'Adjust DOD'], prevention: ['Proper settings'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'SI-103', name: 'Battery Temperature High', brand: 'SMA', model: 'Sunny Island', severity: 'High', category: 'Battery', description: 'Battery overheating.', causes: ['Poor ventilation', 'High current'], symptoms: ['Current limited', 'SI-103'], solution: 'Improve cooling.', steps: ['Check temp', 'Improve ventilation'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 5,000-50,000' },
  { code: 'SI-104', name: 'Overload', brand: 'SMA', model: 'Sunny Island', severity: 'High', category: 'Output', description: 'Output overloaded.', causes: ['Excess load', 'Motor starting'], symptoms: ['Shutdown', 'SI-104'], solution: 'Reduce load.', steps: ['Measure load', 'Remove excess'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FRONIUS INVERTER FAULT CODES - Complete Database (50+ Codes)
// Models: Primo, Symo, Gen24, Tauro
// ═══════════════════════════════════════════════════════════════════════════════

export const FRONIUS_FAULTS: InverterFault[] = [
  // State Codes
  { code: '102', name: 'AC Voltage Too High', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage above maximum limit.', causes: ['Utility high', 'Grid impedance'], symptoms: ['No feed-in', 'State 102'], solution: 'Check grid voltage.', steps: ['Measure voltage', 'Verify settings'], prevention: ['Site assessment'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-10,000' },
  { code: '103', name: 'AC Voltage Too Low', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Grid', description: 'Grid voltage below minimum.', causes: ['Utility low', 'Cable drop'], symptoms: ['No feed-in', 'State 103'], solution: 'Improve voltage.', steps: ['Check connections', 'Verify cable sizing'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-25,000' },
  { code: '105', name: 'AC Frequency Too High', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency above limit.', causes: ['Grid issue'], symptoms: ['Disconnection', 'State 105'], solution: 'Wait for grid stability.', steps: ['Monitor frequency'], prevention: ['Grid monitoring'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: '106', name: 'AC Frequency Too Low', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Grid', description: 'Frequency below limit.', causes: ['Grid overload'], symptoms: ['Disconnection', 'State 106'], solution: 'Wait for recovery.', steps: ['Monitor'], prevention: ['Grid connection'], tools: ['Frequency meter'], estimatedTime: '1 hour', estimatedCost: 'KES 0' },
  { code: '107', name: 'No Feeding', brand: 'Fronius', model: 'All Grid-Tie', severity: 'Low', category: 'Grid', description: 'No grid connection detected.', causes: ['Power outage', 'Breaker off'], symptoms: ['No operation', 'State 107'], solution: 'Check grid.', steps: ['Verify utility', 'Check breakers'], prevention: ['Proper connection'], tools: ['Multimeter'], estimatedTime: '30 min', estimatedCost: 'KES 0' },

  // DC Faults
  { code: '301', name: 'DC Overvoltage', brand: 'Fronius', model: 'All Models', severity: 'Critical', category: 'PV', description: 'PV voltage too high.', causes: ['String too long', 'Cold weather'], symptoms: ['No operation', 'State 301'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure string'], prevention: ['Proper sizing'], tools: ['DC multimeter'], estimatedTime: '4-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '302', name: 'DC Undervoltage', brand: 'Fronius', model: 'All Models', severity: 'Low', category: 'PV', description: 'PV voltage below minimum start voltage.', causes: ['Low irradiance', 'Shading', 'String too short'], symptoms: ['No start', 'State 302'], solution: 'Wait for more sun or check string.', steps: ['Check irradiance', 'Verify string configuration'], prevention: ['Proper design'], tools: ['Irradiance meter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: '303', name: 'DC Overcurrent', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'PV', description: 'DC current exceeds maximum.', causes: ['Too many parallel strings'], symptoms: ['Shutdown', 'State 303'], solution: 'Reduce parallel strings.', steps: ['Measure current', 'Reconfigure'], prevention: ['Proper design'], tools: ['Clamp meter'], estimatedTime: '2-6 hours', estimatedCost: 'KES 5,000-30,000' },
  { code: '401', name: 'Insulation Fault', brand: 'Fronius', model: 'All Models', severity: 'Critical', category: 'PV', description: 'Ground fault in DC system.', causes: ['Cable damage', 'Water ingress', 'Panel fault'], symptoms: ['No operation', 'State 401'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Find fault', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '3-8 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '402', name: 'RCMU Error', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Protection', description: 'Residual current monitoring unit fault.', causes: ['RCMU fault', 'Installation error'], symptoms: ['No operation', 'State 402'], solution: 'Check RCMU and installation.', steps: ['Reset', 'Check bonding', 'Service if persists'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: '403', name: 'Ground Current High', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Protection', description: 'Excessive current to ground.', causes: ['Insulation fault', 'Equipment fault'], symptoms: ['Operation limited', 'State 403'], solution: 'Find leakage source.', steps: ['Test insulation', 'Identify source'], prevention: ['Regular testing'], tools: ['Leakage clamp'], estimatedTime: '2-6 hours', estimatedCost: 'KES 10,000-50,000' },

  // Thermal Faults
  { code: '501', name: 'Temperature Too High', brand: 'Fronius', model: 'All Models', severity: 'Medium', category: 'Thermal', description: 'Overtemperature condition.', causes: ['Poor ventilation', 'High ambient'], symptoms: ['Derating', 'State 501'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Clean vents', 'Add shading'], prevention: ['Proper location'], tools: ['Thermometer'], estimatedTime: '1-4 hours', estimatedCost: 'KES 2,000-25,000' },
  { code: '502', name: 'Fan Speed Low', brand: 'Fronius', model: 'Models with fan', severity: 'Medium', category: 'Hardware', description: 'Cooling fan not running at correct speed.', causes: ['Fan degradation', 'Obstruction'], symptoms: ['Overheating risk', 'State 502'], solution: 'Clean or replace fan.', steps: ['Check fan', 'Clear debris', 'Replace if needed'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '2-4 hours', estimatedCost: 'KES 8,000-25,000' },

  // Hardware Faults
  { code: '601', name: 'Power Stack Fault', brand: 'Fronius', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Power stage hardware failure.', causes: ['Component failure', 'Surge damage'], symptoms: ['No operation', 'State 601'], solution: 'Service required.', steps: ['Document', 'Contact Fronius service'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 75,000-200,000' },
  { code: '602', name: 'Control Board Fault', brand: 'Fronius', model: 'All Models', severity: 'Critical', category: 'Hardware', description: 'Control PCB malfunction.', causes: ['Component failure', 'Corruption'], symptoms: ['No operation', 'State 602'], solution: 'Service required.', steps: ['Document', 'Contact service'], prevention: ['Proper installation'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },
  { code: '603', name: 'Memory Error', brand: 'Fronius', model: 'All Models', severity: 'High', category: 'Hardware', description: 'Internal memory fault.', causes: ['Corruption', 'Component fault'], symptoms: ['Settings lost', 'State 603'], solution: 'Firmware reload or service.', steps: ['Try firmware update', 'Service if fails'], prevention: ['Proper shutdown'], tools: ['USB'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-50,000' },
  { code: '604', name: 'Relay Test Failed', brand: 'Fronius', model: 'All Grid-Tie', severity: 'Critical', category: 'Hardware', description: 'Grid relay test failed.', causes: ['Relay wear', 'Control fault'], symptoms: ['Cannot connect', 'State 604'], solution: 'Service required.', steps: ['Document', 'Contact service'], prevention: ['Regular service'], tools: ['None'], estimatedTime: 'Service', estimatedCost: 'KES 50,000-150,000' },

  // Gen24 Hybrid Specific
  { code: 'BYD-01', name: 'BYD Battery Offline', brand: 'Fronius', model: 'Gen24', severity: 'Medium', category: 'Battery', description: 'Cannot communicate with BYD battery.', causes: ['Cable fault', 'BMS offline'], symptoms: ['No battery operation', 'BYD-01'], solution: 'Check battery communication.', steps: ['Check cables', 'Check BMS', 'Restart'], prevention: ['Secure connections'], tools: ['None'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'BAT-HV', name: 'Battery High Voltage', brand: 'Fronius', model: 'Gen24', severity: 'High', category: 'Battery', description: 'Battery voltage too high.', causes: ['Charge settings wrong', 'BMS fault'], symptoms: ['Charging stopped'], solution: 'Check settings.', steps: ['Verify voltage', 'Check settings'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-15,000' },
  { code: 'BAT-LV', name: 'Battery Low Voltage', brand: 'Fronius', model: 'Gen24', severity: 'High', category: 'Battery', description: 'Battery discharged too far.', causes: ['Overdischarge'], symptoms: ['System offline'], solution: 'Recharge.', steps: ['Charge battery', 'Adjust DOD'], prevention: ['Proper DOD'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 0-300,000' },

  // Communication
  { code: '701', name: 'WLAN Fault', brand: 'Fronius', model: 'All Models', severity: 'Low', category: 'Communication', description: 'WiFi connection lost.', causes: ['Signal weak', 'Network change'], symptoms: ['No cloud monitoring', 'State 701'], solution: 'Check WiFi.', steps: ['Verify signal', 'Reconnect'], prevention: ['Good WiFi coverage'], tools: ['Phone'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0' },
  { code: '702', name: 'SolarWeb Fault', brand: 'Fronius', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Cannot connect to Fronius cloud.', causes: ['Internet down', 'Server issue'], symptoms: ['No portal data', 'State 702'], solution: 'Check internet.', steps: ['Verify connection', 'Check server status'], prevention: ['Reliable internet'], tools: ['Network tools'], estimatedTime: '30 min', estimatedCost: 'KES 0' },
  { code: '703', name: 'Modbus Error', brand: 'Fronius', model: 'All Models', severity: 'Low', category: 'Communication', description: 'Modbus communication fault.', causes: ['Wiring', 'Settings'], symptoms: ['No external control', 'State 703'], solution: 'Check Modbus setup.', steps: ['Verify wiring', 'Check settings'], prevention: ['Proper installation'], tools: ['Modbus tester'], estimatedTime: '1-3 hours', estimatedCost: 'KES 0-10,000' },
];

// Export combined array
export const INVERTER_FAULTS_PART1: InverterFault[] = [
  ...GROWATT_FAULTS,
  ...DEYE_FAULTS,
  ...SMA_FAULTS,
  ...FRONIUS_FAULTS,
];

// Helper to get all brands in this file
export const BRANDS_PART1 = ['Growatt', 'Deye', 'SMA', 'Fronius'];

export const FAULT_COUNT_PART1 = INVERTER_FAULTS_PART1.length;
