/**
 * Comprehensive Inverter Fault Codes - Part 3
 * Additional Brands: Voltronic/Axpert, Must Solar, MPP Solar, ABB/FIMER, Schneider, Outback
 * World's Most Comprehensive Solar Maintenance Hub
 */

import { InverterFault } from './inverter-faults-part1';

// ═══════════════════════════════════════════════════════════════════════════════
// VOLTRONIC/AXPERT INVERTER FAULT CODES (15 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const VOLTRONIC_AXPERT_FAULTS: InverterFault[] = [
  { code: 'F01', name: 'Fan Locked', brand: 'Voltronic/Axpert', model: 'VM III, MKS, King', severity: 'High', category: 'Thermal', description: 'Cooling fan stopped rotating or blocked.', causes: ['Fan failure', 'Debris', 'Connector loose'], symptoms: ['Shutdown', 'High temp', 'No fan noise'], solution: 'Clean or replace fan.', steps: ['Power off', 'Inspect fan', 'Clean or replace'], prevention: ['Regular cleaning'], tools: ['Screwdriver', 'Multimeter'], estimatedTime: '30-60 min', estimatedCost: 'KES 5,000-15,000' },
  { code: 'F02', name: 'Over Temperature', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Critical', category: 'Thermal', description: 'Internal temperature exceeded safe limits.', causes: ['Poor ventilation', 'Fan failure', 'Overload'], symptoms: ['Shutdown', 'Hot enclosure'], solution: 'Improve cooling, reduce load.', steps: ['Cool down', 'Check ventilation', 'Verify fan'], prevention: ['Proper ventilation'], tools: ['Thermometer'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'F03', name: 'Battery Voltage Low', brand: 'Voltronic/Axpert', model: 'All models', severity: 'High', category: 'Battery', description: 'Battery voltage below minimum threshold.', causes: ['Depleted batteries', 'Bad cells', 'Loose connections'], symptoms: ['Transfer to utility', 'Low battery alarm'], solution: 'Recharge batteries, check connections.', steps: ['Measure voltage', 'Check connections', 'Charge'], prevention: ['Regular maintenance'], tools: ['Multimeter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'F04', name: 'Battery Voltage High', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Critical', category: 'Battery', description: 'Battery voltage exceeds safe charging limit.', causes: ['Wrong settings', 'External charger'], symptoms: ['Charging stops', 'Alarm'], solution: 'Correct charge settings.', steps: ['Check settings', 'Match battery type', 'Remove extra chargers'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'F05', name: 'Line Fail', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Low', category: 'Grid', description: 'AC utility lost or outside parameters.', causes: ['Power outage', 'Loose connection', 'Breaker tripped'], symptoms: ['Transfer to battery', 'Utility LED off'], solution: 'Check grid connection.', steps: ['Check breaker', 'Measure voltage', 'Check wiring'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '15-60 min', estimatedCost: 'KES 0-5,000' },
  { code: 'F06', name: 'Output Short Circuit', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Critical', category: 'Output', description: 'Short circuit on AC output.', causes: ['Wiring fault', 'Equipment failure', 'Water ingress'], symptoms: ['Immediate shutdown', 'No output'], solution: 'Find and repair short.', steps: ['Disconnect loads', 'Test circuits', 'Repair'], prevention: ['Proper installation'], tools: ['Multimeter', 'Megger'], estimatedTime: '1-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F07', name: 'Overload', brand: 'Voltronic/Axpert', model: 'All models', severity: 'High', category: 'Output', description: 'Load exceeds inverter capacity.', causes: ['Excessive load', 'Motor startup'], symptoms: ['Overload alarm', 'Power reduction'], solution: 'Reduce load.', steps: ['Check load', 'Remove non-essential', 'Stagger startups'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'F08', name: 'Bus Over Voltage', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Critical', category: 'Internal', description: 'Internal DC bus voltage exceeded.', causes: ['Component failure', 'PV overvoltage'], symptoms: ['Shutdown', 'Cannot restart'], solution: 'Professional repair.', steps: ['Check PV voltage', 'Contact service'], prevention: ['Proper PV sizing'], tools: ['Contact service'], estimatedTime: 'Professional', estimatedCost: 'KES 50,000-150,000' },
  { code: 'F09', name: 'Bus Under Voltage', brand: 'Voltronic/Axpert', model: 'All models', severity: 'High', category: 'Internal', description: 'Internal DC bus voltage too low.', causes: ['Low battery', 'Boost circuit issue'], symptoms: ['Cannot produce output', 'Startup fails'], solution: 'Charge batteries, check inputs.', steps: ['Check battery voltage', 'Check fuses'], prevention: ['Maintain battery'], tools: ['Multimeter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-50,000' },
  { code: 'F10', name: 'PV Voltage High', brand: 'Voltronic/Axpert', model: 'VM III, MKS', severity: 'Critical', category: 'PV', description: 'Solar voltage exceeds MPPT maximum.', causes: ['Too many panels in series', 'Cold weather'], symptoms: ['PV charging stops', 'Alarm'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure array'], prevention: ['Proper design'], tools: ['DC multimeter', 'MC4 tools'], estimatedTime: '1-3 hours', estimatedCost: 'KES 10,000-40,000' },
  { code: 'F11', name: 'Over Current', brand: 'Voltronic/Axpert', model: 'All models', severity: 'High', category: 'Protection', description: 'Current exceeded safe limits.', causes: ['Short circuit', 'Overload'], symptoms: ['Shutdown', 'Output stops'], solution: 'Identify and fix overcurrent source.', steps: ['Disconnect loads', 'Test circuits'], prevention: ['Proper protection'], tools: ['Clamp meter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-20,000' },
  { code: 'F12', name: 'EEPROM Fault', brand: 'Voltronic/Axpert', model: 'All models', severity: 'High', category: 'Internal', description: 'Configuration memory error.', causes: ['Memory failure', 'Corruption'], symptoms: ['Settings lost', 'Erratic behavior'], solution: 'Factory reset or service.', steps: ['Try reset', 'Update firmware', 'Contact service'], prevention: ['Surge protection'], tools: ['USB cable'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-75,000' },
  { code: 'F50', name: 'Communication Fault', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Medium', category: 'Communication', description: 'Communication with BMS or monitoring lost.', causes: ['Loose cable', 'Protocol mismatch'], symptoms: ['BMS data missing', 'No monitoring'], solution: 'Check cables and settings.', steps: ['Check cables', 'Verify protocol'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-10,000' },
  { code: 'F51', name: 'Parallel Fault', brand: 'Voltronic/Axpert', model: 'MKS, King', severity: 'High', category: 'Parallel', description: 'Parallel operation fault.', causes: ['Different firmware', 'Wrong IDs', 'Communication failure'], symptoms: ['Unit shutdown', 'Unequal sharing'], solution: 'Match firmware and settings.', steps: ['Check firmware', 'Verify IDs', 'Check cables'], prevention: ['Same firmware'], tools: ['USB cable', 'Computer'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-20,000' },
  { code: 'F13', name: 'Relay Fail', brand: 'Voltronic/Axpert', model: 'All models', severity: 'Critical', category: 'Hardware', description: 'Relay self-test failed.', causes: ['Relay welding', 'Control fault'], symptoms: ['No output', 'Transfer fails'], solution: 'Replace relay or service.', steps: ['Contact service'], prevention: ['Avoid overloading'], tools: ['Professional service'], estimatedTime: 'Professional', estimatedCost: 'KES 25,000-100,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// MUST SOLAR INVERTER FAULT CODES (10 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const MUST_SOLAR_FAULTS: InverterFault[] = [
  { code: 'ERR01', name: 'Fan Stuck', brand: 'Must Solar', model: 'PV1800, PV3000', severity: 'High', category: 'Thermal', description: 'Cooling fan not operating.', causes: ['Fan failure', 'Debris'], symptoms: ['High temperature', 'Reduced output'], solution: 'Clean or replace fan.', steps: ['Check fan', 'Clean or replace'], prevention: ['Regular cleaning'], tools: ['Screwdriver'], estimatedTime: '30-60 min', estimatedCost: 'KES 5,000-15,000' },
  { code: 'ERR02', name: 'Over Temperature', brand: 'Must Solar', model: 'All models', severity: 'Critical', category: 'Thermal', description: 'Unit temperature exceeds limits.', causes: ['Poor ventilation', 'Overload'], symptoms: ['Shutdown', 'Hot enclosure'], solution: 'Improve ventilation.', steps: ['Cool down', 'Clean vents'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'ERR03', name: 'Battery Overvoltage', brand: 'Must Solar', model: 'All models', severity: 'Critical', category: 'Battery', description: 'Battery voltage exceeds limit.', causes: ['Wrong settings', 'External charger'], symptoms: ['Charging stops', 'Alarm'], solution: 'Correct settings.', steps: ['Check settings', 'Match battery type'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'ERR04', name: 'Battery Under Voltage', brand: 'Must Solar', model: 'All models', severity: 'High', category: 'Battery', description: 'Battery voltage below threshold.', causes: ['Depleted batteries'], symptoms: ['Shutdown', 'Low battery alarm'], solution: 'Recharge batteries.', steps: ['Charge', 'Check cells'], prevention: ['Avoid deep discharge'], tools: ['Multimeter'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'ERR05', name: 'Output Short', brand: 'Must Solar', model: 'All models', severity: 'Critical', category: 'Output', description: 'Short circuit on output.', causes: ['Wiring fault', 'Equipment failure'], symptoms: ['Immediate shutdown'], solution: 'Find and repair short.', steps: ['Disconnect loads', 'Test circuits'], prevention: ['Proper installation'], tools: ['Multimeter'], estimatedTime: '1-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'ERR06', name: 'Overload', brand: 'Must Solar', model: 'All models', severity: 'High', category: 'Output', description: 'Load exceeds capacity.', causes: ['Excessive load'], symptoms: ['Overload alarm'], solution: 'Reduce load.', steps: ['Remove non-essential loads'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'ERR07', name: 'PV Over Voltage', brand: 'Must Solar', model: 'PV series', severity: 'Critical', category: 'PV', description: 'Solar voltage exceeds maximum.', causes: ['Too many panels'], symptoms: ['No solar charging'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper design'], tools: ['DC multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 10,000-40,000' },
  { code: 'ERR08', name: 'PV Insulation Low', brand: 'Must Solar', model: 'PV series', severity: 'Critical', category: 'PV', description: 'Ground fault in PV system.', causes: ['Cable damage', 'Water ingress'], symptoms: ['No PV charging', 'Fault'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'ERR20', name: 'Internal Comm Error', brand: 'Must Solar', model: 'All models', severity: 'High', category: 'Internal', description: 'Internal board communication fault.', causes: ['Loose cable', 'Board failure'], symptoms: ['Erratic behavior'], solution: 'Reseat connections or service.', steps: ['Power cycle', 'Check connections'], prevention: ['Proper installation'], tools: ['Screwdriver'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-50,000' },
  { code: 'ERR21', name: 'BMS Comm Lost', brand: 'Must Solar', model: 'BMS models', severity: 'Medium', category: 'Communication', description: 'Battery BMS communication lost.', causes: ['Cable fault', 'BMS offline'], symptoms: ['Default charging', 'No BMS data'], solution: 'Repair communication link.', steps: ['Check cables', 'Verify protocol'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-10,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// MPP SOLAR INVERTER FAULT CODES (12 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const MPP_SOLAR_FAULTS: InverterFault[] = [
  { code: 'E01', name: 'Inverter Fault', brand: 'MPP Solar', model: 'LV2424, PIP series', severity: 'Critical', category: 'Inverter', description: 'General inverter circuit fault.', causes: ['Component failure', 'Surge damage'], symptoms: ['No output', 'Fault LED'], solution: 'Professional service.', steps: ['Contact support'], prevention: ['Surge protection'], tools: ['Contact manufacturer'], estimatedTime: 'Professional', estimatedCost: 'KES 50,000-200,000' },
  { code: 'E02', name: 'Over Temperature', brand: 'MPP Solar', model: 'All models', severity: 'Critical', category: 'Thermal', description: 'Internal temperature exceeds limits.', causes: ['Poor ventilation', 'Fan failure'], symptoms: ['Shutdown', 'Hot enclosure'], solution: 'Improve cooling.', steps: ['Check fan', 'Clean vents'], prevention: ['Good ventilation'], tools: ['Thermometer'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-25,000' },
  { code: 'E03', name: 'Battery Voltage High', brand: 'MPP Solar', model: 'All models', severity: 'Critical', category: 'Battery', description: 'Battery voltage exceeds limit.', causes: ['Wrong settings', 'Multiple chargers'], symptoms: ['Charging stops', 'Alarm'], solution: 'Correct settings.', steps: ['Check charge voltages', 'Match battery type'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'E04', name: 'Battery Voltage Low', brand: 'MPP Solar', model: 'All models', severity: 'High', category: 'Battery', description: 'Battery voltage below threshold.', causes: ['Discharged', 'Failed cells'], symptoms: ['Shutdown', 'Low battery alarm'], solution: 'Recharge, check cells.', steps: ['Charge', 'Test cells'], prevention: ['Regular maintenance'], tools: ['Multimeter', 'Load tester'], estimatedTime: '30 min-2 hours', estimatedCost: 'KES 0-300,000' },
  { code: 'E05', name: 'Short Circuit', brand: 'MPP Solar', model: 'All models', severity: 'Critical', category: 'Output', description: 'Output short circuit.', causes: ['Wiring fault', 'Equipment failure'], symptoms: ['Immediate shutdown'], solution: 'Find and repair short.', steps: ['Disconnect loads', 'Test circuits'], prevention: ['Proper installation'], tools: ['Multimeter', 'Megger'], estimatedTime: '1-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E06', name: 'Overload', brand: 'MPP Solar', model: 'All models', severity: 'High', category: 'Output', description: 'Output load exceeds capacity.', causes: ['Excessive load', 'Motor inrush'], symptoms: ['Overload alarm', 'Shutdown'], solution: 'Reduce load.', steps: ['Remove non-essential loads'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'E07', name: 'Bus Over Voltage', brand: 'MPP Solar', model: 'All models', severity: 'Critical', category: 'Internal', description: 'Internal DC bus too high.', causes: ['Component failure', 'PV overvoltage'], symptoms: ['Shutdown', 'Cannot restart'], solution: 'Professional service.', steps: ['Check PV', 'Contact support'], prevention: ['Proper PV sizing'], tools: ['Contact support'], estimatedTime: 'Professional', estimatedCost: 'KES 50,000-150,000' },
  { code: 'E08', name: 'Bus Under Voltage', brand: 'MPP Solar', model: 'All models', severity: 'High', category: 'Internal', description: 'Internal DC bus too low.', causes: ['Low battery', 'Connection issue'], symptoms: ['No output', 'Startup failure'], solution: 'Charge battery, check connections.', steps: ['Check battery', 'Check fuses'], prevention: ['Maintain battery'], tools: ['Multimeter'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-10,000' },
  { code: 'E09', name: 'AC Over Voltage', brand: 'MPP Solar', model: 'All models', severity: 'High', category: 'Grid', description: 'Grid voltage too high.', causes: ['Utility high', 'Poor regulation'], symptoms: ['Transfer to battery'], solution: 'Wait for grid to stabilize.', steps: ['Measure voltage', 'Adjust settings'], prevention: ['Voltage monitoring'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'E10', name: 'PV Over Voltage', brand: 'MPP Solar', model: 'PV models', severity: 'Critical', category: 'PV', description: 'Solar voltage exceeds maximum.', causes: ['Too many panels'], symptoms: ['No solar charging'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper design'], tools: ['DC multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 10,000-40,000' },
  { code: 'E11', name: 'PV Over Current', brand: 'MPP Solar', model: 'PV models', severity: 'High', category: 'PV', description: 'Solar current exceeds MPPT rating.', causes: ['Too many parallel strings'], symptoms: ['MPPT limiting'], solution: 'Reduce array size.', steps: ['Measure current', 'Reconfigure'], prevention: ['Proper design'], tools: ['Clamp meter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 5,000-20,000' },
  { code: 'E12', name: 'EEPROM Error', brand: 'MPP Solar', model: 'All models', severity: 'High', category: 'Internal', description: 'Configuration memory error.', causes: ['Memory failure', 'Corruption'], symptoms: ['Settings lost'], solution: 'Factory reset or service.', steps: ['Reset', 'Update firmware'], prevention: ['Surge protection'], tools: ['USB cable'], estimatedTime: '30 min-1 hour', estimatedCost: 'KES 0-50,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ABB/FIMER INVERTER FAULT CODES (12 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const ABB_FIMER_FAULTS: InverterFault[] = [
  { code: 'E001', name: 'Grid Fault', brand: 'ABB/FIMER', model: 'UNO, TRIO, REACT', severity: 'High', category: 'Grid', description: 'Grid parameters outside range.', causes: ['Grid outage', 'Voltage issue'], symptoms: ['Inverter offline'], solution: 'Wait for grid.', steps: ['Check grid', 'Wait for recovery'], prevention: ['Quality connection'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'E002', name: 'Grid Over Voltage', brand: 'ABB/FIMER', model: 'All models', severity: 'High', category: 'Grid', description: 'Grid voltage exceeds limit.', causes: ['High grid voltage'], symptoms: ['Inverter stops'], solution: 'Contact utility.', steps: ['Measure voltage', 'Document', 'Report'], prevention: ['Monitor grid'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'E003', name: 'Grid Under Voltage', brand: 'ABB/FIMER', model: 'All models', severity: 'High', category: 'Grid', description: 'Grid voltage below minimum.', causes: ['Low utility voltage'], symptoms: ['Inverter stops'], solution: 'Contact utility.', steps: ['Measure voltage'], prevention: ['Grid capacity'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'E006', name: 'Islanding Detected', brand: 'ABB/FIMER', model: 'All models', severity: 'Critical', category: 'Safety', description: 'Potential island condition.', causes: ['Grid disconnection'], symptoms: ['Emergency stop'], solution: 'Wait for grid.', steps: ['Verify grid', 'Wait 5 min'], prevention: ['Proper anti-islanding'], tools: ['Multimeter'], estimatedTime: '5+ min', estimatedCost: 'KES 0' },
  { code: 'E010', name: 'Over Temperature', brand: 'ABB/FIMER', model: 'All models', severity: 'High', category: 'Thermal', description: 'Internal temperature exceeds limit.', causes: ['High ambient', 'Poor ventilation'], symptoms: ['Power derating', 'Shutdown'], solution: 'Improve cooling.', steps: ['Check ventilation', 'Add shading'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-25,000' },
  { code: 'E011', name: 'PV Insulation Fault', brand: 'ABB/FIMER', model: 'All models', severity: 'Critical', category: 'PV', description: 'Low insulation in PV system.', causes: ['Cable damage', 'Water ingress'], symptoms: ['No operation'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Find fault', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E012', name: 'DC Injection High', brand: 'ABB/FIMER', model: 'All models', severity: 'High', category: 'Safety', description: 'DC component in AC output.', causes: ['Internal fault'], symptoms: ['Inverter stops'], solution: 'Professional service.', steps: ['Contact support'], prevention: ['Regular maintenance'], tools: ['Professional'], estimatedTime: 'Professional', estimatedCost: 'KES 50,000+' },
  { code: 'E015', name: 'Arc Fault', brand: 'ABB/FIMER', model: 'AFCI models', severity: 'Critical', category: 'Fire Safety', description: 'Arc fault detected in DC.', causes: ['Loose connection', 'Damaged wire'], symptoms: ['Immediate shutdown'], solution: 'Inspect all DC connections.', steps: ['Full inspection', 'Repair connections'], prevention: ['Quality connections'], tools: ['Visual', 'IR camera'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'E020', name: 'PV Over Voltage', brand: 'ABB/FIMER', model: 'All models', severity: 'Critical', category: 'PV', description: 'PV voltage exceeds maximum.', causes: ['Too many panels'], symptoms: ['No solar'], solution: 'Reduce string voltage.', steps: ['Measure Voc', 'Reconfigure'], prevention: ['Proper design'], tools: ['DC multimeter'], estimatedTime: '1-3 hours', estimatedCost: 'KES 10,000-40,000' },
  { code: 'E025', name: 'Communication Error', brand: 'ABB/FIMER', model: 'All models', severity: 'Medium', category: 'Communication', description: 'External communication lost.', causes: ['Network issue', 'Configuration'], symptoms: ['No monitoring'], solution: 'Check network.', steps: ['Check cables', 'Verify settings'], prevention: ['Stable network'], tools: ['Network tools'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-5,000' },
  { code: 'E004', name: 'Grid Over Frequency', brand: 'ABB/FIMER', model: 'All models', severity: 'Medium', category: 'Grid', description: 'Grid frequency above limit.', causes: ['Grid instability'], symptoms: ['Inverter reduces/stops'], solution: 'Auto recovery.', steps: ['Monitor'], prevention: ['Freq-Watt settings'], tools: ['Power analyzer'], estimatedTime: 'Automatic', estimatedCost: 'KES 0' },
  { code: 'E005', name: 'Grid Under Frequency', brand: 'ABB/FIMER', model: 'All models', severity: 'Medium', category: 'Grid', description: 'Grid frequency below limit.', causes: ['Grid overload'], symptoms: ['Inverter stops'], solution: 'Auto recovery.', steps: ['Wait'], prevention: ['Grid monitoring'], tools: ['Power analyzer'], estimatedTime: 'Automatic', estimatedCost: 'KES 0' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SCHNEIDER ELECTRIC INVERTER FAULT CODES (10 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const SCHNEIDER_FAULTS: InverterFault[] = [
  { code: 'W001', name: 'Grid Lost', brand: 'Schneider Electric', model: 'Conext XW+, SW', severity: 'High', category: 'Grid', description: 'AC grid connection lost.', causes: ['Power outage', 'Grid fault'], symptoms: ['Transfer to battery'], solution: 'Wait for grid.', steps: ['Check grid', 'Check breaker'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'W002', name: 'AC Overload', brand: 'Schneider Electric', model: 'Conext XW+, SW', severity: 'High', category: 'Output', description: 'AC output overloaded.', causes: ['Excessive load', 'Motor inrush'], symptoms: ['Overload warning', 'Limiting'], solution: 'Reduce load.', steps: ['Check load', 'Remove non-essential'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'W003', name: 'Battery Low', brand: 'Schneider Electric', model: 'Conext XW+, SW', severity: 'High', category: 'Battery', description: 'Battery voltage approaching cutoff.', causes: ['Depleted batteries', 'High load'], symptoms: ['Low battery warning'], solution: 'Reduce load, charge.', steps: ['Reduce loads', 'Charge'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'W004', name: 'Over Temperature', brand: 'Schneider Electric', model: 'All models', severity: 'High', category: 'Thermal', description: 'Unit temperature exceeds limit.', causes: ['High ambient', 'Poor ventilation'], symptoms: ['Power limiting', 'Shutdown'], solution: 'Improve cooling.', steps: ['Clear ventilation', 'Check fan'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-25,000' },
  { code: 'W010', name: 'Ground Fault', brand: 'Schneider Electric', model: 'All models', severity: 'Critical', category: 'Safety', description: 'Ground fault detected.', causes: ['Insulation failure', 'Water ingress'], symptoms: ['Shutdown'], solution: 'Find and repair fault.', steps: ['Test insulation', 'Repair fault'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F001', name: 'Inverter Fault', brand: 'Schneider Electric', model: 'All models', severity: 'Critical', category: 'Inverter', description: 'Critical inverter fault.', causes: ['Component failure', 'Surge damage'], symptoms: ['No output', 'Fault LED'], solution: 'Professional service.', steps: ['Contact support'], prevention: ['Surge protection'], tools: ['None'], estimatedTime: 'Professional', estimatedCost: 'KES 50,000-200,000' },
  { code: 'F002', name: 'DC Over Voltage', brand: 'Schneider Electric', model: 'Conext XW+, SW', severity: 'Critical', category: 'Battery', description: 'Battery voltage exceeds limit.', causes: ['Wrong settings', 'External charger'], symptoms: ['Charging stops', 'Alarm'], solution: 'Correct settings.', steps: ['Verify settings', 'Match battery'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'F003', name: 'PV Ground Fault', brand: 'Schneider Electric', model: 'Conext RL, CL', severity: 'Critical', category: 'PV', description: 'Ground fault in PV array.', causes: ['Cable damage', 'Water ingress'], symptoms: ['No PV production'], solution: 'Locate and repair fault.', steps: ['Test insulation', 'Repair'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'F010', name: 'Arc Fault', brand: 'Schneider Electric', model: 'AFCI models', severity: 'Critical', category: 'Fire Safety', description: 'Arc fault detected.', causes: ['Loose connection', 'Damaged wire'], symptoms: ['Immediate shutdown'], solution: 'Full inspection required.', steps: ['Inspect all connections', 'Repair'], prevention: ['Quality connections'], tools: ['Visual', 'IR camera'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'W005', name: 'Fan Fault', brand: 'Schneider Electric', model: 'Models with fan', severity: 'Medium', category: 'Hardware', description: 'Cooling fan not operating.', causes: ['Fan failure', 'Obstruction'], symptoms: ['Overheating risk'], solution: 'Replace fan.', steps: ['Check fan', 'Replace'], prevention: ['Regular cleaning'], tools: ['Replacement fan'], estimatedTime: '1-2 hours', estimatedCost: 'KES 8,000-25,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// OUTBACK POWER INVERTER FAULT CODES (10 Codes)
// ═══════════════════════════════════════════════════════════════════════════════

export const OUTBACK_FAULTS: InverterFault[] = [
  { code: 'OB-001', name: 'AC Input Fault', brand: 'Outback Power', model: 'Radian, FX, Skybox', severity: 'High', category: 'Grid', description: 'AC input outside parameters.', causes: ['Grid outage', 'Voltage issue'], symptoms: ['Operating on battery'], solution: 'Wait for grid.', steps: ['Check grid', 'Check connections'], prevention: ['Surge protection'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0' },
  { code: 'OB-002', name: 'Backfeed Fault', brand: 'Outback Power', model: 'Radian, FX', severity: 'Critical', category: 'Safety', description: 'Potential backfeed condition.', causes: ['Incorrect wiring', 'Transfer switch failure'], symptoms: ['Emergency shutdown'], solution: 'Correct wiring.', steps: ['Verify wiring', 'Check transfer switch'], prevention: ['Correct installation'], tools: ['Wiring diagram'], estimatedTime: '1-2 hours', estimatedCost: 'KES 5,000-25,000' },
  { code: 'OB-003', name: 'High Battery', brand: 'Outback Power', model: 'All models', severity: 'Critical', category: 'Battery', description: 'Battery voltage exceeds limit.', causes: ['Wrong settings', 'Multiple chargers'], symptoms: ['Charging stops', 'Alarm'], solution: 'Correct settings.', steps: ['Verify settings', 'Remove extra chargers'], prevention: ['Correct configuration'], tools: ['Multimeter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'OB-004', name: 'Low Battery', brand: 'Outback Power', model: 'All models', severity: 'High', category: 'Battery', description: 'Battery voltage at low limit.', causes: ['Depleted batteries', 'High load'], symptoms: ['Low battery alarm'], solution: 'Reduce load, charge.', steps: ['Check voltage', 'Charge'], prevention: ['Regular maintenance'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0-300,000' },
  { code: 'OB-005', name: 'Over Temperature', brand: 'Outback Power', model: 'All models', severity: 'High', category: 'Thermal', description: 'Internal temperature too high.', causes: ['High ambient', 'Heavy load'], symptoms: ['Power reduction', 'Alarm'], solution: 'Improve cooling.', steps: ['Clear vents', 'Reduce load'], prevention: ['Proper installation'], tools: ['Thermometer'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-25,000' },
  { code: 'OB-006', name: 'Overload', brand: 'Outback Power', model: 'All models', severity: 'High', category: 'Output', description: 'Load exceeds rated capacity.', causes: ['Excessive load', 'Motor inrush'], symptoms: ['Overload alarm', 'Shutdown'], solution: 'Reduce load.', steps: ['Remove loads', 'Reconnect one at a time'], prevention: ['Proper sizing'], tools: ['Clamp meter'], estimatedTime: '15-30 min', estimatedCost: 'KES 0' },
  { code: 'OB-007', name: 'Ground Fault', brand: 'Outback Power', model: 'All models', severity: 'Critical', category: 'Safety', description: 'Ground fault detected.', causes: ['Insulation failure', 'Wiring fault'], symptoms: ['Shutdown'], solution: 'Find and repair fault.', steps: ['Test insulation', 'Repair fault'], prevention: ['Quality installation'], tools: ['Megger'], estimatedTime: '2-4 hours', estimatedCost: 'KES 10,000-50,000' },
  { code: 'OB-010', name: 'Stacking Error', brand: 'Outback Power', model: 'FX, Radian', severity: 'High', category: 'System', description: 'Stacked inverter communication error.', causes: ['Communication cable', 'Configuration error'], symptoms: ['Unit offline', 'Unequal operation'], solution: 'Repair communication.', steps: ['Check cables', 'Verify addresses'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '1-2 hours', estimatedCost: 'KES 0-20,000' },
  { code: 'OB-011', name: 'MATE Comm Error', brand: 'Outback Power', model: 'Systems with MATE', severity: 'Medium', category: 'Communication', description: 'Communication with MATE lost.', causes: ['Cable issue', 'MATE fault'], symptoms: ['No display data'], solution: 'Repair communication.', steps: ['Check cables', 'Power cycle'], prevention: ['Secure connections'], tools: ['Multimeter'], estimatedTime: '30-60 min', estimatedCost: 'KES 0-15,000' },
  { code: 'OB-012', name: 'FLEXmax Error', brand: 'Outback Power', model: 'Systems with FLEXmax', severity: 'High', category: 'Charging', description: 'FLEXmax charge controller fault.', causes: ['Over voltage', 'Communication error'], symptoms: ['No solar charging'], solution: 'Check controller.', steps: ['Check PV voltage', 'Check communication'], prevention: ['Proper sizing'], tools: ['Multimeter'], estimatedTime: 'Varies', estimatedCost: 'KES 0-50,000' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORT ALL INVERTER FAULTS - PART 3
// ═══════════════════════════════════════════════════════════════════════════════

export const ALL_INVERTER_FAULTS_PART3: InverterFault[] = [
  ...VOLTRONIC_AXPERT_FAULTS,
  ...MUST_SOLAR_FAULTS,
  ...MPP_SOLAR_FAULTS,
  ...ABB_FIMER_FAULTS,
  ...SCHNEIDER_FAULTS,
  ...OUTBACK_FAULTS
];

export const BRANDS_PART3 = ['Voltronic/Axpert', 'Must Solar', 'MPP Solar', 'ABB/FIMER', 'Schneider Electric', 'Outback Power'];

export const FAULT_COUNT_PART3 = ALL_INVERTER_FAULTS_PART3.length;
