/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * HVAC BIBLE - COMPREHENSIVE DATA
 * Repair Manuals, Parts Catalogue, Maintenance Schedules, Extended Fault Codes
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// ═══════════════════════════════════════════════════════════════════════════════
// EXTENDED FAULT CODES DATABASE (200+)
// ═══════════════════════════════════════════════════════════════════════════════
export const HVAC_FAULT_CODES = [
  // COMPRESSOR FAULTS (C001-C050)
  { code: 'C001', name: 'Compressor Not Starting', category: 'Compressor', severity: 'Critical', system: 'All',
    symptoms: ['No cooling', 'Compressor silent', 'Circuit breaker trips', 'Overload trips'],
    causes: ['Electrical supply issue', 'Burnt motor windings', 'Locked rotor', 'Faulty capacitor', 'Control board failure'],
    diagnostics: ['Check voltage at compressor terminals', 'Measure winding resistance', 'Check capacitor with meter', 'Check control signals'],
    repair: ['Replace capacitor', 'Replace contactor', 'Replace compressor if windings bad', 'Check/replace control board'],
    parts: ['Compressor', 'Run capacitor', 'Start capacitor', 'Contactor'],
    costKES: '5,000 - 150,000', time: '2-8 hours' },
  { code: 'C002', name: 'Compressor Short Cycling', category: 'Compressor', severity: 'High', system: 'All',
    symptoms: ['Compressor starts/stops frequently', 'Poor cooling', 'High energy bills', 'Compressor overheating'],
    causes: ['Low refrigerant', 'Dirty condenser', 'Faulty thermostat', 'Oversized unit', 'Restricted airflow'],
    diagnostics: ['Check superheat/subcooling', 'Inspect condenser coil', 'Check thermostat operation', 'Measure pressures'],
    repair: ['Add refrigerant if low', 'Clean condenser', 'Replace thermostat', 'Check sizing'],
    parts: ['Refrigerant', 'Thermostat', 'Pressure switches'],
    costKES: '3,000 - 30,000', time: '1-4 hours' },
  { code: 'C003', name: 'Compressor Overheating', category: 'Compressor', severity: 'High', system: 'All',
    symptoms: ['Compressor hot to touch', 'Thermal overload tripping', 'Reduced cooling', 'Burnt smell'],
    causes: ['Low refrigerant', 'High head pressure', 'Poor ventilation', 'Dirty coils', 'Motor winding issues'],
    diagnostics: ['Check discharge temperature', 'Measure head pressure', 'Check suction superheat', 'Inspect coils'],
    repair: ['Charge refrigerant', 'Clean coils', 'Improve ventilation', 'Replace compressor if windings damaged'],
    parts: ['Refrigerant', 'Thermal overload', 'Fan motor'],
    costKES: '5,000 - 100,000', time: '2-6 hours' },
  { code: 'C004', name: 'Compressor Running Continuously', category: 'Compressor', severity: 'Medium', system: 'All',
    symptoms: ['Never reaches setpoint', 'High energy usage', 'Ice on coil', 'Compressor never cycles off'],
    causes: ['Undersized unit', 'Low refrigerant', 'Air leaks in space', 'Thermostat calibration', 'High ambient'],
    diagnostics: ['Calculate cooling load', 'Check refrigerant charge', 'Inspect insulation', 'Calibrate thermostat'],
    repair: ['Address load issues', 'Recharge system', 'Seal air leaks', 'Recalibrate thermostat'],
    parts: ['Thermostat', 'Refrigerant', 'Insulation'],
    costKES: '2,000 - 50,000', time: '1-4 hours' },
  { code: 'C005', name: 'Compressor Mechanical Noise', category: 'Compressor', severity: 'High', system: 'All',
    symptoms: ['Knocking sound', 'Rattling', 'Vibration', 'Grinding noise'],
    causes: ['Liquid slugging', 'Loose mounting', 'Internal wear', 'Bearing failure', 'Broken valves'],
    diagnostics: ['Listen with stethoscope', 'Check mounting bolts', 'Measure vibration', 'Oil analysis'],
    repair: ['Tighten mounts', 'Add crankcase heater', 'Replace compressor if internal damage'],
    parts: ['Compressor', 'Mounting grommets', 'Crankcase heater'],
    costKES: '1,000 - 120,000', time: '1-8 hours' },

  // REFRIGERANT FAULTS (R001-R030)
  { code: 'R001', name: 'Low Refrigerant Charge', category: 'Refrigerant', severity: 'High', system: 'All',
    symptoms: ['Warm air from vents', 'Ice on evaporator', 'Hissing sound', 'Long run times'],
    causes: ['Leak in system', 'Poor installation', 'Vibration damage', 'Corrosion', 'Poor joints'],
    diagnostics: ['Check pressures', 'Measure superheat (high)', 'Leak detection', 'Visual inspection'],
    repair: ['Find and repair leak', 'Evacuate and recharge', 'Replace damaged component'],
    parts: ['Refrigerant', 'Leak repair kit', 'Braze materials'],
    costKES: '5,000 - 40,000', time: '2-6 hours' },
  { code: 'R002', name: 'Refrigerant Overcharge', category: 'Refrigerant', severity: 'High', system: 'All',
    symptoms: ['High head pressure', 'Poor cooling', 'Compressor overheating', 'High energy use'],
    causes: ['Improper charging', 'Recovery without weighing', 'Liquid added not vapor'],
    diagnostics: ['Check pressures', 'Measure subcooling (high)', 'Calculate charge'],
    repair: ['Recover excess refrigerant', 'Weigh in correct charge'],
    parts: ['Recovery cylinder'],
    costKES: '3,000 - 15,000', time: '1-3 hours' },
  { code: 'R003', name: 'Refrigerant Contamination', category: 'Refrigerant', severity: 'Critical', system: 'All',
    symptoms: ['Abnormal pressures', 'Poor performance', 'Compressor damage', 'Color change in sight glass'],
    causes: ['Mixed refrigerants', 'Moisture ingress', 'Air in system', 'Acid formation', 'Wrong oil'],
    diagnostics: ['Refrigerant identifier test', 'Acid test', 'Moisture indicator', 'Oil analysis'],
    repair: ['Recover all refrigerant', 'Triple evacuation', 'Flush system', 'Replace filter drier', 'Recharge with correct refrigerant'],
    parts: ['New refrigerant', 'Filter drier', 'POE oil', 'Flush kit'],
    costKES: '15,000 - 80,000', time: '4-12 hours' },
  { code: 'R004', name: 'Non-Condensables (Air) in System', category: 'Refrigerant', severity: 'High', system: 'All',
    symptoms: ['High head pressure', 'Poor cooling', 'Subcooling varies', 'Bubbles in sight glass'],
    causes: ['Poor evacuation', 'Leak allowed air entry', 'Contaminated refrigerant', 'Loose connections'],
    diagnostics: ['Compare actual vs theoretical head pressure', 'Purge test', 'Check vacuum level'],
    repair: ['Recover refrigerant', 'Leak test', 'Deep vacuum', 'Recharge'],
    parts: ['Refrigerant', 'Filter drier'],
    costKES: '5,000 - 25,000', time: '2-6 hours' },

  // ELECTRICAL FAULTS (E001-E040)
  { code: 'E001', name: 'No Power to Unit', category: 'Electrical', severity: 'Critical', system: 'All',
    symptoms: ['Unit dead', 'No display', 'No response to controls', 'Breaker tripped'],
    causes: ['Power supply off', 'Breaker tripped', 'Fuse blown', 'Disconnect switch off', 'Wiring fault'],
    diagnostics: ['Check voltage at disconnect', 'Check breaker/fuse', 'Check control transformer'],
    repair: ['Reset breaker', 'Replace fuse', 'Repair wiring', 'Replace transformer'],
    parts: ['Fuses', 'Control transformer', 'Wiring'],
    costKES: '500 - 15,000', time: '0.5-3 hours' },
  { code: 'E002', name: 'Contactor Not Pulling In', category: 'Electrical', severity: 'High', system: 'All',
    symptoms: ['Compressor not starting', 'Outdoor fan not running', 'Control voltage present'],
    causes: ['Faulty contactor', 'No control signal', 'Low voltage', 'Burnt coil', 'Pitted contacts'],
    diagnostics: ['Check coil voltage', 'Manually push contactor', 'Measure coil resistance', 'Check thermostat signal'],
    repair: ['Replace contactor', 'Repair control circuit', 'Replace thermostat'],
    parts: ['Contactor', 'Control relay'],
    costKES: '2,000 - 10,000', time: '1-2 hours' },
  { code: 'E003', name: 'Capacitor Failure', category: 'Electrical', severity: 'High', system: 'All',
    symptoms: ['Motor hums but wont start', 'Motor runs slow', 'Motor overheats', 'Swollen capacitor'],
    causes: ['Age', 'Overheating', 'Power surges', 'Wrong rating installed', 'Short circuit'],
    diagnostics: ['Visual inspection', 'Capacitance test', 'Check for bulging or leaking'],
    repair: ['Replace capacitor with correct rating'],
    parts: ['Run capacitor', 'Start capacitor', 'Hard start kit'],
    costKES: '1,500 - 8,000', time: '0.5-1 hour' },
  { code: 'E004', name: 'Control Board Failure', category: 'Electrical', severity: 'Critical', system: 'All',
    symptoms: ['Erratic operation', 'No response to inputs', 'Display errors', 'Multiple fault codes'],
    causes: ['Power surge', 'Moisture damage', 'Component failure', 'Manufacturing defect', 'Age'],
    diagnostics: ['Visual inspection for burnt components', 'Check input/output signals', 'Check power supply voltages'],
    repair: ['Replace control board', 'Repair if minor component issue'],
    parts: ['Main PCB', 'Display board', 'Power supply board'],
    costKES: '15,000 - 80,000', time: '2-4 hours' },
  { code: 'E005', name: 'Inverter/VFD Fault', category: 'Electrical', severity: 'Critical', system: 'Inverter Units',
    symptoms: ['Error code displayed', 'Compressor not running at variable speed', 'Overcurrent alarm'],
    causes: ['IGBT failure', 'DC bus fault', 'Overcurrent', 'Overvoltage', 'Communication error'],
    diagnostics: ['Read fault code', 'Check DC bus voltage', 'Check IGBT module', 'Communication test'],
    repair: ['Reset and retry', 'Replace IGBT module', 'Replace inverter board'],
    parts: ['IGBT module', 'Inverter board', 'Capacitors'],
    costKES: '30,000 - 150,000', time: '4-8 hours' },

  // FAN MOTOR FAULTS (F001-F025)
  { code: 'F001', name: 'Indoor Fan Not Running', category: 'Fan', severity: 'High', system: 'Split/Package',
    symptoms: ['No air from vents', 'Evaporator icing', 'High head pressure', 'Motor hot'],
    causes: ['Capacitor failure', 'Motor failure', 'No power to motor', 'Control board issue', 'Relay failure'],
    diagnostics: ['Check capacitor', 'Check voltage to motor', 'Check motor windings', 'Spin motor manually'],
    repair: ['Replace capacitor', 'Replace fan motor', 'Replace relay/board'],
    parts: ['Indoor fan motor', 'Capacitor', 'Fan blade', 'Relay'],
    costKES: '3,000 - 25,000', time: '1-3 hours' },
  { code: 'F002', name: 'Outdoor Fan Not Running', category: 'Fan', severity: 'Critical', system: 'Split/Package',
    symptoms: ['Unit tripping on high pressure', 'Compressor overheating', 'Poor cooling', 'No condenser airflow'],
    causes: ['Capacitor failure', 'Motor failure', 'Contactor issue', 'Fan blade broken', 'Motor seized'],
    diagnostics: ['Check capacitor', 'Check voltage to motor', 'Check motor windings', 'Spin motor manually'],
    repair: ['Replace capacitor', 'Replace fan motor', 'Replace blade'],
    parts: ['Outdoor fan motor', 'Capacitor', 'Fan blade'],
    costKES: '3,000 - 30,000', time: '1-3 hours' },
  { code: 'F003', name: 'Fan Running Backwards', category: 'Fan', severity: 'High', system: 'Three Phase',
    symptoms: ['Very poor airflow', 'Motor overheating', 'No cooling', 'Wrong phase sequence'],
    causes: ['Incorrect phase sequence', 'Wiring error after maintenance', 'Phase reversal at supply'],
    diagnostics: ['Check phase rotation', 'Compare to nameplate', 'Check rotation direction'],
    repair: ['Swap any two phases', 'Correct wiring'],
    parts: ['Phase sequence relay'],
    costKES: '2,000 - 10,000', time: '0.5-1 hour' },
  { code: 'F004', name: 'Fan Vibration/Noise', category: 'Fan', severity: 'Medium', system: 'All',
    symptoms: ['Rattling', 'Vibration', 'Bearing noise', 'Squealing', 'Rumbling'],
    causes: ['Unbalanced blade', 'Loose mounting', 'Bearing wear', 'Blade damage', 'Foreign object'],
    diagnostics: ['Visual inspection', 'Check blade balance', 'Check bearings', 'Check mounting'],
    repair: ['Balance or replace blade', 'Replace bearings', 'Tighten mounts', 'Remove debris'],
    parts: ['Fan blade', 'Bearings', 'Motor', 'Mounting hardware'],
    costKES: '1,000 - 15,000', time: '1-3 hours' },

  // SENSOR/CONTROL FAULTS (S001-S030)
  { code: 'S001', name: 'Room Temperature Sensor Fault', category: 'Sensors', severity: 'High', system: 'All',
    symptoms: ['Wrong temperature reading', 'Unit wont reach setpoint', 'Erratic operation', 'Error code'],
    causes: ['Sensor failure', 'Wiring issue', 'Wrong sensor type', 'Sensor out of position', 'Contamination'],
    diagnostics: ['Measure sensor resistance', 'Compare to temperature', 'Check wiring', 'Check sensor position'],
    repair: ['Replace sensor', 'Correct wiring', 'Reposition sensor'],
    parts: ['Room temperature sensor', 'Thermistor'],
    costKES: '1,000 - 5,000', time: '0.5-2 hours' },
  { code: 'S002', name: 'Coil Temperature Sensor Fault', category: 'Sensors', severity: 'High', system: 'All',
    symptoms: ['Defrost issues', 'Compressor cycling', 'Error code', 'Poor temperature control'],
    causes: ['Sensor failure', 'Detached from coil', 'Wiring issue', 'Wrong sensor type'],
    diagnostics: ['Measure sensor resistance', 'Check attachment to coil', 'Check wiring'],
    repair: ['Replace sensor', 'Reattach to coil', 'Correct wiring'],
    parts: ['Coil sensor', 'Thermal paste'],
    costKES: '1,000 - 5,000', time: '0.5-2 hours' },
  { code: 'S003', name: 'Pressure Switch Fault', category: 'Sensors', severity: 'High', system: 'All',
    symptoms: ['Unit not starting', 'Frequent trips', 'Error code', 'Compressor protection active'],
    causes: ['Switch failure', 'Incorrect setting', 'Wiring issue', 'Actual pressure problem'],
    diagnostics: ['Check actual pressure', 'Check switch setting', 'Bypass test (temporary)'],
    repair: ['Adjust setting', 'Replace switch', 'Fix pressure issue'],
    parts: ['High pressure switch', 'Low pressure switch'],
    costKES: '2,000 - 8,000', time: '1-2 hours' },
  { code: 'S004', name: 'Thermostat/Controller Fault', category: 'Sensors', severity: 'High', system: 'All',
    symptoms: ['No control', 'Wrong temperature display', 'Buttons not working', 'Display blank'],
    causes: ['Battery dead (if applicable)', 'Wiring issue', 'Controller failure', 'Programming error'],
    diagnostics: ['Check power to controller', 'Check batteries', 'Reset to factory defaults', 'Check wiring'],
    repair: ['Replace batteries', 'Replace controller', 'Reprogram', 'Fix wiring'],
    parts: ['Thermostat', 'Controller', 'Batteries', 'Wiring'],
    costKES: '2,000 - 30,000', time: '0.5-2 hours' },

  // AIRFLOW FAULTS (A001-A025)
  { code: 'A001', name: 'Dirty/Clogged Filter', category: 'Airflow', severity: 'Low', system: 'All',
    symptoms: ['Reduced airflow', 'Poor cooling', 'Ice on coil', 'High energy use', 'Dusty air'],
    causes: ['Lack of maintenance', 'High dust environment', 'Wrong filter type', 'Filter installed backwards'],
    diagnostics: ['Visual inspection', 'Check pressure drop', 'Check coil condition'],
    repair: ['Clean or replace filter', 'Establish maintenance schedule'],
    parts: ['Air filter'],
    costKES: '500 - 5,000', time: '0.25-0.5 hours' },
  { code: 'A002', name: 'Evaporator Coil Frozen', category: 'Airflow', severity: 'High', system: 'All',
    symptoms: ['Ice on coil', 'No cooling', 'Water leaks when thawing', 'Compressor short cycling'],
    causes: ['Low refrigerant', 'Dirty filter', 'Fan failure', 'Low airflow', 'Metering device issue'],
    diagnostics: ['Check superheat', 'Check airflow', 'Inspect filter', 'Check fan operation'],
    repair: ['Defrost coil', 'Fix root cause (filter, fan, refrigerant)'],
    parts: ['Filter', 'Fan motor', 'Refrigerant', 'TXV'],
    costKES: '1,000 - 30,000', time: '1-4 hours' },
  { code: 'A003', name: 'Condenser Coil Dirty', category: 'Airflow', severity: 'High', system: 'All',
    symptoms: ['High head pressure', 'Poor cooling', 'Compressor overheating', 'High energy use'],
    causes: ['Outdoor debris', 'Dust buildup', 'Cottonwood seeds', 'Lack of maintenance'],
    diagnostics: ['Visual inspection', 'Check head pressure', 'Check airflow through coil'],
    repair: ['Clean coil with pressure washer and coil cleaner'],
    parts: ['Coil cleaner', 'Coil guard (prevention)'],
    costKES: '2,000 - 8,000', time: '1-2 hours' },
  { code: 'A004', name: 'Ductwork Leak', category: 'Airflow', severity: 'Medium', system: 'Ducted Systems',
    symptoms: ['Reduced airflow at registers', 'Hot/cold spots', 'High energy use', 'Dusty air'],
    causes: ['Poor installation', 'Age/deterioration', 'Pest damage', 'Settling', 'Vibration'],
    diagnostics: ['Duct blaster test', 'Visual inspection', 'Smoke test', 'IR camera'],
    repair: ['Seal joints with mastic', 'Replace damaged sections', 'Add insulation'],
    parts: ['Mastic sealant', 'Duct tape (metal)', 'Insulation', 'Duct sections'],
    costKES: '5,000 - 50,000', time: '2-8 hours' },

  // DRAINAGE FAULTS (D001-D015)
  { code: 'D001', name: 'Drain Pan Overflow', category: 'Drainage', severity: 'High', system: 'All',
    symptoms: ['Water leaks', 'Musty smell', 'Ceiling stains', 'Float switch tripping'],
    causes: ['Clogged drain line', 'Blocked drain pan', 'Slime buildup', 'Improper slope', 'Pan cracked'],
    diagnostics: ['Inspect drain pan', 'Check drain line', 'Check float switch', 'Check slope'],
    repair: ['Clear drain line', 'Clean pan', 'Correct slope', 'Replace pan if cracked'],
    parts: ['Drain pan', 'Float switch', 'Drain line', 'Pan tablets'],
    costKES: '1,000 - 15,000', time: '0.5-3 hours' },
  { code: 'D002', name: 'Condensate Pump Failure', category: 'Drainage', severity: 'High', system: 'All',
    symptoms: ['Water overflow', 'Unit shutting down', 'Pump not running', 'Pump running constantly'],
    causes: ['Pump motor failure', 'Float switch stuck', 'Blocked discharge', 'Power issue'],
    diagnostics: ['Check pump operation', 'Check float switch', 'Check discharge line', 'Check power'],
    repair: ['Clean float switch', 'Clear blockage', 'Replace pump'],
    parts: ['Condensate pump', 'Float switch', 'Tubing'],
    costKES: '5,000 - 25,000', time: '1-3 hours' },

  // VRV/VRF SPECIFIC FAULTS (V001-V030)
  { code: 'V001', name: 'Communication Error', category: 'VRV/VRF', severity: 'High', system: 'VRV/VRF',
    symptoms: ['Indoor unit offline', 'Error code displayed', 'No communication with central controller'],
    causes: ['Wiring fault', 'Address conflict', 'Termination missing', 'Board failure', 'Noise interference'],
    diagnostics: ['Check wiring continuity', 'Check addresses', 'Check termination resistor', 'Check communication voltage'],
    repair: ['Correct wiring', 'Reset addresses', 'Add/remove termination', 'Replace board'],
    parts: ['Communication cable', 'PCB board', 'Termination resistor'],
    costKES: '5,000 - 50,000', time: '1-4 hours' },
  { code: 'V002', name: 'Oil Return Fault', category: 'VRV/VRF', severity: 'Critical', system: 'VRV/VRF',
    symptoms: ['Compressor damage', 'Oil level low', 'Oil return alarm', 'Bearing noise'],
    causes: ['Long piping runs', 'Low load operation', 'Incorrect piping slope', 'Oil level sensors'],
    diagnostics: ['Check oil level', 'Check piping installation', 'Force oil recovery mode'],
    repair: ['Run oil recovery', 'Correct piping', 'Add oil if low', 'Check traps'],
    parts: ['Refrigeration oil', 'Oil separator'],
    costKES: '10,000 - 80,000', time: '2-8 hours' },
  { code: 'V003', name: 'Refrigerant Imbalance', category: 'VRV/VRF', severity: 'High', system: 'VRV/VRF',
    symptoms: ['Some units not cooling', 'High superheat on some circuits', 'Uneven temperature'],
    causes: ['Improper commissioning', 'Leak in system', 'EXV malfunction', 'Piping issues'],
    diagnostics: ['Check superheat each circuit', 'Run auto charge test', 'Check EXV operation'],
    repair: ['Recommission system', 'Fix leaks', 'Replace faulty EXV'],
    parts: ['Refrigerant', 'EXV', 'Piping components'],
    costKES: '15,000 - 100,000', time: '4-12 hours' },

  // CHILLER SPECIFIC FAULTS (CH001-CH025)
  { code: 'CH001', name: 'Low Evaporator Water Flow', category: 'Chiller', severity: 'Critical', system: 'Chillers',
    symptoms: ['Chiller trips', 'Low delta T', 'Flow switch alarm', 'Freeze protection alarm'],
    causes: ['Pump failure', 'Valve closed', 'Strainer blocked', 'Air in system', 'Pipe blockage'],
    diagnostics: ['Check pump operation', 'Check valve positions', 'Check strainer', 'Verify flow rate'],
    repair: ['Start pump', 'Open valves', 'Clean strainer', 'Bleed air', 'Clear blockage'],
    parts: ['Pump', 'Strainer', 'Flow switch', 'Valves'],
    costKES: '10,000 - 200,000', time: '2-12 hours' },
  { code: 'CH002', name: 'High Condenser Water Temperature', category: 'Chiller', severity: 'High', system: 'Water-Cooled Chillers',
    symptoms: ['High head pressure', 'Chiller de-rating', 'Approach temperature high'],
    causes: ['Cooling tower issue', 'Tube fouling', 'High ambient', 'Pump issue', 'Valve issue'],
    diagnostics: ['Check cooling tower', 'Check condenser approach', 'Check flow rate'],
    repair: ['Service cooling tower', 'Clean condenser tubes', 'Service pumps'],
    parts: ['Tube cleaning equipment', 'Pump parts', 'Cooling tower parts'],
    costKES: '20,000 - 300,000', time: '4-24 hours' },
  { code: 'CH003', name: 'Oil Pressure Differential Low', category: 'Chiller', severity: 'Critical', system: 'Screw/Centrifugal Chillers',
    symptoms: ['Oil pressure alarm', 'Compressor trips', 'Bearing damage risk'],
    causes: ['Oil pump failure', 'Low oil level', 'Clogged oil filter', 'Oil heater failure', 'Refrigerant in oil'],
    diagnostics: ['Check oil level', 'Check oil pressure', 'Check oil temperature', 'Check filter DP'],
    repair: ['Replace oil filter', 'Add oil', 'Repair pump', 'Replace oil heater'],
    parts: ['Oil filter', 'Oil', 'Oil pump', 'Oil heater'],
    costKES: '15,000 - 150,000', time: '2-8 hours' },

  // REFRIGERATION FAULTS (RF001-RF025)
  { code: 'RF001', name: 'Defrost Failure', category: 'Refrigeration', severity: 'High', system: 'Refrigeration',
    symptoms: ['Ice buildup on coil', 'Poor cooling', 'High suction pressure', 'Compressor short cycling'],
    causes: ['Defrost timer failure', 'Defrost heater failure', 'Termination sensor failure', 'Defrost relay'],
    diagnostics: ['Check defrost timer', 'Check heater continuity', 'Check termination sensor', 'Manual defrost test'],
    repair: ['Replace timer', 'Replace heater', 'Replace sensor', 'Replace relay'],
    parts: ['Defrost timer', 'Defrost heater', 'Termination thermostat', 'Defrost relay'],
    costKES: '3,000 - 25,000', time: '1-4 hours' },
  { code: 'RF002', name: 'Door Seal Failure', category: 'Refrigeration', severity: 'Medium', system: 'Refrigeration',
    symptoms: ['Frost buildup', 'Temperature fluctuation', 'Compressor running constantly', 'Ice on door frame'],
    causes: ['Worn gasket', 'Misaligned door', 'Damaged gasket', 'Debris in seal'],
    diagnostics: ['Dollar bill test', 'Visual inspection', 'Check door alignment', 'Check hinges'],
    repair: ['Replace gasket', 'Adjust door', 'Clean gasket', 'Replace hinges'],
    parts: ['Door gasket', 'Hinges', 'Door closer'],
    costKES: '5,000 - 30,000', time: '1-3 hours' },
  { code: 'RF003', name: 'Expansion Valve Problem', category: 'Refrigeration', severity: 'High', system: 'Refrigeration',
    symptoms: ['Low superheat', 'High superheat', 'Flooding', 'Starving evaporator', 'Hunting'],
    causes: ['Bulb placement', 'Wrong valve size', 'Valve stuck', 'Moisture in system', 'Loss of charge'],
    diagnostics: ['Measure superheat', 'Check bulb attachment', 'Check valve operation'],
    repair: ['Adjust superheat', 'Reposition bulb', 'Replace valve', 'Change drier'],
    parts: ['TXV', 'Bulb insulation', 'Filter drier'],
    costKES: '8,000 - 40,000', time: '2-6 hours' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// REPAIR MANUALS
// ═══════════════════════════════════════════════════════════════════════════════
export const HVAC_REPAIR_MANUALS = [
  {
    id: 'rm-hvac-001',
    title: 'Split AC Refrigerant Recharge Procedure',
    category: 'Refrigerant Service',
    difficulty: 'Medium',
    timeRequired: '1-2 hours',
    tools: ['Manifold gauge set', 'Refrigerant scale', 'Vacuum pump', 'Refrigerant cylinder', 'Leak detector', 'PPE'],
    safetyWarnings: [
      'Always wear safety glasses and gloves',
      'Work in well-ventilated area',
      'Never release refrigerant to atmosphere (illegal)',
      'High pressure - use caution',
      'Recover all refrigerant before opening system',
    ],
    steps: [
      { step: 1, title: 'Verify Low Charge', description: 'Confirm low refrigerant by checking pressures and superheat', details: 'Connect gauges, run unit, measure pressures. Low suction with high superheat indicates low charge.', caution: 'Do not add refrigerant without confirming low charge' },
      { step: 2, title: 'Leak Detection', description: 'Find the leak before adding refrigerant', details: 'Use electronic leak detector or soap bubbles. Check all joints, coils, valves.', caution: 'Must find leak or system will lose charge again' },
      { step: 3, title: 'Recover Remaining Refrigerant', description: 'Recover any refrigerant left in system', details: 'Connect recovery unit, recover to proper cylinder.', caution: 'Never vent refrigerant' },
      { step: 4, title: 'Repair Leak', description: 'Fix the identified leak', details: 'Braze leak point, replace component if needed, pressure test with nitrogen.', caution: 'Always nitrogen test after brazing' },
      { step: 5, title: 'Evacuate System', description: 'Pull deep vacuum to remove moisture', details: 'Connect vacuum pump, pull to 500 microns, hold for 15 minutes.', caution: 'Never shortcut evacuation - moisture causes problems' },
      { step: 6, title: 'Weigh In Charge', description: 'Add correct amount of refrigerant', details: 'Check nameplate for charge amount. Add liquid to high side (unit off) or vapor to low side (unit running).', caution: 'Never overcharge - use scale' },
      { step: 7, title: 'Verify Operation', description: 'Check pressures, superheat, subcooling', details: 'Run unit, measure superheat (8-12F typical) and subcooling (10-15F typical).', caution: 'Fine tune charge based on superheat/subcooling' },
    ],
    verification: [
      'Superheat in correct range (8-12F)',
      'Subcooling in correct range (10-15F)',
      'No leaks detected',
      'Unit cooling properly',
      'Pressures within specs',
    ],
  },
  {
    id: 'rm-hvac-002',
    title: 'Indoor Fan Motor Replacement',
    category: 'Component Replacement',
    difficulty: 'Medium',
    timeRequired: '1-3 hours',
    tools: ['Screwdrivers', 'Nut drivers', 'Multimeter', 'Cable ties', 'Electrical tape'],
    safetyWarnings: [
      'Turn off power at breaker before starting',
      'Verify power off with multimeter',
      'Support motor when removing to prevent drops',
      'Note wire connections before disconnecting',
    ],
    steps: [
      { step: 1, title: 'Power Isolation', description: 'Turn off power at breaker and disconnect', details: 'Turn off breaker, verify power off at unit with multimeter.', caution: 'Lock out/tag out if possible' },
      { step: 2, title: 'Access Motor', description: 'Remove covers to access indoor fan motor', details: 'Remove filters, front panel, any covers hiding motor.', caution: 'Keep track of all screws and components' },
      { step: 3, title: 'Document Wiring', description: 'Take photos of all electrical connections', details: 'Photograph wire colors and positions before disconnecting.', caution: 'Proper documentation prevents errors' },
      { step: 4, title: 'Disconnect Wiring', description: 'Disconnect motor electrical connections', details: 'Disconnect capacitor wires, power wires, any speed wires.', caution: 'Note capacitor polarity if applicable' },
      { step: 5, title: 'Remove Motor', description: 'Remove mounting hardware and motor', details: 'Remove motor mounting screws/bolts. Support motor while removing.', caution: 'Motor is heavy - support during removal' },
      { step: 6, title: 'Transfer Components', description: 'Move blade and hardware to new motor', details: 'Remove blade from old motor, attach to new motor. Transfer any brackets.', caution: 'Blade must be secured properly' },
      { step: 7, title: 'Install New Motor', description: 'Mount new motor in position', details: 'Position motor, install mounting hardware, tighten evenly.', caution: 'Verify motor is centered and secure' },
      { step: 8, title: 'Reconnect Wiring', description: 'Connect electrical wires to new motor', details: 'Follow photos taken earlier. Connect capacitor if new one not included.', caution: 'Verify wire connections match documentation' },
      { step: 9, title: 'Test Operation', description: 'Restore power and test', details: 'Turn on power, run unit, verify proper rotation and airflow.', caution: 'Listen for unusual sounds, check for vibration' },
    ],
    verification: [
      'Motor runs smoothly',
      'No unusual vibration or noise',
      'Proper airflow from all vents',
      'Current draw within specs',
      'No burning smell',
    ],
  },
  {
    id: 'rm-hvac-003',
    title: 'Condenser Coil Cleaning Procedure',
    category: 'Maintenance',
    difficulty: 'Easy',
    timeRequired: '30-60 minutes',
    tools: ['Garden hose', 'Coil cleaner', 'Pump sprayer', 'Fin comb', 'Safety glasses', 'Gloves'],
    safetyWarnings: [
      'Turn off unit before cleaning',
      'Wear safety glasses - chemicals splash',
      'Wear gloves - chemicals irritate skin',
      'Do not spray water into electrical components',
      'Do not use high pressure that bends fins',
    ],
    steps: [
      { step: 1, title: 'Turn Off Unit', description: 'Shut down air conditioner completely', details: 'Turn off at thermostat and breaker for safety.', caution: 'Never clean while unit is running' },
      { step: 2, title: 'Remove Debris', description: 'Clear loose debris from around unit', details: 'Remove leaves, grass, debris from around condenser. Clear area 2 feet around unit.', caution: 'Keep vegetation trimmed away' },
      { step: 3, title: 'Straighten Fins', description: 'Use fin comb to straighten bent fins', details: 'Carefully comb any bent fins back to straight position.', caution: 'Fins are delicate - work carefully' },
      { step: 4, title: 'Apply Coil Cleaner', description: 'Spray coil cleaner on condenser coil', details: 'Apply cleaner liberally, let foam for recommended time (usually 5-10 minutes).', caution: 'Follow product instructions' },
      { step: 5, title: 'Rinse Coil', description: 'Rinse coil with garden hose', details: 'Spray from inside out to push debris out. Use moderate pressure.', caution: 'Avoid spraying electrical components' },
      { step: 6, title: 'Clean Fan Blade', description: 'Clean fan blade while unit is off', details: 'Wipe fan blade clean, check for cracks or damage.', caution: 'Do not bend blade' },
      { step: 7, title: 'Verify Drain', description: 'Ensure condensate drains freely', details: 'Check drain pan and drain line are clear.', caution: 'Blocked drain causes problems' },
      { step: 8, title: 'Restore Power', description: 'Turn unit back on and verify operation', details: 'Restore power, run unit, check for proper operation.', caution: 'Wait 5 minutes before starting compressor' },
    ],
    verification: [
      'Coil fins clean and straight',
      'Good airflow through coil',
      'Head pressure reduced from before cleaning',
      'Unit cooling properly',
      'No chemical residue remaining',
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// PARTS CATALOGUE WITH KENYA SUPPLIERS
// ═══════════════════════════════════════════════════════════════════════════════
export const HVAC_PARTS_CATALOGUE = {
  compressors: [
    { partNumber: 'COPELAND-ZR34K3', description: 'Scroll Compressor 3HP R410A', brand: 'Copeland', priceKES: 45000, application: 'Split AC 24000 BTU', suppliers: ['EmersonEIMS'] },
    { partNumber: 'COPELAND-ZR57K3', description: 'Scroll Compressor 5HP R410A', brand: 'Copeland', priceKES: 75000, application: 'Split AC 48000 BTU', suppliers: ['EmersonEIMS'] },
    { partNumber: 'DAIKIN-JT160', description: 'Inverter Scroll Compressor', brand: 'Daikin', priceKES: 85000, application: 'VRV Systems', suppliers: ['EmersonEIMS'] },
    { partNumber: 'DANFOSS-MT36', description: 'Reciprocating Compressor 3HP', brand: 'Danfoss', priceKES: 38000, application: 'Refrigeration', suppliers: ['EmersonEIMS'] },
    { partNumber: 'BITZER-2CES', description: 'Semi-Hermetic 2HP R404A', brand: 'Bitzer', priceKES: 95000, application: 'Cold Room', suppliers: ['EmersonEIMS'] },
  ],
  capacitors: [
    { partNumber: 'CAP-RUN-35-440', description: 'Run Capacitor 35uF 440V', brand: 'Generic', priceKES: 1500, application: 'Compressor/Fan', suppliers: ['EmersonEIMS'] },
    { partNumber: 'CAP-RUN-45-440', description: 'Run Capacitor 45uF 440V', brand: 'Generic', priceKES: 1800, application: 'Large Compressor', suppliers: ['EmersonEIMS'] },
    { partNumber: 'CAP-RUN-25-440', description: 'Run Capacitor 25uF 440V', brand: 'Generic', priceKES: 1200, application: 'Fan Motor', suppliers: ['EmersonEIMS'] },
    { partNumber: 'CAP-START-88-108', description: 'Start Capacitor 88-108uF', brand: 'Generic', priceKES: 2000, application: 'Hard Start Kit', suppliers: ['EmersonEIMS'] },
    { partNumber: 'CAP-DUAL-35-5', description: 'Dual Capacitor 35+5uF 440V', brand: 'Generic', priceKES: 2200, application: 'Compressor + Fan', suppliers: ['EmersonEIMS'] },
  ],
  fanMotors: [
    { partNumber: 'FM-INDOOR-1/8', description: 'Indoor Fan Motor 1/8HP', brand: 'YS', priceKES: 8500, application: 'Wall Mount AC', suppliers: ['Refrigeration Kenya', 'Hotpoint'] },
    { partNumber: 'FM-OUTDOOR-1/4', description: 'Outdoor Fan Motor 1/4HP', brand: 'YS', priceKES: 12000, application: 'Condenser Unit', suppliers: ['EmersonEIMS'] },
    { partNumber: 'FM-OUTDOOR-1/2', description: 'Outdoor Fan Motor 1/2HP', brand: 'YS', priceKES: 18000, application: 'Large Condenser', suppliers: ['EmersonEIMS'] },
    { partNumber: 'FM-INDOOR-1/4', description: 'Indoor Fan Motor 1/4HP', brand: 'YS', priceKES: 12000, application: 'Ceiling Cassette', suppliers: ['EmersonEIMS'] },
  ],
  refrigerants: [
    { partNumber: 'R410A-11.3KG', description: 'R410A Refrigerant 11.3kg', brand: 'Honeywell', priceKES: 18000, application: 'Modern AC Systems', suppliers: ['EmersonEIMS'] },
    { partNumber: 'R32-10KG', description: 'R32 Refrigerant 10kg', brand: 'Honeywell', priceKES: 16000, application: 'New AC Systems', suppliers: ['EmersonEIMS'] },
    { partNumber: 'R134A-13.6KG', description: 'R134a Refrigerant 13.6kg', brand: 'Honeywell', priceKES: 22000, application: 'Chillers, Auto AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'R404A-10.9KG', description: 'R404A Refrigerant 10.9kg', brand: 'Honeywell', priceKES: 28000, application: 'Refrigeration', suppliers: ['EmersonEIMS'] },
    { partNumber: 'R22-13.6KG', description: 'R22 Refrigerant 13.6kg', brand: 'Various', priceKES: 35000, application: 'Legacy Systems', suppliers: ['EmersonEIMS'] },
  ],
  controls: [
    { partNumber: 'TSTAT-DIGITAL', description: 'Digital Thermostat', brand: 'Honeywell', priceKES: 8500, application: 'Split AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'TSTAT-WIFI', description: 'WiFi Smart Thermostat', brand: 'Honeywell', priceKES: 25000, application: 'Smart HVAC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'CTRL-COLDROOM', description: 'Cold Room Controller', brand: 'Eliwell', priceKES: 15000, application: 'Walk-in Cooler', suppliers: ['EmersonEIMS'] },
    { partNumber: 'RELAY-DEFROST', description: 'Defrost Timer/Relay', brand: 'Various', priceKES: 3500, application: 'Refrigeration', suppliers: ['EmersonEIMS'] },
    { partNumber: 'PSWITCH-HP', description: 'High Pressure Switch', brand: 'Danfoss', priceKES: 5500, application: 'All Systems', suppliers: ['EmersonEIMS'] },
    { partNumber: 'PSWITCH-LP', description: 'Low Pressure Switch', brand: 'Danfoss', priceKES: 4500, application: 'All Systems', suppliers: ['EmersonEIMS'] },
  ],
  filterDriers: [
    { partNumber: 'DRIER-083', description: 'Filter Drier 3/8" Flare', brand: 'Danfoss', priceKES: 1800, application: 'Small AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'DRIER-163', description: 'Filter Drier 3/8" Solder', brand: 'Danfoss', priceKES: 2200, application: 'Medium AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'DRIER-165', description: 'Filter Drier 5/8" Solder', brand: 'Danfoss', priceKES: 3500, application: 'Large AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'DRIER-CORE', description: 'Replaceable Core 48-DC', brand: 'Sporlan', priceKES: 4500, application: 'Shell & Core', suppliers: ['EmersonEIMS'] },
  ],
  txv: [
    { partNumber: 'TXV-R410A-3T', description: 'TXV 3 Ton R410A', brand: 'Danfoss', priceKES: 12000, application: '3 Ton AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'TXV-R410A-5T', description: 'TXV 5 Ton R410A', brand: 'Danfoss', priceKES: 15000, application: '5 Ton AC', suppliers: ['EmersonEIMS'] },
    { partNumber: 'TXV-R404A-3T', description: 'TXV 3 Ton R404A', brand: 'Danfoss', priceKES: 13500, application: 'Refrigeration', suppliers: ['EmersonEIMS'] },
    { partNumber: 'EXV-R410A', description: 'Electronic Expansion Valve', brand: 'Danfoss', priceKES: 35000, application: 'VRV Systems', suppliers: ['EmersonEIMS'] },
  ],
  coils: [
    { partNumber: 'COIL-EVAP-12K', description: 'Evaporator Coil 12000 BTU', brand: 'Various', priceKES: 18000, application: '1 Ton Split', suppliers: ['EmersonEIMS'] },
    { partNumber: 'COIL-EVAP-24K', description: 'Evaporator Coil 24000 BTU', brand: 'Various', priceKES: 28000, application: '2 Ton Split', suppliers: ['EmersonEIMS'] },
    { partNumber: 'COIL-COND-24K', description: 'Condenser Coil 24000 BTU', brand: 'Various', priceKES: 32000, application: '2 Ton Split', suppliers: ['EmersonEIMS'] },
    { partNumber: 'COIL-COLDROOM', description: 'Cold Room Evaporator', brand: 'Bohn', priceKES: 85000, application: 'Walk-in Cooler', suppliers: ['EmersonEIMS'] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MAINTENANCE SCHEDULES
// ═══════════════════════════════════════════════════════════════════════════════
export const HVAC_MAINTENANCE_SCHEDULES = {
  residential: {
    monthly: [
      { task: 'Check/clean air filters', procedure: 'Remove filters, clean or replace if dirty', tools: ['None'] },
      { task: 'Check thermostat operation', procedure: 'Verify temperature setpoint and response', tools: ['Thermometer'] },
    ],
    quarterly: [
      { task: 'Clean indoor coil', procedure: 'Remove panel, clean coil with soft brush or coil cleaner', tools: ['Coil cleaner', 'Brush'] },
      { task: 'Check condensate drain', procedure: 'Verify drain is clear, clean if blocked', tools: ['Wet/dry vacuum'] },
      { task: 'Check refrigerant pressures', procedure: 'Connect gauges, verify normal pressures', tools: ['Manifold gauges'] },
    ],
    annually: [
      { task: 'Full system inspection', procedure: 'Comprehensive check of all components', tools: ['Full tool kit'] },
      { task: 'Clean condenser coil', procedure: 'Wash outdoor coil with pressure washer', tools: ['Coil cleaner', 'Hose'] },
      { task: 'Check electrical connections', procedure: 'Tighten all connections, check voltage', tools: ['Multimeter', 'Screwdrivers'] },
      { task: 'Lubricate moving parts', procedure: 'Oil fan motor bearings if applicable', tools: ['Lubricating oil'] },
      { task: 'Check refrigerant charge', procedure: 'Verify superheat/subcooling, adjust if needed', tools: ['Manifold gauges', 'Thermometers'] },
    ],
  },
  commercial: {
    weekly: [
      { task: 'Check system operation', procedure: 'Verify all units running, no alarms', tools: ['None'] },
      { task: 'Record temperatures', procedure: 'Log supply/return air temperatures', tools: ['Thermometer'] },
    ],
    monthly: [
      { task: 'Change/clean filters', procedure: 'Replace or clean all air filters', tools: ['None'] },
      { task: 'Check belt tension', procedure: 'Inspect and adjust belt tension on AHUs', tools: ['Belt gauge'] },
      { task: 'Check condensate drains', procedure: 'Clear all drain lines and pans', tools: ['Wet/dry vacuum'] },
      { task: 'Inspect electrical panels', procedure: 'Visual check for overheating, loose connections', tools: ['IR thermometer'] },
    ],
    quarterly: [
      { task: 'Clean coils', procedure: 'Clean evaporator and condenser coils', tools: ['Coil cleaner', 'Brush'] },
      { task: 'Check refrigerant charge', procedure: 'Verify pressures and temperatures', tools: ['Manifold gauges'] },
      { task: 'Lubricate motors and bearings', procedure: 'Apply lubricant per manufacturer specs', tools: ['Grease gun', 'Oil'] },
      { task: 'Check controls and safeties', procedure: 'Test all safety controls operation', tools: ['Multimeter'] },
    ],
    annually: [
      { task: 'Complete system inspection', procedure: 'Full inspection of all equipment', tools: ['Full tool kit'] },
      { task: 'Electrical testing', procedure: 'Megger motors, check connections', tools: ['Megger', 'Multimeter'] },
      { task: 'Vibration analysis', procedure: 'Check for bearing wear and imbalance', tools: ['Vibration meter'] },
      { task: 'Refrigerant leak test', procedure: 'Full leak detection on all systems', tools: ['Leak detector'] },
      { task: 'Water treatment check', procedure: 'Test and treat chilled/condenser water', tools: ['Water test kit'] },
    ],
  },
  coldRoom: {
    daily: [
      { task: 'Record temperatures', procedure: 'Log room and product temperatures', tools: ['Thermometer', 'Log sheet'] },
      { task: 'Check door seals', procedure: 'Verify doors close properly, no frost buildup', tools: ['None'] },
      { task: 'Visual inspection', procedure: 'Check for ice buildup, unusual operation', tools: ['None'] },
    ],
    weekly: [
      { task: 'Check defrost operation', procedure: 'Verify defrost cycles running properly', tools: ['None'] },
      { task: 'Check evaporator fans', procedure: 'Verify all fans running, check for ice', tools: ['None'] },
      { task: 'Clean floor drain', procedure: 'Clear any debris from floor drain', tools: ['None'] },
    ],
    monthly: [
      { task: 'Clean evaporator coil', procedure: 'Defrost and clean coil if needed', tools: ['Coil cleaner'] },
      { task: 'Check door heaters', procedure: 'Verify frame heaters working', tools: ['Thermometer'] },
      { task: 'Check pressures', procedure: 'Verify normal operating pressures', tools: ['Manifold gauges'] },
      { task: 'Inspect insulation', procedure: 'Check for moisture or damage', tools: ['Moisture meter'] },
    ],
    quarterly: [
      { task: 'Deep clean evaporator', procedure: 'Thorough coil cleaning and sanitization', tools: ['Coil cleaner', 'Sanitizer'] },
      { task: 'Check compressor oil', procedure: 'Verify oil level and condition', tools: ['Sight glass'] },
      { task: 'Inspect electrical', procedure: 'Check all connections and controls', tools: ['Multimeter'] },
      { task: 'Replace filter drier', procedure: 'Change drier if moisture present', tools: ['Brazing kit'] },
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// EMERSONEIMS PARTS & SERVICES - YOUR TRUSTED PARTNER
// ═══════════════════════════════════════════════════════════════════════════════
export const HVAC_KENYA_SUPPLIERS = [
  { name: 'EmersonEIMS', location: 'Nairobi, Kenya (Serving All Counties)', specialization: 'Complete HVAC Solutions - Installation, Maintenance, Repairs & Parts', phone: '+254 768 860 665', email: 'info@emersoneims.com' },
];

// Export all
export const HVAC_BIBLE_DATA = {
  faultCodes: HVAC_FAULT_CODES,
  repairManuals: HVAC_REPAIR_MANUALS,
  partsCatalogue: HVAC_PARTS_CATALOGUE,
  maintenanceSchedules: HVAC_MAINTENANCE_SCHEDULES,
  suppliers: HVAC_KENYA_SUPPLIERS,
};
