/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * MOTORS BIBLE - COMPREHENSIVE DATA
 * Repair Manuals, Parts Catalogue, Maintenance Schedules, Extended Fault Codes
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// ═══════════════════════════════════════════════════════════════════════════════
// EXTENDED FAULT CODES DATABASE (200+)
// ═══════════════════════════════════════════════════════════════════════════════
export const MOTOR_FAULT_CODES = [
  // WINDING FAULTS (MW001-MW050)
  { code: 'MW001', name: 'Open Winding', category: 'Winding', severity: 'Critical', motor_type: 'All',
    symptoms: ['Motor will not start', 'No current draw', 'Single phase hum', 'Infinite resistance'],
    causes: ['Burnt connection', 'Broken wire', 'Loose terminal', 'Internal break'],
    diagnostics: ['Winding resistance test', 'Continuity check', 'Visual inspection'],
    repair_steps: ['Test each phase', 'Locate break point', 'Rewind if internal', 'Repair terminal if external'],
    parts_needed: ['Magnet wire', 'Insulation paper', 'Varnish'],
    estimated_cost: 'KES 15,000 - 100,000', repair_time: '4-24 hours' },
  { code: 'MW002', name: 'Shorted Turns', category: 'Winding', severity: 'High', motor_type: 'All',
    symptoms: ['Overheating', 'High current', 'Reduced torque', 'Smoke/burning smell'],
    causes: ['Insulation failure', 'Contamination', 'Overload damage', 'Age deterioration'],
    diagnostics: ['Surge comparison test', 'IR reading', 'Turn ratio test'],
    repair_steps: ['Identify shorted coils', 'Strip windings', 'Rewind motor'],
    parts_needed: ['Magnet wire', 'Slot insulation', 'Varnish'],
    estimated_cost: 'KES 20,000 - 150,000', repair_time: '8-48 hours' },
  { code: 'MW003', name: 'Phase to Phase Short', category: 'Winding', severity: 'Critical', motor_type: 'Three Phase',
    symptoms: ['Blown fuses', 'Breaker trips', 'Very high current', 'Smoke'],
    causes: ['Insulation breakdown', 'Mechanical damage', 'Contamination', 'Overheating'],
    diagnostics: ['Insulation resistance test', 'Winding resistance imbalance', 'Visual inspection'],
    repair_steps: ['Complete rewind required', 'Strip and clean core', 'Apply new windings'],
    parts_needed: ['Magnet wire', 'Complete insulation kit', 'Varnish'],
    estimated_cost: 'KES 25,000 - 200,000', repair_time: '12-72 hours' },
  { code: 'MW004', name: 'Phase to Ground Fault', category: 'Winding', severity: 'Critical', motor_type: 'All',
    symptoms: ['Ground fault tripping', 'Shock hazard', 'Insulation breakdown', 'Low megger reading'],
    causes: ['Damaged insulation', 'Moisture ingress', 'Contamination', 'Mechanical damage'],
    diagnostics: ['Megger test <1MΩ', 'Hi-pot test failure', 'Visual inspection'],
    repair_steps: ['Identify fault location', 'Spot repair if minor', 'Full rewind if extensive'],
    parts_needed: ['Insulation materials', 'Varnish', 'Magnet wire if rewind'],
    estimated_cost: 'KES 10,000 - 180,000', repair_time: '4-48 hours' },
  { code: 'MW005', name: 'Winding Overheating', category: 'Winding', severity: 'High', motor_type: 'All',
    symptoms: ['Discolored windings', 'Burnt smell', 'Insulation damage', 'High temperature'],
    causes: ['Overload', 'Poor ventilation', 'Voltage imbalance', 'Bearing problems'],
    diagnostics: ['Visual inspection', 'Temperature measurement', 'Current monitoring'],
    repair_steps: ['Address root cause', 'Revarnish if minor', 'Rewind if insulation damaged'],
    parts_needed: ['Varnish', 'Possibly full rewind kit'],
    estimated_cost: 'KES 5,000 - 150,000', repair_time: '2-48 hours' },

  // BEARING FAULTS (MB001-MB040)
  { code: 'MB001', name: 'Bearing Wear', category: 'Bearing', severity: 'High', motor_type: 'All',
    symptoms: ['Noise', 'Vibration', 'Heat', 'Shaft play', 'Inconsistent operation'],
    causes: ['Lack of lubrication', 'Contamination', 'Misalignment', 'Age', 'Overload'],
    diagnostics: ['Vibration analysis', 'Bearing clearance check', 'Temperature monitoring'],
    repair_steps: ['Remove old bearing', 'Clean housing', 'Install new bearing', 'Lubricate'],
    parts_needed: ['Bearings (DE and NDE)', 'Grease'],
    estimated_cost: 'KES 3,000 - 30,000', repair_time: '2-6 hours' },
  { code: 'MB002', name: 'Bearing Failure - Locked', category: 'Bearing', severity: 'Critical', motor_type: 'All',
    symptoms: ['Motor will not turn', 'Seized shaft', 'Overheating', 'Burn marks'],
    causes: ['Complete lubrication failure', 'Severe contamination', 'Excessive load'],
    diagnostics: ['Physical inspection', 'Cannot rotate shaft', 'Bearing discoloration'],
    repair_steps: ['Extract bearings', 'Inspect shaft for damage', 'Replace bearings', 'Check alignment'],
    parts_needed: ['New bearings', 'Possibly shaft repair'],
    estimated_cost: 'KES 5,000 - 50,000', repair_time: '3-8 hours' },
  { code: 'MB003', name: 'Bearing Housing Damage', category: 'Bearing', severity: 'High', motor_type: 'All',
    symptoms: ['Bearing spins in housing', 'Eccentric shaft', 'Vibration'],
    causes: ['Incorrect fit', 'Overload', 'Repeated bearing replacement'],
    diagnostics: ['Measure housing ID', 'Check bearing fit', 'Look for scoring'],
    repair_steps: ['Machine housing', 'Install sleeve', 'Or replace end bracket'],
    parts_needed: ['End bracket or sleeve', 'New bearing'],
    estimated_cost: 'KES 10,000 - 80,000', repair_time: '4-12 hours' },
  { code: 'MB004', name: 'Shaft Wear at Bearing', category: 'Bearing', severity: 'High', motor_type: 'All',
    symptoms: ['Bearing loose on shaft', 'Play in shaft', 'Noise'],
    causes: ['Incorrect fit', 'Repeated bearing removal', 'Overload'],
    diagnostics: ['Measure shaft diameter', 'Check bearing inner race fit'],
    repair_steps: ['Metal spray shaft', 'Machine to size', 'Or replace shaft'],
    parts_needed: ['Shaft repair materials', 'New bearing'],
    estimated_cost: 'KES 15,000 - 100,000', repair_time: '6-24 hours' },

  // ROTOR FAULTS (MR001-MR030)
  { code: 'MR001', name: 'Broken Rotor Bars', category: 'Rotor', severity: 'High', motor_type: 'Squirrel Cage',
    symptoms: ['Reduced starting torque', 'High slip', 'Vibration', 'Hot spots'],
    causes: ['Thermal stress', 'Centrifugal forces', 'Manufacturing defect', 'Frequent starts'],
    diagnostics: ['Motor current signature analysis', 'Growler test', 'Visual inspection'],
    repair_steps: ['Re-bar rotor', 'Or replace rotor', 'Balance after repair'],
    parts_needed: ['Aluminum or copper bars', 'End rings'],
    estimated_cost: 'KES 30,000 - 200,000', repair_time: '12-48 hours' },
  { code: 'MR002', name: 'Rotor Eccentricity', category: 'Rotor', severity: 'Medium', motor_type: 'All',
    symptoms: ['Uneven air gap', 'Vibration', 'Pulsating current', 'Noise'],
    causes: ['Worn bearings', 'Bent shaft', 'Damaged core', 'Manufacturing issue'],
    diagnostics: ['Air gap measurement', 'Shaft runout check', 'Vibration analysis'],
    repair_steps: ['Replace bearings', 'True shaft', 'Or machine rotor'],
    parts_needed: ['Bearings', 'Possibly shaft repair'],
    estimated_cost: 'KES 10,000 - 80,000', repair_time: '4-16 hours' },
  { code: 'MR003', name: 'Rotor Core Damage', category: 'Rotor', severity: 'Critical', motor_type: 'All',
    symptoms: ['Vibration', 'Noise', 'Reduced efficiency', 'Hot spots'],
    causes: ['Rotor-stator contact', 'Foreign object', 'Fatigue'],
    diagnostics: ['Visual inspection', 'Core loss test', 'Vibration signature'],
    repair_steps: ['Repair laminations if minor', 'Replace rotor if severe', 'New core if available'],
    parts_needed: ['Rotor or core stack'],
    estimated_cost: 'KES 50,000 - 300,000', repair_time: '24-96 hours' },

  // MECHANICAL FAULTS (MM001-MM030)
  { code: 'MM001', name: 'Shaft Misalignment', category: 'Mechanical', severity: 'High', motor_type: 'All',
    symptoms: ['Vibration', 'Premature bearing failure', 'Coupling wear', 'High temperature'],
    causes: ['Poor installation', 'Foundation movement', 'Thermal growth', 'Piping stress'],
    diagnostics: ['Laser alignment check', 'Vibration analysis', 'Temperature monitoring'],
    repair_steps: ['Perform laser alignment', 'Adjust motor position', 'Shim as required'],
    parts_needed: ['Shims', 'Coupling if damaged'],
    estimated_cost: 'KES 5,000 - 30,000', repair_time: '2-6 hours' },
  { code: 'MM002', name: 'Unbalanced Rotor', category: 'Mechanical', severity: 'Medium', motor_type: 'All',
    symptoms: ['Vibration at 1x RPM', 'Bearing wear', 'Noise'],
    causes: ['Lost balance weight', 'Uneven contamination', 'Broken rotor bar', 'Bent shaft'],
    diagnostics: ['Vibration analysis', 'Phase analysis', 'Visual inspection'],
    repair_steps: ['Dynamic balancing', 'Clean rotor', 'Fix root cause'],
    parts_needed: ['Balance weights', 'Possibly rotor repair'],
    estimated_cost: 'KES 8,000 - 40,000', repair_time: '2-8 hours' },
  { code: 'MM003', name: 'Loose Foundation', category: 'Mechanical', severity: 'Medium', motor_type: 'All',
    symptoms: ['Vibration', 'Movement', 'Alignment problems', 'Bolt loosening'],
    causes: ['Foundation deterioration', 'Improper installation', 'Vibration damage'],
    diagnostics: ['Foundation inspection', 'Bolt tightness check', 'Alignment check'],
    repair_steps: ['Re-grout', 'Tighten bolts', 'Realign'],
    parts_needed: ['Grout', 'Foundation bolts', 'Shims'],
    estimated_cost: 'KES 10,000 - 50,000', repair_time: '4-12 hours' },
  { code: 'MM004', name: 'Coupling Failure', category: 'Mechanical', severity: 'High', motor_type: 'All',
    symptoms: ['Vibration', 'Noise', 'Coupling damage visible', 'Shaft movement'],
    causes: ['Misalignment', 'Overload', 'Age', 'Contamination'],
    diagnostics: ['Visual inspection', 'Coupling element check', 'Alignment verification'],
    repair_steps: ['Replace coupling elements', 'Or complete coupling', 'Realign'],
    parts_needed: ['Coupling or elements', 'Alignment tools'],
    estimated_cost: 'KES 5,000 - 50,000', repair_time: '2-6 hours' },

  // ELECTRICAL FAULTS (ME001-ME040)
  { code: 'ME001', name: 'Single Phasing', category: 'Electrical', severity: 'Critical', motor_type: 'Three Phase',
    symptoms: ['Motor hums', 'Will not start', 'Overheating', 'Unequal currents'],
    causes: ['Fuse blown', 'Contactor issue', 'Loose connection', 'Supply problem'],
    diagnostics: ['Check voltage all phases', 'Check current all phases', 'Inspect connections'],
    repair_steps: ['Find and fix open phase', 'Replace fuse/breaker', 'Tighten connections'],
    parts_needed: ['Fuses', 'Contactors if needed'],
    estimated_cost: 'KES 500 - 10,000', repair_time: '0.5-2 hours' },
  { code: 'ME002', name: 'Voltage Imbalance', category: 'Electrical', severity: 'High', motor_type: 'Three Phase',
    symptoms: ['Overheating', 'Unequal currents', 'Reduced efficiency', 'Vibration'],
    causes: ['Supply problem', 'Load imbalance on transformer', 'Bad connection'],
    diagnostics: ['Measure all three voltages', 'Calculate % imbalance'],
    repair_steps: ['Report to utility', 'Check connections', 'Install voltage monitor'],
    parts_needed: ['Voltage monitoring relay'],
    estimated_cost: 'KES 5,000 - 20,000', repair_time: '1-4 hours' },
  { code: 'ME003', name: 'Over-voltage', category: 'Electrical', severity: 'High', motor_type: 'All',
    symptoms: ['Overheating', 'Increased current', 'Insulation stress', 'Core saturation'],
    causes: ['Supply issue', 'Transformer tap setting', 'Light load on grid'],
    diagnostics: ['Voltage measurement', 'Compare to nameplate'],
    repair_steps: ['Report to utility', 'Install voltage stabilizer', 'Adjust transformer taps'],
    parts_needed: ['Voltage stabilizer'],
    estimated_cost: 'KES 20,000 - 200,000', repair_time: '2-8 hours' },
  { code: 'ME004', name: 'Under-voltage', category: 'Electrical', severity: 'High', motor_type: 'All',
    symptoms: ['Poor starting', 'Overheating', 'High current', 'Reduced torque'],
    causes: ['Supply issue', 'Long cable run', 'Heavy load on grid', 'Undersized cables'],
    diagnostics: ['Voltage measurement at motor', 'Compare to supply', 'Cable size check'],
    repair_steps: ['Report to utility', 'Upsize cables', 'Install voltage stabilizer'],
    parts_needed: ['Larger cables', 'Voltage stabilizer'],
    estimated_cost: 'KES 15,000 - 150,000', repair_time: '4-24 hours' },
  { code: 'ME005', name: 'VFD Induced Bearing Current', category: 'Electrical', severity: 'Medium', motor_type: 'VFD Driven',
    symptoms: ['Premature bearing failure', 'Fluting on races', 'EDM marks', 'Noise'],
    causes: ['High frequency common mode voltage', 'Poor grounding', 'No shaft grounding'],
    diagnostics: ['Bearing inspection', 'Shaft voltage measurement', 'Grounding check'],
    repair_steps: ['Install shaft grounding ring', 'Insulate bearings', 'Improve grounding'],
    parts_needed: ['Shaft grounding ring', 'Insulated bearings'],
    estimated_cost: 'KES 15,000 - 50,000', repair_time: '4-8 hours' },

  // COOLING FAULTS (MC001-MC020)
  { code: 'MC001', name: 'Blocked Cooling Fins', category: 'Cooling', severity: 'Medium', motor_type: 'TEFC',
    symptoms: ['Overheating', 'Reduced life', 'Thermal trips'],
    causes: ['Dust accumulation', 'Debris', 'Paint overspray'],
    diagnostics: ['Visual inspection', 'Temperature measurement', 'Air flow check'],
    repair_steps: ['Clean fins', 'Brush and blow out debris'],
    parts_needed: ['None usually'],
    estimated_cost: 'KES 2,000 - 5,000', repair_time: '0.5-2 hours' },
  { code: 'MC002', name: 'Fan Broken or Missing', category: 'Cooling', severity: 'High', motor_type: 'TEFC',
    symptoms: ['Overheating', 'No airflow', 'Missing/damaged fan visible'],
    causes: ['Debris impact', 'Fatigue', 'Over-speed'],
    diagnostics: ['Visual inspection', 'Air flow check'],
    repair_steps: ['Replace cooling fan', 'Check cover'],
    parts_needed: ['Cooling fan'],
    estimated_cost: 'KES 3,000 - 15,000', repair_time: '1-3 hours' },
  { code: 'MC003', name: 'Fan Cover Damaged', category: 'Cooling', severity: 'Medium', motor_type: 'TEFC',
    symptoms: ['Noise', 'Safety hazard', 'Debris entry'],
    causes: ['Impact', 'Corrosion', 'Vibration'],
    diagnostics: ['Visual inspection'],
    repair_steps: ['Replace fan cover'],
    parts_needed: ['Fan cover'],
    estimated_cost: 'KES 5,000 - 20,000', repair_time: '0.5-2 hours' },

  // INSULATION FAULTS (MI001-MI020)
  { code: 'MI001', name: 'Low Insulation Resistance', category: 'Insulation', severity: 'High', motor_type: 'All',
    symptoms: ['Earth fault trips', 'Low megger reading', 'Moisture indication'],
    causes: ['Moisture', 'Contamination', 'Age', 'Thermal damage'],
    diagnostics: ['Megger test', 'Polarization index test'],
    repair_steps: ['Dry out motor', 'Re-varnish', 'Rewind if damaged'],
    parts_needed: ['Varnish', 'Heaters for drying'],
    estimated_cost: 'KES 5,000 - 100,000', repair_time: '24-72 hours' },
  { code: 'MI002', name: 'Polarization Index Low', category: 'Insulation', severity: 'High', motor_type: 'All',
    symptoms: ['PI <2', 'Contamination', 'Moisture'],
    causes: ['Moisture ingress', 'Oil contamination', 'Degraded insulation'],
    diagnostics: ['PI test (10 min/1 min ratio)', 'DA test'],
    repair_steps: ['Identify cause', 'Clean or dry', 'Re-varnish or rewind'],
    parts_needed: ['Cleaning solvents', 'Varnish'],
    estimated_cost: 'KES 10,000 - 80,000', repair_time: '8-48 hours' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// REPAIR MANUALS
// ═══════════════════════════════════════════════════════════════════════════════
export const MOTOR_REPAIR_MANUALS = [
  {
    id: 'rm-motor-001',
    title: 'Motor Bearing Replacement Procedure',
    category: 'Mechanical Repair',
    difficulty: 'Medium',
    timeRequired: '2-6 hours',
    tools: ['Bearing puller', 'Bearing press/heater', 'Soft hammer', 'Dial indicator', 'Micrometers', 'Grease gun'],
    safetyWarnings: [
      'Lock out/tag out power supply',
      'Allow motor to cool before working',
      'Use proper lifting equipment for heavy motors',
      'Wear safety glasses when using puller',
    ],
    steps: [
      { step: 1, title: 'Isolate and Document', description: 'Lock out power, document all connections', details: 'Tag breaker, disconnect leads, note connection points and cable routing.', caution: 'Verify power off with multimeter' },
      { step: 2, title: 'Remove Motor', description: 'Disconnect coupling and remove motor from base', details: 'Mark coupling halves for reassembly. Use lifting equipment for motors >25kg.', caution: 'Support motor weight during removal' },
      { step: 3, title: 'Remove Fan Cover and Fan', description: 'Remove rear cover and cooling fan', details: 'Note fan orientation, check for damage.', caution: 'Fan may be press-fit on shaft' },
      { step: 4, title: 'Mark End Brackets', description: 'Mark stator and end brackets for alignment', details: 'Use punch marks or paint for alignment on reassembly.', caution: 'Essential for proper reassembly' },
      { step: 5, title: 'Remove End Brackets', description: 'Remove bolts and slide off end brackets', details: 'Support rotor when removing drive end bracket.', caution: 'Do not damage stator laminations' },
      { step: 6, title: 'Remove Rotor', description: 'Slide rotor out of stator', details: 'Use rotor support stand if available. Keep rotor level.', caution: 'Avoid damaging windings or laminations' },
      { step: 7, title: 'Remove Old Bearings', description: 'Use bearing puller to remove bearings', details: 'Apply force to inner race only. Note bearing number.', caution: 'Never reuse old bearings' },
      { step: 8, title: 'Inspect Shaft', description: 'Measure shaft at bearing locations', details: 'Check for wear, scoring, or corrosion. Measure with micrometer.', caution: 'Shaft damage requires repair before new bearings' },
      { step: 9, title: 'Install New Bearings', description: 'Heat bearings to 100-110C and slide onto shaft', details: 'Apply force to inner race only. Bearing should slide on smoothly when heated.', caution: 'Never hammer on outer race' },
      { step: 10, title: 'Reassemble', description: 'Reverse disassembly procedure', details: 'Align marks, grease bearings, torque bolts evenly.', caution: 'Verify free rotation before energizing' },
      { step: 11, title: 'Test', description: 'Reinstall and test motor', details: 'Run uncoupled, check vibration, temperature, and current.', caution: 'Monitor closely during initial run' },
    ],
    verification: [
      'Rotor turns freely by hand',
      'No unusual noise or vibration',
      'Current balanced on all phases',
      'Bearing temperature stable',
      'Vibration within specification',
    ],
  },
  {
    id: 'rm-motor-002',
    title: 'Motor Rewinding Procedure',
    category: 'Winding Repair',
    difficulty: 'Advanced',
    timeRequired: '24-72 hours',
    tools: ['Burnout oven', 'Coil winding machine', 'Insulation materials', 'Varnish tank', 'VPI system', 'Test equipment'],
    safetyWarnings: [
      'Burnout fumes are toxic - proper ventilation required',
      'Hot varnish is flammable - no open flames',
      'Use appropriate PPE for chemicals',
      'High voltage testing - follow procedures',
    ],
    steps: [
      { step: 1, title: 'Document Original', description: 'Record all winding data before stripping', details: 'Note wire size, turns per coil, connection pattern, slot fill, spans.', caution: 'Accurate data is essential for proper rewind' },
      { step: 2, title: 'Core Loss Test', description: 'Test core before stripping', details: 'Perform ring flux test to verify core condition.', caution: 'Damaged core may need restacking' },
      { step: 3, title: 'Burnout', description: 'Remove windings by controlled heating', details: 'Heat to 350-400C in burnout oven. Allow to cool slowly.', caution: 'Over-temperature damages core' },
      { step: 4, title: 'Clean Core', description: 'Remove all carbon and debris', details: 'Brush slots, blow out debris, inspect laminations.', caution: 'Core must be clean for good insulation' },
      { step: 5, title: 'Install Slot Insulation', description: 'Insert slot liners and phase separators', details: 'Use specified insulation class materials.', caution: 'Proper insulation prevents failure' },
      { step: 6, title: 'Wind Coils', description: 'Wind new coils to specification', details: 'Match original wire size, turns, and winding pattern.', caution: 'Consistent tension is important' },
      { step: 7, title: 'Insert Coils', description: 'Place coils in slots', details: 'Insert bottom coils first, then top coils. Insert wedges.', caution: 'Do not damage insulation during insertion' },
      { step: 8, title: 'Make Connections', description: 'Connect coils per winding diagram', details: 'Braze or crimp connections. Insulate all joints.', caution: 'Verify connection pattern before testing' },
      { step: 9, title: 'Test Before Varnish', description: 'Perform electrical tests', details: 'Surge test, insulation resistance, winding resistance balance.', caution: 'Easier to fix problems before varnish' },
      { step: 10, title: 'Varnish Treatment', description: 'Apply insulating varnish', details: 'Dip or VPI process. Bake to cure.', caution: 'Proper cure is essential' },
      { step: 11, title: 'Final Test', description: 'Complete electrical testing', details: 'IR, PI, surge, hipot, no-load run.', caution: 'Must pass all tests before return' },
    ],
    verification: [
      'Winding resistance balanced within 2%',
      'Insulation resistance >100MΩ',
      'Polarization index >2',
      'Surge test passed',
      'Hi-pot test passed',
      'No-load current balanced and within spec',
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// PARTS CATALOGUE WITH KENYA SUPPLIERS
// ═══════════════════════════════════════════════════════════════════════════════
export const MOTOR_PARTS_CATALOGUE = {
  bearings: [
    { partNumber: '6205-2RS', description: 'Deep Groove Ball Bearing 25x52x15', brand: 'SKF', priceKES: 1200, application: 'Small motors 0.5-2HP', suppliers: ['SKF Kenya', 'Bearing distributors'] },
    { partNumber: '6206-2RS', description: 'Deep Groove Ball Bearing 30x62x16', brand: 'SKF', priceKES: 1500, application: 'Motors 2-5HP', suppliers: ['SKF Kenya', 'Bearing distributors'] },
    { partNumber: '6207-2RS', description: 'Deep Groove Ball Bearing 35x72x17', brand: 'SKF', priceKES: 1800, application: 'Motors 5-10HP', suppliers: ['SKF Kenya', 'Bearing distributors'] },
    { partNumber: '6208-2RS', description: 'Deep Groove Ball Bearing 40x80x18', brand: 'SKF', priceKES: 2200, application: 'Motors 10-15HP', suppliers: ['SKF Kenya'] },
    { partNumber: '6209-2RS', description: 'Deep Groove Ball Bearing 45x85x19', brand: 'SKF', priceKES: 2800, application: 'Motors 15-25HP', suppliers: ['SKF Kenya'] },
    { partNumber: '6210-2RS', description: 'Deep Groove Ball Bearing 50x90x20', brand: 'SKF', priceKES: 3500, application: 'Motors 25-40HP', suppliers: ['SKF Kenya'] },
    { partNumber: '6310-2RS', description: 'Deep Groove Ball Bearing 50x110x27', brand: 'SKF', priceKES: 5500, application: 'Large motors', suppliers: ['SKF Kenya'] },
    { partNumber: 'NU206', description: 'Cylindrical Roller Bearing', brand: 'SKF', priceKES: 4500, application: 'High load DE', suppliers: ['SKF Kenya'] },
  ],
  magnetWire: [
    { partNumber: 'MW-0.5-CLASS-F', description: 'Magnet Wire 0.5mm Class F', brand: 'Essex', priceKES: 2500, application: 'Small motors', suppliers: ['Wire suppliers', 'Motor shops'] },
    { partNumber: 'MW-0.8-CLASS-F', description: 'Magnet Wire 0.8mm Class F', brand: 'Essex', priceKES: 2800, application: 'Medium motors', suppliers: ['Wire suppliers', 'Motor shops'] },
    { partNumber: 'MW-1.0-CLASS-F', description: 'Magnet Wire 1.0mm Class F', brand: 'Essex', priceKES: 3200, application: 'Medium motors', suppliers: ['Wire suppliers', 'Motor shops'] },
    { partNumber: 'MW-1.2-CLASS-H', description: 'Magnet Wire 1.2mm Class H', brand: 'Essex', priceKES: 4000, application: 'High temp motors', suppliers: ['Wire suppliers'] },
    { partNumber: 'MW-1.5-CLASS-F', description: 'Magnet Wire 1.5mm Class F', brand: 'Essex', priceKES: 4500, application: 'Large motors', suppliers: ['Wire suppliers'] },
  ],
  insulation: [
    { partNumber: 'SLOT-LINER-0.3', description: 'Slot Liner 0.3mm Class F', brand: 'DuPont', priceKES: 150, application: 'Per meter', suppliers: ['Insulation suppliers'] },
    { partNumber: 'PHASE-PAPER-0.2', description: 'Phase Separator Paper', brand: 'DuPont', priceKES: 120, application: 'Per meter', suppliers: ['Insulation suppliers'] },
    { partNumber: 'WEDGE-STRIP', description: 'Slot Wedge Strip', brand: 'Generic', priceKES: 80, application: 'Per meter', suppliers: ['Motor shops'] },
    { partNumber: 'VARNISH-5L', description: 'Insulating Varnish 5L', brand: 'Dolphin', priceKES: 5500, application: 'Dip varnish', suppliers: ['Chemical suppliers'] },
    { partNumber: 'SLEEVE-1.5', description: 'Insulating Sleeve 1.5mm', brand: 'Generic', priceKES: 50, application: 'Per meter', suppliers: ['Electrical shops'] },
  ],
  capacitors: [
    { partNumber: 'START-CAP-100UF', description: 'Start Capacitor 100uF 250V', brand: 'Ducati', priceKES: 1800, application: 'Single phase 0.5-1HP', suppliers: ['Electrical wholesalers'] },
    { partNumber: 'START-CAP-200UF', description: 'Start Capacitor 200uF 250V', brand: 'Ducati', priceKES: 2500, application: 'Single phase 1-2HP', suppliers: ['Electrical wholesalers'] },
    { partNumber: 'START-CAP-300UF', description: 'Start Capacitor 300uF 250V', brand: 'Ducati', priceKES: 3200, application: 'Single phase 2-3HP', suppliers: ['Electrical wholesalers'] },
    { partNumber: 'RUN-CAP-25UF', description: 'Run Capacitor 25uF 450V', brand: 'Ducati', priceKES: 1200, application: 'Single phase', suppliers: ['Electrical wholesalers'] },
    { partNumber: 'RUN-CAP-40UF', description: 'Run Capacitor 40uF 450V', brand: 'Ducati', priceKES: 1500, application: 'Single phase', suppliers: ['Electrical wholesalers'] },
  ],
  fans: [
    { partNumber: 'FAN-100MM', description: 'Cooling Fan 100mm', brand: 'Generic', priceKES: 800, application: 'Small motors', suppliers: ['Motor shops'] },
    { partNumber: 'FAN-120MM', description: 'Cooling Fan 120mm', brand: 'Generic', priceKES: 1000, application: 'Medium motors', suppliers: ['Motor shops'] },
    { partNumber: 'FAN-150MM', description: 'Cooling Fan 150mm', brand: 'Generic', priceKES: 1500, application: 'Large motors', suppliers: ['Motor shops'] },
    { partNumber: 'FAN-COVER-100', description: 'Fan Cover 100mm', brand: 'Generic', priceKES: 600, application: 'Small motors', suppliers: ['Motor shops'] },
    { partNumber: 'FAN-COVER-150', description: 'Fan Cover 150mm', brand: 'Generic', priceKES: 1200, application: 'Large motors', suppliers: ['Motor shops'] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MAINTENANCE SCHEDULES
// ═══════════════════════════════════════════════════════════════════════════════
export const MOTOR_MAINTENANCE_SCHEDULES = {
  general: {
    daily: [
      { task: 'Visual inspection', procedure: 'Check for unusual noise, vibration, heat, or smell', tools: ['None'] },
      { task: 'Check motor load', procedure: 'Verify motor not overloaded (current within rating)', tools: ['Clamp meter'] },
    ],
    weekly: [
      { task: 'Check ventilation', procedure: 'Ensure cooling fins and air paths are clear', tools: ['None'] },
      { task: 'Check for leaks', procedure: 'Look for oil or grease leaks around bearings', tools: ['None'] },
    ],
    monthly: [
      { task: 'Clean exterior', procedure: 'Wipe or blow off dust and debris', tools: ['Cloth', 'Compressed air'] },
      { task: 'Check connections', procedure: 'Verify terminal box connections tight', tools: ['Screwdriver'] },
      { task: 'Measure current', procedure: 'Record running current on all phases', tools: ['Clamp meter'] },
    ],
    quarterly: [
      { task: 'Insulation resistance', procedure: 'Megger test motor windings', tools: ['Megger'] },
      { task: 'Vibration check', procedure: 'Check vibration levels', tools: ['Vibration meter'] },
      { task: 'Bearing inspection', procedure: 'Listen for bearing noise, check temperature', tools: ['Stethoscope', 'IR thermometer'] },
    ],
    annually: [
      { task: 'Full electrical test', procedure: 'IR, PI, winding resistance, current balance', tools: ['Test equipment'] },
      { task: 'Bearing lubrication', procedure: 'Re-grease bearings per schedule', tools: ['Grease gun'] },
      { task: 'Alignment check', procedure: 'Verify motor-load alignment', tools: ['Alignment tools'] },
      { task: 'Coupling inspection', procedure: 'Check coupling condition and alignment', tools: ['Visual'] },
    ],
  },
  critical: {
    daily: [
      { task: 'Temperature monitoring', procedure: 'Check winding and bearing temperatures', tools: ['IR thermometer'] },
      { task: 'Current monitoring', procedure: 'Verify current balanced and within spec', tools: ['Clamp meter'] },
      { task: 'Vibration check', procedure: 'Quick vibration check', tools: ['Vibration pen'] },
    ],
    weekly: [
      { task: 'Detailed inspection', procedure: 'Check all mounting, connections, condition', tools: ['Full toolkit'] },
      { task: 'Record operating data', procedure: 'Log voltage, current, temperature, vibration', tools: ['Test equipment'] },
    ],
    monthly: [
      { task: 'Thermographic survey', procedure: 'IR scan of motor and connections', tools: ['Thermal camera'] },
      { task: 'Vibration analysis', procedure: 'Detailed vibration spectrum analysis', tools: ['Vibration analyzer'] },
      { task: 'Insulation resistance', procedure: 'Megger test and trend', tools: ['Megger'] },
    ],
    quarterly: [
      { task: 'Oil analysis', procedure: 'Analyze bearing oil/grease (if applicable)', tools: ['Sample kit'] },
      { task: 'Motor current analysis', procedure: 'Detailed current spectrum analysis', tools: ['MCA equipment'] },
      { task: 'Alignment verification', procedure: 'Laser alignment check', tools: ['Laser alignment'] },
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// KENYA SUPPLIERS DATABASE
// ═══════════════════════════════════════════════════════════════════════════════
export const MOTOR_KENYA_SUPPLIERS = [
  { name: 'Kenya Motor Rewinders', location: 'Nairobi Industrial Area', specialization: 'Motor rewinding, repairs', phone: '+254 20 xxx xxxx', email: 'info@kenyamotors.co.ke' },
  { name: 'SKF Kenya', location: 'Nairobi', specialization: 'Bearings, seals, lubrication', phone: '+254 20 xxx xxxx', email: 'kenya@skf.com' },
  { name: 'Davis & Shirtliff', location: 'Nationwide', specialization: 'Pumps, motors, electrical', phone: '+254 20 xxx xxxx', email: 'sales@dayliff.com' },
  { name: 'Holman Brothers', location: 'Nairobi', specialization: 'Motors, generators, electrical', phone: '+254 20 xxx xxxx', email: 'sales@holman.co.ke' },
  { name: 'Electric Motor Services', location: 'Mombasa', specialization: 'Motor repairs, rewinding', phone: '+254 41 xxx xxxx', email: 'info@ems.co.ke' },
  { name: 'Kenya Electrical Industries', location: 'Nairobi', specialization: 'Motor manufacturing, repairs', phone: '+254 20 xxx xxxx', email: 'sales@kei.co.ke' },
];

// Export all
export const MOTOR_BIBLE_DATA = {
  faultCodes: MOTOR_FAULT_CODES,
  repairManuals: MOTOR_REPAIR_MANUALS,
  partsCatalogue: MOTOR_PARTS_CATALOGUE,
  maintenanceSchedules: MOTOR_MAINTENANCE_SCHEDULES,
  suppliers: MOTOR_KENYA_SUPPLIERS,
};
